### ISSUE TITLE
Activation issues when wp-admin is behind HTTP-auth

### ISSUE THREAD

**Issue by joho1968** [Automattic/wordpress-activitypub#1000]
### Quick summary

It seems like the plugin cannot be activated if /wp-admin/ is behind HTTP-auth

### Steps to reproduce

1. Activcate HTTP-auth for /wp-admin/
2. Go to /wp-admin/ and login to your site as an administrator
3. Attempt to activate the plugin

### What you expected to happen

I expect activation to not fail 😉 

### What actually happened

The activation failed

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

I can't think of anything else that may have caused this ...

Unfortunately, I don't seem to be able to find any further log information ... there's nothing in the PHP log, and there's nothing (useful) in the `access_log` or `error_log` files.

**Comment by pfefferle** [comment]
Is there any error message you can share or does it simply not activate?

**Comment by joho1968** [comment]
Well, I see `Plugin could not be activated because it triggered a fatal error.` at the top of the admin screen.

There are no errors in the PHP log file, nor in `error_log` or `access_log` (Apache).

In the Query monitor (plugin) output, I see this:

`PHP errors were triggered during an Ajax request. See your browser developer console for details.`

and

`GET https://www.mysite.com/wp-admin/plugins.php?plugin=activitypub%2Factivitypub.php → 200`

I can't, however, see anything in the developer console that I would relate to this.

Unless this is related to that:

`Content-Security-Policy: The page’s settings blocked a worker script (worker-src) at blob:https://www.mysite.com/6f288be1-c660-44fa-a038-2ee6ea064cf7 from being executed because it violates the following directive: “script-src 'self' 'unsafe-inline' 'unsafe-eval' http: https: https://*.wp.com https://*.wordpress.com”`

**Comment by pfefferle** [comment]
Is it possible to install and activate other plugins?

**Comment by joho1968** [comment]
Yes. This is the first time I've seen this happen on this site (i.e. this is the only plugin giving me a 🤯 ...

**Comment by pfefferle** [comment]
Thanks for your feedback, I will try to reproduce it, to see what we do different from other plugin devs.

**Comment by joho1968** [comment]
Sorry I couldn't provide more specifics, but there really isn't anything worth mentioning in the logs. How are you "activating"?

I can only see two potential "culprits" (although they work with other plugins), one is HTTP-auth for /wp-admin/, and the other is that I'm using fail2wp. But I can't really find anything related to those two things either during the failed activation attempt.

**Comment by obenland** [comment]
> Content-Security-Policy: The page’s settings blocked a worker script (worker-src) at blob:https://www.mysite.com/6f288be1-c660-44fa-a038-2ee6ea064cf7 from being executed because it violates the following directive: “script-src 'self' 'unsafe-inline' 'unsafe-eval' http: https: https://*.wp.com https://*.wordpress.com”

@joho1968 If your site is hosted on WordPress.com and you feel comfortable sharing the URL, I could try to find system logs that might help debug this further?

Not sure there's much else to sink our teeth in, I'm afraid.

**Comment by obenland** [comment]
Let's close this for now, while we don't know what it is that causes the error. Happy to re-open when there are other reports or more actionable details to follow up on.
