### ISSUE TITLE
PHP Warnings (maybe) triggered by ActivityPub plugin

### ISSUE THREAD

**Issue by rghedin** [Automattic/wordpress-activitypub#1007]
### Quick summary

I've been trying to track down what plugin is causing a surge in “PHP Warning” erros in my WP instance, hosted at WordPress\.com.

I set up a staging site and deactivated one plugin at a time, checking out how they affect my logs. After deactivating ActivityPub plugin, the error messages disappeared.

They look like this:

![Image](https://github.com/user-attachments/assets/b63507c4-dc7b-4788-bb73-eeb3984172a8)

Transcription:

> **Message:** PHP Warning:  foreach() argument must be of type array|object, null given in /wordpress/core/6.7/wp-admin/includes/plugin.php on line 1853
> **Timestamp:** 2024-11-20T20:52:05.000Z
> **Type:** core
> **Name:** 6.7
> **File:** /wordpress/core/6.7/wp-admin/includes/plugin.php
> **Line:** 1853

I'm really not sure if they are caused by AP plugin; it's just my main suspicion. I also suspect it may be something related to the WordPress\.com interventions with MU plugin and Jetpack, which causes some headaches from time to time.

I hope this report helps anyway.

### Steps to reproduce

1. Activate AP plugin.
2. Wait.
3. Check “Logs” (not sure if it's available in self-manage WP or only in Business WP.com accounts).

### What you expected to happen

No errors appearing.

### What actually happened

PHP Warnings appear frequently.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
phew... that is hard to debug, but I will keep my eyes open if I can see similar issues!

**Comment by obenland** [comment]
Looks like this gets triggered within `remove_menu_page()` when the global `$menu` is null. I've not been able to re-create it.

https://github.com/WordPress/wordpress-develop/blob/6.7/src/wp-admin/includes/plugin.php#L1853


@rghedin We'll keep an eye out for it but will close for now since it's not reproducible. Please feel free to re-open when that changes!

**Comment by rghedin** [comment]
Maybe it isn't related to AP plugin, after all. I searched my WordPress theme for `remove_menu_page()` references and found a couple on `functions.php`. Probably the culprit.

Sorry about the false alarm, @obenland!
