### ISSUE TITLE
How to favour `read-more` over excerpt?

### ISSUE THREAD

**Issue by shtrom** [Automattic/wordpress-activitypub#1035]
I have found #556, and #856

However, I can't work out how to use it.

I write custom excerpts for my post, for summary views, but I'd like the Fediverse post to use the beginning of the post down to the `read-more` separator.

Using `[ap_excerpt]` uses the custom excerpt, and neither `[activitypub_content_more]` nor `[ap_content_more]` (random but promising strings from #856) are supported.

Is there a way to specifically favour the post content down to the `read-more` separator in Fediverse posts _even if a custom excerpt exists_?

And if so, is it documented somewhere (couldn't find it in either the short or longer help)?

**Comment by pfefferle** [comment]
There is currently no way to force a specific option!

The current priority is:

1. use the post excerpt if it exists.
2. fall back to the first part of the post content if it contains the `<!--more-->` tag.
3. fall back to an excerpt of the post content if it is longer than the specified length.

In the code: https://github.com/Automattic/wordpress-activitypub/blob/6c18433965d291459cc00ea885808ffc3bc8dea0/includes/functions.php#L1291

**Comment by pfefferle** [comment]
I will close this, because we do not plan to support this very special case, but you can implement it on your own, by using a filter or your own shortcode. Let us know if we can support you on this.
