### ISSUE TITLE
ActivityPub note content settings were reset

### ISSUE THREAD

**Issue by sindastra** [Automattic/wordpress-activitypub#1043]
### Quick summary

Hi, I noticed that the ActivityPub Note "content" settings were reset after some update. Based on the dates of the affected posts, it must have happened in the 4.1.0 or 4.1.1 update.

My personal settings were:

```html
<strong>[ap_title]</strong>

[ap_excerpt]

[ap_permalink type="html"]

[ap_hashtags]
```

Which were reset around the time of those updates to:

```html
[ap_title type="html"]

[ap_content]

[ap_hashtags]
```

### Steps to reproduce

1. Host a site with ActivityPub and custom note settings
2. Update to ActivityPub 4.1.0 and/or 4.1.1 and see the changes reset (suspected versions)

This is at least the suspected way to reproduce.

### What you expected to happen

The settings should not change on their own.

### What actually happened

The settings were reset to some default (note that this happened on another site I run, too!)

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Logs or notes

I wanted to share my workaround with you:

I changed the settings back to how I used to have them, then trashed all affected posts and republished them with the original date.

This worked at least partially: Misskey seems to have gotten the updated posts, but on Mastodon the posts have simply permanently vanished, even manually inputting the URL of the article into the search box yields "no results" which suggests something broke from trashing and republishing.

This makes me wonder if maybe there should be a "republish to Fediverse" button or something, to force a refresh for edge cases like this? It's really unfortunate to just "lose" posts like this.

**Comment by pfefferle** [comment]
I am very sorry about that @sindastra ! I made a mistake in the migration that caused the reset of your content-template. This is fixed now and should not happen again.

> I changed the settings back to how I used to have them, then trashed all affected posts and republished them with the original date.

If you trash a post, the plugin will send a `Delete` Activity and (as far as I know), this is irrevocable on Mastodon. This is why a re-publish under the same ID/URL does not work.

If you want to update a post the next time, you simply have to change something small in the post (could be as simple as adding a white space), then the Plugin will send an update automatically.

**Comment by obenland** [comment]
@pfefferle Could you link to the PR that fixed this, for posterity?

**Comment by pfefferle** [comment]
@obenland https://github.com/Automattic/wordpress-activitypub/commit/82786d16298e2385a6181336da57cf9fcb81d0de released in https://github.com/Automattic/wordpress-activitypub/releases/tag/4.1.1

**Comment by obenland** [comment]
Closing as fixed in https://github.com/Automattic/wordpress-activitypub/commit/82786d16298e2385a6181336da57cf9fcb81d0de.

**Comment by sindastra** [comment]
Hello @pfefferle ! Thank you for your quick response.

> I am very sorry about that @sindastra ! I made a mistake in the migration that caused the reset of your content-template. This is fixed now and should not happen again.

Thank you. I understand mistakes can happen from time to time, and we're all just human after all. 😊 I'm glad to hear it's been fixed, so I don't have to worry about future posts breaking.

Now, as for the "aftermath", I do have a few questions to get a better picture, if I may:

1. When you mention the plugging sending an update after a small edit, do you mean the same sort of update which in Mastodon terms is known as the "edit" feature?
2. Will said update honor the updated note template setting? As in, I update the note template, add a whitespace to the article, and it will update it to look like the latest template setting (regardless of whether the template actually includes the post contents, i.e. just the excerpt)?
3. When you mention a re-publish under the same ID/URL not being possible, is this an `&&` or `||` condition, or do you mean to say that the URL **_is_** the ID?

I hope you don't mind me asking these questions so I can get a better understanding of what's going on behind the scenes. This information would be very valuable for me to potentially find a workaround, as those affected posts are now simply "gone". Thank you for your time.

**Comment by pfefferle** [comment]
> Thank you. I understand mistakes can happen from time to time, and we're all just human after all. 😊 I'm glad to hear it's been fixed, so I don't have to worry about future posts breaking.

☺️

> When you mention the plugging sending an update after a small edit, do you mean the same sort of update which in Mastodon terms is known as the "edit" feature?

Exactly! Every time you hit the save button on a post, the plugin sends an update of the post to your followers, and they will see the updated version then.

> Will said update honor the updated note template setting? As in, I update the note template, add a whitespace to the article, and it will update it to look like the latest template setting (regardless of whether the template actually includes the post contents, i.e. just the excerpt)?

Exactly! Because the template defines the content of every blog post, it will used for every update. You can check how this looks like, by adding `?activitypub` at the end of a posts URL or if you use the preview button in the block editor.

> Will said update honor the updated note template setting? As in, I update the note template, add a whitespace to the article, and it will update it to look like the latest template setting (regardless of whether the template actually includes the post contents, i.e. just the excerpt)?

The URL was the ID, but we changed the ID to `https://example.com/?p=<post-id>`. So a "re-publish" will only work if you clone the post and publish it under a new ID. But this will break all conversations that already happend, so I would recommend to send an update instead!

> I hope you don't mind me asking these questions so I can get a better understanding of what's going on behind the scenes.

Not at all, I am happy to help when I can!

Let me know if that makes sense to you or if you have ideas how to make it easier to understand!

**Comment by sindastra** [comment]
Hello @pfefferle ! Thank you for your elaborate response, and apologies for my delayed comeback, you know, life and things happening. 😊

> The URL was the ID, but we changed the ID to https://example.com/?p=<post-id>. So a "re-publish" will only work if you clone the post and publish it under a new ID. But this will break all conversations that already happend, so I would recommend to send an update instead!

1. Ok, do I understand correctly that currently the WordPress' internal post ID is used as ActivityPub post ID?
2. Am I correct to understand that deletions are permanent on Mastodon and a republish will always use the same ID with this plugin,
3. And therefore republish after deletion won't work on Mastodon,
4. But if we were to change the ID to be based on, say, `rand()` or `openssl_random_pseudo_bytes()` (just as example), a repost would work,
5. but the downside of the previous point is that current conversations/threads would be lost?
