### ISSUE TITLE
All activitypub users exposed in Lemmy communities

### ISSUE THREAD

**Issue by harcesz** [Automattic/wordpress-activitypub#1046]
### Quick summary

Hi, 

when a blog is displayed as a Lemmy community ([example](https://szmer.info/c/kolektyw@adapulawska.org)) all AP enabled users on the wordpress are listed as moderators. 

I know the accounts are publicly accessible and can be listed by anyone, but if providing this information to Lemmy for display could be made adjustable (default to the blog profile, adjusted list or hidden) it would be preferred.  

Thanks for your great work! 

### Steps to reproduce

Display a AP enabled blog as a community on any lemmy instance. 

### What you expected to happen

providing this information to Lemmy for display could be made adjustable (default to the blog profile, adjusted list or hidden) it would be preferred.  

### What actually happened

all AP enabled users on the wordpress are listed as moderators

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
I think this is too specific and complicated to work as a setting, but I agree it's good to have it filterable.

I'll add a filter to the output, so you can customize the list as needed.
