### ISSUE TITLE
Template blocks for Likes and Reposts: display them on the frontend

### ISSUE THREAD

**Issue by obenland** [Automattic/wordpress-activitypub#1057]
Create a general reactions block that contains both likes and reblogs as a face pile.

See https://notiz.blog/2024/09/13/the-fediverse-files/

**Comment by jeherve** [comment]
Related issues:

- https://github.com/Automattic/wordpress-activitypub/issues/235
- https://github.com/Automattic/wordpress-activitypub/issues/929

**Comment by pfefferle** [comment]
@jeherve I think #929 is more about having likes/dislikes for comments.
