### ISSUE TITLE
Fix comment count

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wordpress-activitypub#1069]
On posts that receive Likes and/or Reposts, the comment count is wrong. We should exclude likes and reposts from the count.

Eg: this post: https://mattwiebe.blog/2024/11/24/support-week-for-activitypub-for-wordpress/

![Image](https://github.com/user-attachments/assets/40decda0-d8aa-4e71-bd3b-e125f97419dd)

Shows "34 responses" in the comments section. It should only show 5 responses, after the 29 combined likes and reposts are removed from it.

List of possible hooks:

* [ ] [`get_comments_number`](https://developer.wordpress.org/reference/functions/get_comments_number/)
* [ ] [`wp_count_comments`](https://developer.wordpress.org/reference/functions/wp_count_comments/)
* [X] [`pre_wp_update_comment_count_now`](https://developer.wordpress.org/reference/functions/wp_update_comment_count_now/)
* [ ] [`get_page_of_comment_query_args`](https://developer.wordpress.org/reference/functions/get_page_of_comment/)?
* [ ] [`parse_comment_query`](https://developer.wordpress.org/reference/hooks/parse_comment_query/)?

**Comment by obenland** [comment]
I looked into that a bit the other day. It won't be a slam dunk, I'm afraid. WP has multiple ways to store and retrieve comment counts :(

**Comment by pfefferle** [comment]
@mattwiebe @obenland let's collect the list of hooks in the issue. I started adding `get_comments_number`!

**Comment by obenland** [comment]
`get_comments_number` grabs the count from a post field that's saved in the database, it doesn't calculate that number. That way it can be used in the front-end relatively cheaply.

I guess the question is, should we hook into the place where that number gets updated, rather than displayed?

**Comment by mattwiebe** [comment]
> should we hook into the place where that number gets updated, rather than displayed

I think it would make most sense to hook into where it gets updated and saved to the DB, unless that breaks something somewhere else, like in `wp-admin/edit-comments.php`.

**Comment by NiceGuy2065** [comment]
Unfortunately, it seems that Version 5.7.0 brought this bug back.

Reactions (likes, reposts) are again counted as "comments".
