### ISSUE TITLE
Fediverse reactions section - some profile pictures not displayed correctly

### ISSUE THREAD

**Issue by trozman** [Automattic/wordpress-activitypub#1101]
### Quick summary

Fediverse reactions section (under the blog post):
Some pictures are not displayed correctly (large ellipse instead of circle). See the attached image.
It seems that the **accounts with no profile picture** set cause this error.

![Image](https://github.com/user-attachments/assets/0f74f94b-2284-40f9-a4b6-d0167dc4e4f4)

### Steps to reproduce

1. Go to https://blog.rozman.info/flashing-xiaomi-ble-sensors-and-integarting-it-in-home-assistant/
2. Check the Fediverse reactions section under the post
3. See the second row of profile pictures (likes), the second one (ellipse). 

### What you expected to happen

The profile picture to be shown in a circle. If no profile picture is set, at least circle with initials could be displayed.

### What actually happened

A large ellipse with name and surname in the center appeared instead of circle with profile picture

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Environment:
- WordPress 6.7.1 running Twenty Twenty-Three theme.
- Latest AP plugin - 4.5.1

**Comment by obenland** [comment]
Thanks for adding a link in the bug description @trozman, that was helpful!

**Comment by trozman** [comment]
Thank you for quick fix! 
This morning I opened the blog and it looks ok now!
