### ISSUE TITLE
Unable to find blog or user profiles via mas.to or mastodon.social after setup

### ISSUE THREAD

**Issue by IAmDarthMole** [Automattic/wordpress-activitypub#1114]
### Quick summary

I'm placing this here because I'm unable to use the support forum due to do being unable to create a new user account while the team is on holiday break. I also feel that the situation is a bug as I've confirmed with the hosting company that there aren't any errors that they can see.

I'm running...

Wordpress Version 6.7.1
ActivityPub Version 4.6.0 
Security Optimizer Version 1.5.7 
Speed Optimizer Version 7.7.2 
WebFinger Version 3.2.7 

Speed and Security Optimizers are only installed to turn off all their settings. When I had uninstalled them before it seems there were still settings interfering.

I was receiving an error about not being able to see the profile but that has since disappeared. I now only have an error related to "WebFinger endpoint is not accessible" even though I've installed the plugin. When I expand the drop down it is blank so I can't fix it/get rid of it.

After installing and setting up ActivityPub (I have profiles and blog setting selected) I am unable to find neither when using search in mas.to and mastodon.social (not logged in and logged-in).

I'm still setting up the website so it isn't the end of the world, plus it is the holidays, but I answered the last couple of questions as accurately to the situation as possible.

Thank you and happy holidays if you celebrate this time of year!

### Steps to reproduce

1. Go to mas.to or mastodon.social
2. Search for @TheMadMole@madmolelabs.com (user), madmolelabs@madmolelabs.com (blog), or @madmolelabs@madmolelabs.com (blog)

### What you expected to happen

Should be able to find the profile(s).

### What actually happened

Both sites say they can't find anything related to the search.

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment]
I am sorry, but I have bad news for you: siteground blocks the WebFinger path completely, so there is no chance to make this work without their support.

You can find some background infos here: https://wordpress.org/support/topic/doesnt-work-at-all-218/

**Comment by pfefferle** [comment]
I will close this for now, because it is no direct issue of the plugin, but you can still comment if you have further questions!

**Comment by IAmDarthMole** [comment]
**Thank you very much** for the information and links! I have reached out to siteground.com and this is there response:

```
I am afraid the plugin requires a custom modification of the Nginx setup that we cannot accommodate.

The ".well-known" folder is a system folder, and due to security reasons, access to it is limited to specific queries only.

However, as a workaround, you may be able to resolve this issue by manually creating the "webfinger" file inside that folder.

For your convenience, I have manually created the file, which is accessible by the "webfinger" service:

https://webfinger.net/lookup/?resource=https%3A%2F%2Fmadmolelabs.com%2F

Note that you can ignore the JSON warning, which is returned because the file has no data.

You should now save the following JSON code in that file:

{
    "subject": "AUTHOR_USERNAME@madmolelabs.com",
    "aliases": [
        "https://madmolelabs.com/author/AUTHOR_USERNAME/"
    ],
    "links": [
        {
            "rel": "self",
            "type": "application/activity+json",
            "href": "https://madmolelabs.com/author/AUTHOR_USERNAME/"
        },
        {
            "rel": "http://webfinger.net/rel/profile-page",
            "type": "text/html",
            "href": "https://madmolelabs.com/author/AUTHOR_USERNAME/"
        }
    ]
}



Where you need to replace "AUTHOR_USERNAME" with your actual username.
```

I updated the script with **TheMadMole** for **AUTHOR_USERNAME**, however, I'm not sure if that is accurate. Can you please confirm if it should just be TheMadMole or perhaps @TheMadMole@madmolelabs.com?

Also, after siteground added the file and I added the above script with "TheMadMole" the webfinger error in the Site Health section disappeared.

**Comment by pfefferle** [comment]
You should use `https://madmolelabs.com/?author=1` instead of `https://madmolelabs.com/author/TheMadMole/` but the rest should be fine!

**Comment by IAmDarthMole** [comment]
Thank you very much! It worked!
