### ISSUE TITLE
Unable to follow profiles with wordpress activitypub profile

### ISSUE THREAD

**Issue by IAmDarthMole** [Automattic/wordpress-activitypub#1115]
### Quick summary

When I select "Follow" on a profile either using mas.to or mastodon.social (not logged in to either), it says I'm not logged in and to enter the domain of my server. When I enter and select madmolelabs.com it redirects me but then gives me the 404 error page. I'm not 100% sure but I'm thinking I should be able to "Follow" accounts/profiles/channels with my wordpress profile?

The same response and behavior happens if I select the "Boost" option.

However, when I use the "reply to" bookmark provided by the ActivityPub settings (and site tools) the reply appears on my wordpress **and** in the comments of the correct post. So the reply functionality seems to work.

I'm able to find my wordpress profile via mas.to and mastodon.social and the following code is in my webfinger file.

The same behavior is also showing through the Friends plugin and page.

```
{
    "subject": "TheMadMole@madmolelabs.com",
    "aliases": [
        "https://madmolelabs.com/?author=1"
    ],
    "links": [
        {
            "rel": "self",
            "type": "application/activity+json",
            "href": "https://madmolelabs.com/?author=1"
        },
        {
            "rel": "http://webfinger.net/rel/profile-page",
            "type": "text/html",
            "href": "https://madmolelabs.com/?author=1"
        }
    ]
}
```

Earlier the code was the following and I was having the same problem.

```
{
    "subject": "TheMadMole@madmolelabs.com",
    "aliases": [
        "https://madmolelabs.com/author/TheMadMole/"
    ],
    "links": [
        {
            "rel": "self",
            "type": "application/activity+json",
            "href": "https://madmolelabs.com/?author=1"
        },
        {
            "rel": "http://webfinger.net/rel/profile-page",
            "type": "text/html",
            "href": "https://madmolelabs.com/?author=1"
        }
    ]
}
```

The environment
Wordpress Version 6.7.1
ActivityPub Version 4.6.0
Security Optimizer Version 1.5.7
Speed Optimizer Version 7.7.2
WebFinger Version 3.2.7
SiteGround.com for hosting

Thank you very much!

### Steps to reproduce

To Follow: 

1. Go to mas.to or mastodon.social
2. Search for a profile that you aren't following.
3. Select the "Follow" option
4. Enter madmolelabs.com and hit enter.

To Boost:

1. Go to mas.to or mastodon.social
2. Search for a post.
3. Select the "Boost" option
4. Enter madmolelabs.com and hit enter.

### What you expected to happen

To Follow:

I would assume it would reload the correct page in my site and show that I've followed the account in question.

To Boost:

Would reload me into a "create post" page with all the information filled out so I can hit save and publish. This would add the boost/repost to my wordpress and then increase the "boost" count on the post in question wherever it was posted (mas.to or mastodon.social).

### What actually happened

Reloads a 404 page on my wordpress installation.

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment]
To make remote communication possible, you have to add:

```JSON
{
      "rel": "http://ostatus.org/schema/1.0/subscribe",
      "template": "https://madmolelabs.com/wp-json/activitypub/1.0/interactions?uri={uri}"
},
```

to your WebFinger endpoint.

> Would reload me into a "create post" page with all the information filled out so I can hit save and publish. This would add the boost/repost to my wordpress and then increase the "boost" count on the post in question wherever it was posted (mas.to or mastodon.social).

But this only works for replies, boosts are not yet supported: https://github.com/Automattic/wordpress-activitypub/issues/973

> I would assume it would reload the correct page in my site and show that I've followed the account in question.

The plugin does not support following others (yet), but there is a plugin that bridges this gap: https://wordpress.org/plugins/friends/

**Comment by IAmDarthMole** [comment]
Thank you very much for the reply and clarifications! I've updated my WebFinger endpoint file with the following, can you please confirm it is accurate?

```
{
    "subject": "TheMadMole@madmolelabs.com",
    "aliases": [
        "https://madmolelabs.com/author/TheMadMole"
    ],
    "links": [
        {
            "rel": "http://ostatus.org/schema/1.0/subscribe",
            "template": "https://madmolelabs.com/wp-json/activitypub/1.0/interactions?uri={uri}"
	},
        {
            "rel": "self",
            "type": "application/activity+json",
            "href": "https://madmolelabs.com/?author=1"
        },
        {
            "rel": "http://webfinger.net/rel/profile-page",
            "type": "text/html",
            "href": "https://madmolelabs.com/?author=1"
        }
    ]
}
```

Also, just to confirm, would it be accurate to say, as of this moment, that ActivityPub plugin is more of a Fediverse publishing tool vs what I would call a social media/fediverse server/client? IE: With just the ActivityPub I can post my own content to the Fediverse and Reply to Posts (which also publishes to my Wordpress), but I can't use it as a Mastodon client. 

If I add Enable Mastodon Apps **without** Friends will the above functionality come into play or the same limitations still apply?

Thank you again for your time, efforts, and awesome plugin!

**Comment by IAmDarthMole** [comment]
~~Additionally, are there known situations where a mastodon instance (IE: mas.to) may have settings applied that prevent posting of replies via the "Reply to" browser shortcut/bookmark?~~

~~I've noticed that I can successfully reply to posts on mastodon.social but not mas.to~~

~~I also thought it may be related to the above.~~

~~Thanks!~~

Please disregard, the replies have since appeared on mas.to (maybe it was a caching issue?).

**Comment by pfefferle** [comment]
@IAmDarthMole the posts will be sent asynchronously via a cron, so it might last some time.
