### ISSUE TITLE
Tags in posts are being injected into Wordpress tags list

### ISSUE THREAD

**Issue by iLeif-de** [Automattic/wordpress-activitypub#1117]
### Quick summary

When having strings like color codes like #fff or other texts like #Hugo in the page content, these becomes automatically tags, shown as tags in the post, mastodon post and in the blogs tags list. I often publish some code, and this behavior is annoying. 

Might be the same issue as in https://github.com/Automattic/wordpress-activitypub/issues/1105

Happens with Activitypub Version 4.6.0 and Wordpress 6.7.1, when the plugin is active, when not the tags are not added.

### Steps to reproduce

1. Activate the Activitypub plugin.
2. Create a new post
3. Just add #Hugo
4. Save the post
5. Check the tag box, #Hugo will be added.
6. If not publish the post, at least then it will be added, as well in the tag list

### What you expected to happen

Only tags that will be add manually to the tag area will be saved and posted. No tag like strings from the post (e.g. color code)

### What actually happened

e.g. color codes from source examples in post will become tags

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

MacOS 15.2
latest Safari and Chrome

Activitypub Version 4.6.0
Wordpress 6.7.1,

**Comment by pfefferle** [comment]
You can deactivate the hashtags feature in the settings!

**Comment by iLeif-de** [comment]
This is embarrassing, I think I should get a new pair of glasses. I'm not sure why, but I checked the settings several times and overlooked this point. To keep some self-respect, I would suggest that after the installation you have to turn on the automatic tagging first. 
Sorry and happy new year,
Leif

**Comment by pfefferle** [comment]
No problem ☺️

> To keep some self-respect, I would suggest that after the installation you have to turn on the automatic tagging first.

If some more users have issues with the opt-out, we can sure change that to opt-in!

A happy new year for you too 🎉
