### ISSUE TITLE
Strip @username from comment

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#143]
Every comment starts with "@username" which does not make sense in the comment section of the Post. 

It would be nice if this could be stripped automatically (or maybe if the administrator of the site can choose to do so)

**Comment by pfefferle** [comment]
Keep!

**Comment by jaschaurbach** [comment]
keep!

**Comment by pfefferle** [comment]
Keep

**Comment by pfefferle** [comment]
keep!
