### ISSUE TITLE
Template placeholder for Mastodon-ID of the author

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#144]
It would be great if there would be a placeholder like %author% which replaces with the mastodon-ID you enter int the Wordpress-profile of the user. 

My Blog has the ID @tomate@jascha.wtf
My personal ID is @herrurbach@chaos.social 

I would love to be able to add something in my template like "by %author%" which then replaces to "by @herrurbach@chaos.social" so when people do write comments while I am on the run I would get a notification in my client as well as have a comment in my Wordpress.

**Comment by pfefferle** [comment]
Keep!

**Comment by jaschaurbach** [comment]
Keep!

**Comment by pfefferle** [comment]
Keep

**Comment by pfefferle** [comment]
Now that is comes up again: why not add it directly to the box? Placeholder are mainly for changing content, but if you want to add something that is static and valid for all posts, simply add it to the template box. The box also supports HTML.

**Comment by pfefferle** [comment]
@jaschaurbach does this ☝️ work for you?
