### ISSUE TITLE
Can't follow from Pleroma

### ISSUE THREAD

**Issue by hikerus** [Automattic/wordpress-activitypub#151]
Thanks for this cool plugin. I can follow the WP Blog from Matodon but from Pleroma there is a problem. I see the account when searching form Pleroma, I can follow - but it says with "request sent". A new blog entry isn't displayed in Pleroma.

Wordpress and Pleroma with recent versions.

**Comment by pfefferle** [comment]
Can you give me your Blog-URL/WebFinger handle?

**Comment by hikerus** [comment]
Wordpress Blog is on https://wp.fedcast.ch

**Comment by pfefferle** [comment]
items will not be pulled actively... have you tried to publish a new blogpost?

**Comment by rickgardner077** [comment]
> @rickgardner077 items will not be pulled actively... have you tried to publish a new blogpost?
Yes, I published a post AFTER following in Pleroma. The blog post is not pulled to Pleroma and not shown in any timeline. However, on searching for the post in the search bar within Pleroma with the URL of the blog post as query the post appears in the profile. Still, the "Following" button seems to get stuck on "Request sent!".

**Comment by mediaformat** [comment]
Maybe related to #88

**Comment by hikerus** [comment]
Any news about this problem? Still exists.

**Comment by hikerus** [comment]
Hmm, any hope for a fix?

**Comment by mwt** [comment]
I can't follow from Pleroma, but can follow from several different mastodon instances. There must be something different about the follow implementation.

It shows follow requested, but the panel in WP lists it as a follow and the Mastodon instances see the Pleroma account as a follower.

**Comment by hikerus** [comment]
I would be very grateful if this bug would be fixed soon. Thank you.

**Comment by mwt** [comment]
@hikerus If I try to follow from Pleroma, I just get the classic "follow request pending"

![follow request pending in pleroma](https://user-images.githubusercontent.com/13644285/192862256-cb80e2dd-198b-4a2f-8184-66a0086b6fd1.png)

I assume it's expecting some confirmation from the server that it's not receiving for some reason. I think this is why the posts are not actually appearing.

I don't think comments are the only solution. If I like or boost the post on another platform, it will show up for me on Pleroma.

**Comment by hikerus** [comment]
When I reload the page in #Pleroma where I followed a WP account then it says "End following" - so the connection seems to be established. But as already said: New WP posts don't show up in my TL in #Pleroma.

**Comment by mwt** [comment]
Hmm. Maybe these are separate issues then. I cannot get it to follow at all. The screenshot I sent was for a follow request I sent to myself last year.

It's still pending.

**Comment by hikerus** [comment]
Should I try from my instance to follow this account and see the result?

**Comment by mwt** [comment]
Sure. It's `@chris@chriskthomas.com`

https://apfollow.mwt.me/?user=chris&instance=chriskthomas.com

**Comment by mwt** [comment]
I see. Maybe there's something wrong with my Pleroma instance then.

**Comment by pfefferle** [comment]
I also tried this lately and it worked fine. Is this still an issue?

**Comment by hikerus** [comment]
I just tested it. A new article shows up without problems on a #Calckey or #Mastodon instance. But on the #Pleroma instance I can' see it - only if I insert the URL of the article in "search" it is found and displayed. So it seems the ActivityPub plugin can't send it to #Pleroma.

**Comment by mwt** [comment]
It doesn't work for me still:

![Screenshot_20230202-073350.png](https://user-images.githubusercontent.com/13644285/216339051-a481d733-35a2-4f3c-8b44-7041c21a055b.png)

**Comment by pfefferle** [comment]
Is it still an issue?

**Comment by pfefferle** [comment]
Please re-open if yes.
