### ISSUE TITLE
Name and email comment requirement blocks Mastodon replies

### ISSUE THREAD

**Issue by averymd** [Automattic/wordpress-activitypub#154]
Howdy! I found that attempts to reply to posts via Mastodon were disappearing into the void. Apache access logs revealed that there was first a 202 reply, then a 500 error, but no details made it into my Wordpress debug log. In fact, nothing ended up in my Apache error logs, either, but that might be a hosting problem.

I added some manual debugging to this plugin's code and was able to find out that my blog's requirement for a name and email address on comments was causing the error. 

I see that that's supposedly accounted for in the [`handle_create()`](https://github.com/pfefferle/wordpress-activitypub/blob/0.13.3/includes/rest/class-inbox.php#L428) and `handle_reaction()` methods:

    // do not require email for AP entries
    \add_filter( 'pre_option_require_name_email', '__return_false' );

    $state = \wp_new_comment( $commentdata, true );

    \remove_filter( 'pre_option_require_name_email', '__return_false' );

Based on an old [StackExchange answer](https://wordpress.stackexchange.com/a/179354/33955), I changed those to `__return_null` and a quick Postman test resulted in a comment (in spam probably thanks to Akismet, but not completely lost). 

I didn't submit a PR because it's been a long, long time since I've done anything other than basic theme dev in WP and I haven't done extensive testing on this, but hopefully this fix is correct.

**Comment by Cambridgeport90** [comment]
Still an issue from what I can tell.

**Comment by jaschaurbach** [comment]
I would love to be able to have the requirement for comments on the website while the comments from the fürdiverse come through. I use to have a gigantic spam problem after blogpost which go around a lot and the hurdle keeps away at least a few...

**Comment by pfefferle** [comment]
Keep!

**Comment by mediaformat** [comment]
A while back I test using webfinger in this field, predictably comments were no longer systematically held. Even the `Comment author must have a previously approved comment` setting worked.

It seems like a hack, but ultimately a the `user@domain` paradigm is compatible.

**Comment by pfefferle** [comment]
I think this is no longer an issue, please re-open if it is.
