### ISSUE TITLE
List of all the routes required?

### ISSUE THREAD

**Issue by antranigv** [Automattic/wordpress-activitypub#157]
Hi there! First of all, huge love to everyone involved in this project, it brings hope to the web!

My question is simple: Is there a list for all the routes that this plugin requires?

The reason why I'm asking is because I have a caching plugin (WP Rocket I think) and I'd like to disable caching in those routes, otherwise it's breaking.

Thanks in advance!

**Comment by pfefferle** [comment]
Good point, I will collect all routes and send you the list, but I will also add this info to the settings page.

**Comment by pfefferle** [comment]
And I am glad you like the plugin ☺️

**Comment by mwt** [comment]
@antranigv it's working for me so far with this rule in nginx and fastcgi cache

```nginx
# Skip cache if requesting json file (ActivityPub)
if ($http_accept ~* "application/ld\+json|application/activity\+json|application/json") {
        set $skip_cache 1;
}
```
and then later set `fastcgi_cache_bypass` and `fastcgi_no_cache` to `$skip_cache`. I've never used WP rocket, but maybe it also lets you bypass the cache based on header rules? In plain language the rule says:

> Bypass the cache if the Accept header contains application/ld+json OR application/activity+json OR application/json.

I'm not sure if this causes issues in edge cases though.

**Comment by andypiper** [comment]
> Good point, I will collect all routes and send you the list, but I will also add this info to the settings page.

I'm just getting started with this and think another caching plugin (WP-SuperCache) has been causing me some headaches, so I would also be interested in a list of routes or better information about how to avoid problematic cache interactions.
Thanks 👍🏻 excited to use this to have our site join the Fediverse!

**Comment by mwt** [comment]
I think that any cache plugin will break it for sure if you don't exclude things. The plugin requires posts and author pages to be served in json when requested with the headers I mentioned. If you cache those pages as json, they won't be human readable and if you cache them as html, they won't be readable by AP instances.

You need to either bypass the cache or use a separate cache token when these headers are present. I know how to do that with fastcgi and Cloudflare, but I don't know about other plugins.
