### ISSUE TITLE
Feature Request: Filter comments for # to not publish on blog

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#164]
I read some discussions and thought about how to avoid people getting angry that their answer to a post is getting federated onto the blog as well. I know, federation is about having all the things decentralized and saved on many places but people, we all knot the problem :D 

I came up with an idea: how about to define a # when used in a comment (like #noblog), this comment will not be considered as an answer to the post and will never show up as a comment. A Bonus would be that these comments will be shown on to logged in admins and authors of the post somewhere under the article or on a new page. 

Let me know what you think., I am of course open to discussion and will not be mad if this is not considered as I know the try proposal is going against the idea of federation in the Fediverse.

**Comment by mediaformat** [comment]
This is an important issue! I think we have to balance broad user expectations with actual user behaviour. 

(Mastodon) Users can choose not to have their own profiles / status indexed, but with public / unlisted replies going to other servers there are no guarantees or expectations.  

And partial indexing is not really a thing, at best we could exclude received comments that are `Unlisted` (Don't show up in the federated timelines), adding the [data-nosnippet-attr](https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag?hl=en#data-nosnippet-attr). 

The other possibility would be to accept Follower-only and Direct messages in reply to our posts, despite not currently supporting replying with the same visibility.

**Comment by jaschaurbach** [comment]
I admit, I created this request after I encountered a discussion which I do to find any more to link to it. It was about that people were not happy that their content "leaves the Fediverse" (woah) and are stored on an another website without their consent. 

I think it Is a cultural problem here that many users think Fedivers == Mastodon/Pleroma/Misskey but not a "private Website" of someone else. I thought about the easiest way to deal with it and it was "just do not show answers with a predefined hashtag"

**Comment by timnolte** [comment]
Would it be possible to still create comments in WordPress that are not public, in the cases where replies in the Fediverse were not marked public? I ask this as I understand people not wanting their replies posted public on my site but I still want then captured on my site so that I can have them available when logged into the WordPress dashboard.

**Comment by pfefferle** [comment]
Keep
