### ISSUE TITLE
Request: Custom text for profile biography

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#165]
I was rewriting my biography on my blog to for both, the website as well as the Fediverse account description. While doing so I recognized that it is not that easy.

I would love to have a second field on my author page: Fediverse Biography. If set, use it for fediverse related activities, if empty, take default biography from author. 

What do you think?

**Comment by danimrich** [comment]
I think it would be nice to have this feature. For a start, it would help alleviate confusion between the authors' Mastodon profiles and the profiles created by the plugin.

**Comment by eficklin** [comment]
Looking for opportunities to contribute and happy to take a crack at this. PR forthcoming next week, hopefully.

**Comment by pfefferle** [comment]
Keep!

**Comment by pfefferle** [comment]
done, will be part of the next release.
