### ISSUE TITLE
Template placeholders

### ISSUE THREAD

**Issue by davehill47** [Automattic/wordpress-activitypub#167]
>  [Let me know](https://github.com/pfefferle/wordpress-activitypub/issues/new) if you miss a template placeholder.

I make extensive use of category and category description in my blog; I'd like for the first/primary category to be something that I could pick here.

In addition to an N-word excerpt, selecting the body text up to the More flag would be helpful.

Drawing on the RSS feed would be another interesting option.

Thanks!

**Comment by thomasjwebb** [comment]
I second wishing I could do up until the more break. As it stands right now, my blog is unusable on fediverse.
