### ISSUE TITLE
Customizable Meta-Fields for the Profile

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#170]
At the moment the profile page shows three times the same Link.

Mastodon shows three times the same link. 
<img width="305" alt="Bildschirm­foto 2022-11-09 um 08 22 50" src="https://user-images.githubusercontent.com/2017105/200767668-a35aa0db-8f06-4068-ac6c-1a7e3ebfbaab.png">

Can we have the possibility to define up to four Metaboxes with not only links but any UTF-8 content? Like Emojis, some written Texts, etc.

Thanks der considering :)

**Comment by wohfab** [comment]
I like that idea! Although, if setup in WordPress, the Blog goes to the blog page, the website to the homepage and the profile to the author page, I'd love to have a little more room to experiment with the fields.

Same would go for the displayed name and the profile image.

**Comment by nerdteacher** [comment]
Going to join in here. This was precisely what I was looking for. It'd be lovely to be able to include links to elsewhere, like accounts elsewhere on the Fediverse.

**Comment by pfefferle** [comment]
Keep!

**Comment by lapineige** [comment]
> Going to join in here. This was precisely what I was looking for. It'd be lovely to be able to include links to elsewhere, like accounts elsewhere on the Fediverse.

And maybe that "rel=me" link ?

**Comment by sindastra** [comment]
I think it would also be nice to be able to choose which of the default fields I want. For me, it just points to my blog three times (one being the author page). I'd like the ability to turn some of those off, in addition to defining my own. 🙂

**Comment by pfefferle** [comment]
I would close it for now in favor of: https://github.com/Automattic/wordpress-activitypub/pull/603
