### ISSUE TITLE
Migrate Followers from Mastodon

### ISSUE THREAD

**Issue by enzocomics** [Automattic/wordpress-activitypub#178]
I'd love to be able to migrate my followers from a Mastodon account, please.

I didn't see a prior issue posted, so I thought I would start one to see if others were interested in a feature like this. Thanks for your time!

**Comment by mediaformat** [comment]
Yes, this is on the roadmap: https://github.com/pfefferle/wordpress-activitypub/projects/10#card-56132357

**Comment by enzocomics** [comment]
Ah, I see. My apologies -- still getting familiar with how GitHub operates. That's wonderful to hear, thank you! I am looking forward to it.

**Comment by Atn-D** [comment]
message to prevent the issue from closing

**Comment by Atn-D** [comment]
message to prevent the issue from closing
