### ISSUE TITLE
Tags in Wordpress article don't show up as hashtags

### ISSUE THREAD

**Issue by bocops** [Automattic/wordpress-activitypub#182]
After installing the plugin, when writing an article on my Wordpress blog and adding tags to the article, no hashtags appear in the resulting post visible on Mastodon, not even as simple text.

Things I've already tried after consulting with Matthias directly:

1. two different blogs on separate URLs
2. viewing the resulting post with two different accounts on different Mastodon servers (one running v3.5.3, the other v4.0.2)
3. plugin setting: changing custom text - it doesn't matter where %hashtags% is inserted and in what order relative to other placeholders, or whether it is surrounded by an HTML p-tag or not.
4. plugin setting: toggling "Hashtags" option on or off
5. viewing post content by appending "/activitypub" to the blog URL - hashtags appear defined there, both as text with link to my blog in the content as well as in the "tag" list.
6. checking resulting Mastodon post using my browser's developer tools - there's simply nothing there

**Comment by bocops** [comment]
One thing I just noted is that the title, which is defined as `<p><strong>%title%</strong></p>` in the plugin, appears as `<p>Title</p>` in the resulting Mastodon post, with the `<strong>` tag missing.

It seems as if some sanitization or stripping of HTML tags is done before delivering these posts. Hashtags in `<a>` tags might simply be affected by that as well?

**Comment by mediaformat** [comment]
Mastodon has a very strict filter, and afaict strips out everything but `<br>` and `<a>`.

**Comment by pfefferle** [comment]
@mediaformat the `a` tag is allowed! I have checked that with several blog posts.

**Comment by dustinrue** [comment]
I think it would be great to just have post tags added as hashtags in the ActivityPub post. This keeps your page content clean while still using hashtags on the ActivityPub side.

**Comment by pfefferle** [comment]
You already can do that using the placeholders

**Comment by timnolte** [comment]
@bocops & @dustinrue if you go to the plugin settings you can control the output of the ActivityPub posts. Currently I'm using a Custom format as follows:
```
<p><strong>%title%</strong></p>

%excerpt%

<p>%hashtags%</p>

<p>%shortlink%</p>
```
My posts on Mastodon look like this:
![image](https://user-images.githubusercontent.com/4312062/204116657-554dea10-7ae6-47b0-b254-0e7961fe03f3.png)

**Comment by bocops** [comment]
@timnolte My custom format in Wordpress looks the same, but hashtags simply won't show up in the resulting post when viewed by different Mastodon users.

**Comment by dustinrue** [comment]
I didn't even think if custom formats, ty for the tip on that

**Comment by evilgeniuschronicles** [comment]
I am spending my Saturday night inserting logging code into the live plugin on my website. Hot times. 

Here is what happens when I write a post. I see it going through all the steps in generate_the_content a few times. I suspect each of those is a time when the autosave happens. Then it goes through when I publish, generates content with no tags in it and that's what gets published to Mastodon followers. Then after all that it gets called again, gets the tags and generates the content again **with the tags** but it has already sent the toots off. This is why it is not working. What I don't understand is what is making this timing happen. Hopefully y'all (in particular @pfefferle ) have a better grasp of it.

I went back and added logging at the top of get_the_post_hashtags. It is getting called each time, but all the times before send_post_activity() that returns nothing. After it gets called again that last time, after the actual activity is sent, the tags exist. 

```
[08-Jan-2023 02:23:15 UTC] Getting tags for 10265 
[08-Jan-2023 02:23:15 UTC] Getting tags for 10265 
[08-Jan-2023 02:23:15 UTC] Content: <p></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p>
[08-Jan-2023 02:23:15 UTC] Filtered Content: <p></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p>
[08-Jan-2023 02:23:15 UTC] Decoded Content: <p></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p>
[08-Jan-2023 02:23:15 UTC] <p></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p>
[08-Jan-2023 02:24:12 UTC] Getting tags for 10265 
[08-Jan-2023 02:24:12 UTC] Getting tags for 10265 
[08-Jan-2023 02:24:12 UTC] Content: <p></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p><p>I think I have narrowed this down to timing and things getting called prior to the tags being a
ssociated. Or something.</p>
[08-Jan-2023 02:24:12 UTC] Filtered Content: <p></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p><p>I think I have narrowed this down to timing and things getting called prior to the tag
s being associated. Or something.</p>
[08-Jan-2023 02:24:12 UTC] Decoded Content: <p></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p><p>I think I have narrowed this down to timing and things getting called prior to the tags
 being associated. Or something.</p>
[08-Jan-2023 02:24:12 UTC] <p></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p><p>I think I have narrowed this down to timing and things getting called prior to the tags being associated
. Or something.</p>

[08-Jan-2023 02:24:13 UTC] In send_post_activity: 2 {"@context":["https:\/\/www.w3.org\/ns\/activitystreams","https:\/\/w3id.org\/security\/v1",{"manuallyApprovesFollowers":"as:manuallyApprovesFollowers","PropertyValue":"schema:PropertyVal
ue","schema":"http:\/\/schema.org#","pt":"https:\/\/joinpeertube.org\/ns#","toot":"http:\/\/joinmastodon.org\/ns#","value":"schema:value","Hashtag":"as:Hashtag","featured":{"@id":"toot:featured","@type":"@id"},"featuredTags":{"@id":"toot:f
eaturedTags","@type":"@id"}}],"published":"2023-01-08T02:24:12Z","id":"https:\/\/evilgeniuschronicles.org\/2023\/01\/07\/activitypub-tag-test-9\/?activity=create","type":"Create","actor":"https:\/\/evilgeniuschronicles.org\/author\/dave-s\
/","to":["https:\/\/mastodon.lol\/users\/geniodiabolico"],"cc":["https:\/\/www.w3.org\/ns\/activitystreams#Public"],"object":{"id":"https:\/\/evilgeniuschronicles.org\/2023\/01\/07\/activitypub-tag-test-9\/","type":"Note","published":"2023
-01-08T02:24:12Z","attributedTo":"https:\/\/evilgeniuschronicles.org\/author\/dave-s\/","summary":null,"inReplyTo":null,"content":"\u003Cp\u003E\u003C\/p\u003E\u003Cp\u003E\u003Ca href=\u0022https:\/\/evilgeniuschronicles.org\/b\/2r5\u0022
\u003Ehttps:\/\/evilgeniuschronicles.org\/b\/2r5\u003C\/a\u003E\u003C\/p\u003E\u003Cp\u003EI think I have narrowed this down to timing and things getting called prior to the tags being associated. Or something.\u003C\/p\u003E","contentMap"
:{"en":"\u003Cp\u003E\u003C\/p\u003E\u003Cp\u003E\u003Ca href=\u0022https:\/\/evilgeniuschronicles.org\/b\/2r5\u0022\u003Ehttps:\/\/evilgeniuschronicles.org\/b\/2r5\u003C\/a\u003E\u003C\/p\u003E\u003Cp\u003EI think I have narrowed this dow
n to timing and things getting called prior to the tags being associated. Or something.\u003C\/p\u003E"},"to":["https:\/\/www.w3.org\/ns\/activitystreams#Public"],"cc":["https:\/\/www.w3.org\/ns\/activitystreams#Public"],"attachment":[],"t
ag":[]}}
[08-Jan-2023 02:24:14 UTC] In send_post_activity: 2 {"@context":["https:\/\/www.w3.org\/ns\/activitystreams","https:\/\/w3id.org\/security\/v1",{"manuallyApprovesFollowers":"as:manuallyApprovesFollowers","PropertyValue":"schema:PropertyVal
ue","schema":"http:\/\/schema.org#","pt":"https:\/\/joinpeertube.org\/ns#","toot":"http:\/\/joinmastodon.org\/ns#","value":"schema:value","Hashtag":"as:Hashtag","featured":{"@id":"toot:featured","@type":"@id"},"featuredTags":{"@id":"toot:f
eaturedTags","@type":"@id"}}],"published":"2023-01-08T02:24:12Z","id":"https:\/\/evilgeniuschronicles.org\/2023\/01\/07\/activitypub-tag-test-9\/?activity=create","type":"Create","actor":"https:\/\/evilgeniuschronicles.org\/author\/dave-s\
/","to":["https:\/\/masto.ai\/users\/mikewmerritt"],"cc":["https:\/\/www.w3.org\/ns\/activitystreams#Public"],"object":{"id":"https:\/\/evilgeniuschronicles.org\/2023\/01\/07\/activitypub-tag-test-9\/","type":"Note","published":"2023-01-08
T02:24:12Z","attributedTo":"https:\/\/evilgeniuschronicles.org\/author\/dave-s\/","summary":null,"inReplyTo":null,"content":"\u003Cp\u003E\u003C\/p\u003E\u003Cp\u003E\u003Ca href=\u0022https:\/\/evilgeniuschronicles.org\/b\/2r5\u0022\u003E
https:\/\/evilgeniuschronicles.org\/b\/2r5\u003C\/a\u003E\u003C\/p\u003E\u003Cp\u003EI think I have narrowed this down to timing and things getting called prior to the tags being associated. Or something.\u003C\/p\u003E","contentMap":{"en"
:"\u003Cp\u003E\u003C\/p\u003E\u003Cp\u003E\u003Ca href=\u0022https:\/\/evilgeniuschronicles.org\/b\/2r5\u0022\u003Ehttps:\/\/evilgeniuschronicles.org\/b\/2r5\u003C\/a\u003E\u003C\/p\u003E\u003Cp\u003EI think I have narrowed this down to t
iming and things getting called prior to the tags being associated. Or something.\u003C\/p\u003E"},"to":["https:\/\/www.w3.org\/ns\/activitystreams#Public"],"cc":["https:\/\/www.w3.org\/ns\/activitystreams#Public"],"attachment":[],"tag":[]
}}
[08-Jan-2023 02:24:15 UTC] Getting tags for 10265 Array
(
    [0] => WP_Term Object
        (
            [term_id] => 2702
            [name] => activitypub
            [slug] => activitypub
            [term_group] => 0
            [term_taxonomy_id] => 2700
            [taxonomy] => post_tag
            [description] => 
            [parent] => 0
            [count] => 12
            [filter] => raw
        )

    [1] => WP_Term Object
        (
            [term_id] => 2706
            [name] => debug
            [slug] => debug
            [term_group] => 0
            [term_taxonomy_id] => 2704
            [taxonomy] => post_tag
            [description] => 
            [parent] => 0
            [count] => 8
            [filter] => raw
        )

    [2] => WP_Term Object
        (
            [term_id] => 2700
            [name] => mastodon
            [slug] => mastodon
            [term_group] => 0
            [term_taxonomy_id] => 2698
            [taxonomy] => post_tag
            [description] => 
            [parent] => 0
            [count] => 13
            [filter] => raw
        )

)

[08-Jan-2023 02:24:15 UTC] Getting tags for 10265 Array
(
    [0] => WP_Term Object
        (
            [term_id] => 2702
            [name] => activitypub
            [slug] => activitypub
            [term_group] => 0
            [term_taxonomy_id] => 2700
            [taxonomy] => post_tag
            [description] => 
            [parent] => 0
            [count] => 12
            [filter] => raw
        )

    [1] => WP_Term Object
        (
            [term_id] => 2706
            [name] => debug
            [slug] => debug
            [term_group] => 0
            [term_taxonomy_id] => 2704
            [taxonomy] => post_tag
            [description] => 
            [parent] => 0
            [count] => 8
            [filter] => raw
        )

    [2] => WP_Term Object
        (
            [term_id] => 2700
            [name] => mastodon
            [slug] => mastodon
            [term_group] => 0
            [term_taxonomy_id] => 2698
            [taxonomy] => post_tag
            [description] => 
            [parent] => 0
            [count] => 13
            [filter] => raw
        )

)

[08-Jan-2023 02:24:15 UTC] Content: <p><a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/activitypub/">#activitypub</a> <a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/debug/">#debug</a> <a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/mastodon/">#mastodon</a></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p><p>I think I have narrowed this down to timing and things getting called prior to the tags being associated. Or something.</p>
[08-Jan-2023 02:24:15 UTC] Filtered Content: <p><a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/activitypub/">#activitypub</a> <a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/debug/">#debug</a> <a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/mastodon/">#mastodon</a></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p><p>I think I have narrowed this down to timing and things getting called prior to the tags being associated. Or something.</p>
[08-Jan-2023 02:24:15 UTC] Decoded Content: <p><a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/activitypub/">#activitypub</a> <a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/debug/">#debug</a> <a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/mastodon/">#mastodon</a></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p><p>I think I have narrowed this down to timing and things getting called prior to the tags being associated. Or something.</p>
[08-Jan-2023 02:24:15 UTC] <p><a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/activitypub/">#activitypub</a> <a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/debug/">#debug</a> <a rel="tag" class="u-tag u-category" href="https://evilgeniuschronicles.org/tag/mastodon/">#mastodon</a></p><p><a href="https://evilgeniuschronicles.org/b/2r5">https://evilgeniuschronicles.org/b/2r5</a></p><p>I think I have narrowed this down to timing and things getting called prior to the tags being associated. Or something.</p>
[08-Jan-2023 02:24:19 UTC] []

```

**Comment by bocops** [comment]
I've talked to @evilgeniuschronicles the last few days and can confirm his findings.

For what it's worth, if I edit `get_the_post_hashtags()` in `class-post.php` to return some arbitrary string in case of not finding any post tags, like so:

```php
if ( ! $tags ) {
    return 'This text should never appear for posts with tags!';
}
```

Then this string will appear in **all** resulting Mastodon statuses, even if the post **did** have tags. This means that the abovementioned placeholder replacement works, but that WP's `get_the_tags($id)` doesn't, at least not at that point and for some of us.

**Comment by bocops** [comment]
FWIW, @evilgeniuschronicles found a workaround and shared it with me that might help users encountering the same issue, and might also help track down why this bug exists in the first place:

If the Wordpress post isn't posted immediately, but instead **scheduled** (even just some minutes in the future is enough), then the resulting AcitivityPub post as viewed for example via Mastodon will contain the post tags as hashtags, as long as the template is set up correctly.

This, combined with the fact that this bug did not appear for all of us in the first place, seems to suggest that timing issues might be the cause, perhaps via the use of `wp_schedule_single_event(...)` for some of the internal scheduling this plugin does?

**Comment by pfefferle** [comment]
@bocops nice debugging! that helps a lot, I will have a look why the tags might not be included if the post is sent to quickly.

**Comment by pfefferle** [comment]
I have one last question: How do you generate the tags? Are these the tags that are added via the classic tags frontend of the editor or the hashtag feature ActivityPub implements?

**Comment by evilgeniuschronicles** [comment]
In my case, it was the tag editor in the front end. Even when adding tags first before writing the post, I got the empty get_the_tags() behavior during publish.

**Comment by bocops** [comment]
Same here, I added "tags" in the Wordpress editor for them to be added to the resulting ActivityPub object via `%hashtags%`.

Adding hashtags to the content directly still seems to have other issues. At least Mastodon doesn't seem to recognize them, and instead displays simple text. Not sure if this is a related issue or something else at the moment.

**Comment by pfefferle** [comment]
Is this still an issue with version 0.16.1?

**Comment by bocops** [comment]
@pfefferle Just tested this once, but looks good to me! As far as I am concerned, this can be closed unless others still see the problem. Thanks for the fix! :)

**Comment by evilgeniuschronicles** [comment]
I tested on my blog with 0.16.1 . I still see the problem.

The wordpress posts have odd permalinks, but I did comment to Matthais' mastodon account in a reply to my test post. I set up the tags in the right-hand column of the post section prior to publishing. I did the immediate "Publish" and did not get the tags in the post when it arrived in Mastodon.

**Comment by pfefferle** [comment]
What do you mean by "the permalinks are weird"? You seem to use shortlinks, if you want to have the permalinks, you have to change your settings.

**Comment by pfefferle** [comment]
@evilgeniuschronicles can you send me your message config?

**Comment by evilgeniuschronicles** [comment]
![image](https://user-images.githubusercontent.com/1059864/217645836-f06d6c3d-d8ea-4bd5-b3b9-01699531514f.png)

**Comment by evilgeniuschronicles** [comment]
@

> What do you mean by "the permalinks are weird"? You seem to use shortlinks, if you want to have the permalinks, you have to change your settings.

I mean the permalink to the actual Mastodon post that results is weird. If there is a trick for finding the link in the Mastodon context I don't know it. The permalink points back to Wordpress.

**Comment by pfefferle** [comment]
This is how the permalink should work! It should point to the WordPress post.

**Comment by evilgeniuschronicles** [comment]
That's fine. It just makes it difficult to point out to you how this problem gets realized, since it shows up in the Fediverse in a way that cannot be pointed to directly.

**Comment by evilgeniuschronicles** [comment]
Scheduled vs Immediate publish

![image](https://user-images.githubusercontent.com/1059864/217649158-ad748a8b-029d-4420-ac52-2904385783c4.png)

**Comment by pfefferle** [comment]
Because of the changing link? `/b/2xd` and `/b/2xc`?

**Comment by pfefferle** [comment]
Sorry, but I still see no problem.

**Comment by pfefferle** [comment]
It looks like it should look like.

**Comment by evilgeniuschronicles** [comment]
Top post, the one that was scheduled has hashtags in it. The bottom one, published by hitting the "Publish" button,  does not.

**Comment by pfefferle** [comment]
Ah, we are talking about the hashtags! I was confused because you always talked about the permalink!

**Comment by evilgeniuschronicles** [comment]
I only talked about the permalink because it makes it hard to show you the hashtag problem. AFAIK screenshotting is the only option because I can't otherwise show you how it shows up in Mastodon.

**Comment by evilgeniuschronicles** [comment]
@pfefferle If you want to follow from your Mastodon account @dave@evilgeniuschronicles.org that will cut out a middleman and you'll see my tests directly.

I know this issue is me complaining but I do appreciate your efforts. This is not a super-high priority to me since there is a trivial workaround but I can see this confusing new installers.

**Comment by pfefferle** [comment]
Should finally work with 1.0.x
