### ISSUE TITLE
Request to Disable Serving ActivityPub JSON by User Agent

### ISSUE THREAD

**Issue by dshanske** [Automattic/wordpress-activitypub#223]
As there is not an easy fix for #78 and it seems unlikely there would be, requesting optional special casing based on user agent.

https://github.com/aaronpk/XRay/blob/main/controllers/Parse.php#L16

Essentially, in this function, return early if you detect XRay in the User-Agent.

https://github.com/pfefferle/wordpress-activitypub/blob/master/includes/class-activitypub.php#L36

I know technically speaking, @aaronpk 's code is asking for the ActivityPub version, but one side has to special case it.

Or give me an easy way to filter at this point?

**Comment by dshanske** [comment]
Here's my suggested code: https://gist.github.com/dshanske/e2659241f1c8c064441737afbd89654c

**Comment by pfefferle** [comment]
I do not think it is that easy! @aaronpk has added it, because it seems to be a nice fallback if no other semantic is available and we can not get sure, that Microformats are available only because of someone installed the Webmention plugin.

**Comment by pfefferle** [comment]
If we could deactivate that by default, than I would vote for doing it on the XRay side!

**Comment by pfefferle** [comment]
fixed by @aaronpk https://github.com/aaronpk/XRay/issues/101
