### ISSUE TITLE
Feature Request: Fediverse Address Block

### ISSUE THREAD

**Issue by beckej13820** [Automattic/wordpress-activitypub#236]
Recently, I updated my "Author" template in my WordPress theme to look more like a social media site.

I don't know how familiar the developers of this plugin are with the "Full Site Editing" experience in WordPress, but with existing blocks, it was fairly easy to create a design that feels familiar to Mastodon using the "Avatar," "Author," "Author Biography," and a custom Query Loop for the posts.

<img width="1331" alt="Screenshot 2023-01-01 at 9 12 15 PM" src="https://user-images.githubusercontent.com/29982981/210190979-421ab169-1edd-4fde-81cf-16ef4387c0df.png">

The only piece of the author template that there wasn't an existing block for was something to display the fediverse address of the author. Being able to pull and display @username@site.url for an author in a context aware way that could be reused on page, post, author, and archive templates could be a nice feature on WordPress sites that are fediverse enabled, signaling to others that it is possible to follow from activitypub enabled sites. 

Currently, I have that information hardcoded into the template, but I manage a multi-author site, and with the growing interest in activitypub enabled sites, it might be interesting to connect multiple accounts from a single website, in which case a block that could be placed into templates would become even more useful.

**Comment by pfefferle** [comment]
Keep

**Comment by pfefferle** [comment]
There is now a "Follow me" block!
