### ISSUE TITLE
Chinese-character tags are not converted into hashtag properly

### ISSUE THREAD

**Issue by mattholy** [Automattic/wordpress-activitypub#239]
It looks like the `%hashtags%`  will url-encode tags in the Wordpress articles.

For example:
I had a tag `#参考文献` in my article, but when pushed to Mastodon I got `#%e5%8f%82%e8%80%83%e6%96%87%e7%8c%ae`

![image](https://user-images.githubusercontent.com/22177897/210252692-904c8578-328c-45ea-b061-dfd2052e2a8a.png)

**Comment by timnolte** [comment]
This should be kept and classified as internationalization.
