### ISSUE TITLE
Hashtags and remote delete

### ISSUE THREAD

**Issue by Sampozzo** [Automattic/wordpress-activitypub#253]
Hello, 
in the latest release 0.15 i've seen "Fix remote-delete"... what this mean? because i tryed deleting a post but it is not removed on mastodon. What i'm missing? 

Another question, i set te post-content to custom with hashtags, but they are not shown.

Last: I have a multidomain installation, how can i set the defaults for every blog?

Thank you very much!

**Comment by bocops** [comment]
The hashtag issue is already discussed in #182.

**Comment by pfefferle** [comment]
Hmm, I think that Mastodon might have changed something, so I have to really check this!

Regarding the "delete" issue: Have you moved the post to the trash or have you deleted it completely? To delete the post in the fediverse, it has to sit in the trash for a bit (because the communication is asynchronous and it might last some minutes, to really send the delete request). Maybe I should document it somewhere.

**Comment by pfefferle** [comment]
@Sampozzo I had not tested really the plugin in a multi-domain env, due to (spare) time shortage, so I do not really have an answer for that. I might get some more time working on the plugin by the beginning of April but no guarantee yet!

**Comment by Krafting** [comment]
Hello, 
Wouldn't it be better if we had a GUI to delete any post on Mastodon?
I mean, there is a lot of test stuff now on my page that I can't delete now, ahah
 Maybe I am missing something ? Maybe there is a CLI tool to delete posts ? is there any documentation for that ?

Thank you, and keep up the good work!

**Comment by pfefferle** [comment]
@Krafting if you delete a post it should be deleted in the fediverse, at least it worked in my tests. It is important to keep the posts in the trash for some time!

There is no possibility to have a different UI for deleting things, because there is no other persistence then the post itself! If the post is already deleted, WordPress does not know about the federated version of the post any more.

**Comment by pfefferle** [comment]
I am working on a feature to completely delete the profile from the fediverse if possible.

**Comment by Krafting** [comment]
> @Krafting if you delete a post it should be deleted in the fediverse, at least it worked in my tests. It is important to keep the posts in the trash for some time!
> 
> There is no possibility to have a different UI for deleting things, because there is no other persistence then the post itself! If the post is already deleted, WordPress does not know about the federated version of the post any more.

Oh, okay, I think I get it, it shows old non deleted post because the Mastodon instance I'm on, cached them. But from other instance they might not be there as they were never loaded, is this correct ?

**Comment by pfefferle** [comment]
It depends, the plugin had a bug, that was fixed in 0.15.0, so posts before that version might not be deleted correctly. 😔

**Comment by Krafting** [comment]
> It depends, the plugin had a bug, that was fixed in 0.15.0, so posts before that version might not be deleted correctly.

I tried accessing my account from another instance and deleted posts weren't present! I guess the bug didn't occur with me. 

Also, is it possible to change the profile picture to something custom ? Wordpress wants me to use gravatar but meh.. is there any plugin that we can use to change the profile picture that would also replicate on the fediverse side ?

**Comment by Sampozzo** [comment]
I @pfefferle thanks for the reply! I don't remember for sure, but the post was not in the trash, will test again. Thanks again. But the hashtags doesn't seems to work.

**Comment by Sampozzo** [comment]
@pfefferle yes it works like you said 😊

**Comment by Sampozzo** [comment]
@pfefferle now the hashtags are working too.

About the multi-domain env, if you will a have a look at it, here are some suggestion:

1) ability to set default post-content for every subdomain
2) ability to disabile the plugin on single subdomain (can't understand if it is possible now)

**Comment by pfefferle** [comment]
should work with 1.0.x, please re-open if still an issue
