### ISSUE TITLE
Add a pattern tag/variable

### ISSUE THREAD

**Issue by adegans** [Automattic/wordpress-activitypub#257]
Hello,

For multiuser blogs can you add a %username% variable to the template for posts shared.

I now use:
```
<p><strong>%title%</strong></p>
<p>%excerpt%</p>
<p>Full Article: %permalink%
Search for <strong>@arnandegans@ajdg.solutions</strong> on your instance or app and click follow.</p>
<p>%hashtags%</p>
```

But that only works because I'm the only user.
On my other site, where there are 2 users... Not so practical. 😉

Perhaps something to consider -  Thanks!

**Comment by beckej13820** [comment]
Similar request to #236 

People who are getting into sharing their blog posts on the fediverse want to be able to signal in their themes and templates that this is a activitypub enabled blog.

**Comment by pfefferle** [comment]
@adegans but to see the post, you have to follow the blogs user, so you already know the identifier. And if you see the post in someone else's timeline, you can simply see who has published the post and follow your blog anyways?!?

**Comment by beckej13820** [comment]
@pfefferle I see your point if the user has found you through a tool like mastodon, but I when I read this, I thought he was more talking about a use case where someone has stumbled on your blog/website, and giving visual indications that it is possible to follow on mastodon.

![Screenshot 2023-01-18 at 8 48 21 AM](https://user-images.githubusercontent.com/29982981/213188864-032c0336-59a5-4236-91b8-5abb56eb4135.png)

**Comment by pfefferle** [comment]
But the template constants are only used for the posts sent to the fediverse!

**Comment by pfefferle** [comment]
@beckej13820 I agree that your usecase makes sense (also a remote follow dialogue maybe) but this is a separate issue I think.
