### ISSUE TITLE
Control Which Posts are Published and Documentation

### ISSUE THREAD

**Issue by tmichellemoore** [Automattic/wordpress-activitypub#264]
Hello @pfefferle,
Is there any way to have the plugin not publish a post?
Also, do you have documentation that goes into a little more detail on the plugin like explaining the delete capabilities, the what gets posted, etc? I think I have seen some answers in the issues and some int he FAQs, but can’t find more details.
Thank you for what looks like a huge effort on this plugin!
Michelle

**Comment by pfefferle** [comment]
@tmichellemoore there is currently no possibility to decide what to post and what not, but it was requested quite often, so I think we have to add it 😊

I agree with the documentation part... can you be a bit more concrete what exactly would help you?

**Comment by tmichellemoore** [comment]
Hi @pfefferle, Thank you for that answer. Regarding documentation. If I was starting from day one, the topics that would have helped me and still will, are below. I am going on information you have provided or that I have seen in the answers and on things I still want to know.
**Setup**
- What is nodeinfo plugin for relative to the ActivityPub plugin?
- Can you explain a little more about what Nodeinfo does?
- Can you update any additional settings in Nodeinfo in the backend?
- How can you change the Mastodon profile settings?
- What is the Webfinger plugin for relative to the ActivityPub plugin?
**Friends/Followers/Following**
- What will the Friends plugin do?
- Does it add users to my WordPress install? Yes
- Will this let me see my Mastodon followers? No
- Will this increase my Mastodon following count or are these separate friends? No, they are Separate.
- Can I see my followers in WordPress?
**Create and Publish**
- What gets posted? Everything that you have setup in the plugin settings, if the plugin is active.
- How can I not post things? Deactivate the plugin before posting.
- What part of a post gets published?
- If the WordPress except is included in the post, Will the plugin use that?
- What do each of the what gets published settings mean?
- What will checking the hashtag setting do?
- Does it matter if the post has been validated in Indywebify.me or any other microformat validator? No
- How can I include some formatting in my post on Mastodon?
**Update** 
- How can I update a post on Mastodon? Mastodon might not support.
**Delete**
- How can I delete a post on Mastodon? Delete in WordPress.
- If deleting in WordPress does not delete on Mastodon, how do I delete on Mastodon? 
**Other**
- Can this work with Brid.gy in some way?
- How do likes and comments get transmitted to WordPress?
- What is the best way to reply to someone that has replied to your post on Mastodon?

I have more from answers you have provided but have to look them up. I will edit this post and let you know when I am done.

**Comment by tmichellemoore** [comment]
@pfefferle Above would be my questions about ActivityPub. If you provided answers before, I pasted them in there.

**Comment by jeckman** [comment]
Other (maybe belongs on the Friends plugin?)

When I'm reading a users' updates in my own Friends page, how can I comment on their post?

Or, if I find an update by a user on an external Mastodon server, can I reply to it? Can I boost it? If so, how?

**Comment by Cambridgeport90** [comment]
Leave it be.

**Comment by pfefferle** [comment]
Keep!

**Comment by pfefferle** [comment]
Keep!
