### ISSUE TITLE
Different templates for different post types

### ISSUE THREAD

**Issue by shaunrobinson** [Automattic/wordpress-activitypub#270]
Feature request: Could you add the option to use different Post Content templates for each post type?

**Comment by janboddez** [comment]
Similar to #348, maybe a filter can be a first step?

It's probably not very practical to let users set a template per post type (some sites may have a dozen or more).

But filtering the outcome of `get_post_content_template()` might be enough (for developers, at least, and then they could share code snippets that others could reuse, and so on).

**Comment by pfefferle** [comment]
keep
