### ISSUE TITLE
Mentions issue - how is it supported?

### ISSUE THREAD

**Issue by beergeekdotcom** [Automattic/wordpress-activitypub#273]
I have setup a group on a.gup.pe and mention that group in the default template of the activitypub plugin.

is @username@server the correct format or perhaps mentions are not supported in the default template? I did use the Friends plugin to follow the group accounts per that method.

example toots: https://beerweek.lol/author/sfbeerevents/

**Comment by pfefferle** [comment]
It is as you said: `@username@domain.tld`

There is currently no UI for that, that means you will not see any word/name completion (yet), like with the friends pluging.

**Comment by beergeekdotcom** [comment]
I did a couple more tests and it appears that mentions may not be supported in the Post-Content custom template, but are supported in the content of a post?  Here's the template I'm using:
![Screen Shot 2023-02-07 at 11 42 46 AM](https://user-images.githubusercontent.com/17600155/217349027-a863319e-b154-455b-bb7b-f1b18b8bbcea.png)

**Comment by pfefferle** [comment]
Yes, that is how it works.

I have never thought about the template, is this really a case? Do you want to mention these two in every post?

**Comment by beergeekdotcom** [comment]
In this case, yes. Pretty limited functionality in that site. I’m sure others will eventually come up with more compelling reasons to want to do similar. 

In addition, would be great if default tags could be added to the template as well. For the same reasons.

**Comment by seindal** [comment]
I would like to second the need for mentions and tags in the post template.

Like the OP I have a thematic group I'd like to mention, and a couple of tags that characterise everything I post on my site.

**Comment by seindal** [comment]
I would still like to see this fixed.

**Comment by seindal** [comment]
@beergeekdotcom The problem of automatically mentioning Fediverse profiles in all posts can be solved by a plugin, using one of the hooks available in the ActivityPub plugin.

I have made such a plugin which you can find here:
https://plugins.seindal.dk/plugins/activitypub-auto-mention/

How to automatically add some fixed tags to all posts still eludes me. I just add the tags in WordPress on every post.
