### ISSUE TITLE
One WP post didn't get distributed via ActivityPub

### ISSUE THREAD

**Issue by craigconstantine** [Automattic/wordpress-activitypub#274]
My most recent post on https://moversmindset.com hasn't been sent out via ActivityPub. If you look at `@craig@moversmindset.com` aka https://moversmindset.com/author/craig  you'll see the most recent post is from Dec 2022.

But there is a public post from Feb 8…

<img width="1098" alt="Screenshot 2023-02-09 at 07 58 51" src="https://user-images.githubusercontent.com/2278992/217820030-b1de6cb5-5c49-45ac-a8ac-e344d8e0b0d1.png">

I notice that ActivityPub can display the post if I directly ask, https://moversmindset.com/preview-still-mind-with-martin-svenselius/activitypub

**Extra oddities:**

This is the first time I've tried to use "(preview) " at the front of post title. So… parenthesis are one place for suspicion

But also, I just posted a bug report for the `display-posts` WP plugin, https://wordpress.org/support/topic/behavior-different-anonymous-visitor-versus-me-logged-in/  Because this same post _also_ doesn't get shown to anonymous visitors to the site. So _perhaps_ there's something deeper in WP's queries that is preventing both ActivityPub and DisplayPosts plugins from getting this post in queries. Here's a screenshot of **the Display Posts** bug I reported over there…

<img width="1320" alt="Screenshot 2023-02-09 at 07 53 04" src="https://user-images.githubusercontent.com/2278992/217820651-15008deb-0f77-4be6-9c75-ee5bb1f73f56.png">

**Comment by jeckman** [comment]
FWIW, I do see the post on the home page of https://moversmindset.com/ - but not in the page https://moversmindset.com/episodes/

Caching, perhaps? Most caching plugins ignore logged in users - if I add a nonsense query string ( https://moversmindset.com/episodes/?junk ) I do see it on that page

**Comment by craigconstantine** [comment]
Caching is a great point! I'd forgotten about that. That may be all that's wrong with the other WP plugin... nothing's wrong, the page is cached.

But my question here… "Why didn't this newest post go out via ActivityPub to subscribers?" remains…

**Comment by jeckman** [comment]
I do see the post from 2/8  at https://moversmindset.com/author/craig/ - had not checked there before. Perhaps authors page is also being cached?

**Comment by craigconstantine** [comment]
…okay, I've disable page caching :)

…and I still don't see the newest (feb 8) post when I look at craig@moversmindset.com from a mastodon client.

…and my original callout: Why didn't AP plugin notify/push/publish/whatever the Feb 8 post to my Mastodon account. (I'm following @craig@moversmindset.com from a generic mastodon account to keep an eye on things.)

**Comment by pfefferle** [comment]
I can see the post on mastodon, maybe a glitch? have you deleted the post at some time in the process?

![Bildschirmfoto 2023-05-23 um 12 16 19](https://github.com/Automattic/wordpress-activitypub/assets/2373/6e06820a-4b6b-4643-b893-59c422057412)

I will close this for now, feel free to re-open if still a problem.
