### ISSUE TITLE
Dropdowns to choose "preferredUsername" and "name" from list

### ISSUE THREAD

**Issue by stevenjaycohen** [Automattic/wordpress-activitypub#277]
It may make sense to use a more formal Full Name when a post goes out into the Fediverse as opposed to a more familiar firstname or nickname while on one's own website.

I am suggesting adopting the UI from the current User Profile page and allowing users to choose which of the names they would like on their Fediverse Profiles and accompanying their posts.

**Comment by pfefferle** [comment]
I just had a look at the code. I use "display_name" for the name attribute (that should be the value of the drop-down) and the login-name as "preferredUsername". My understanding is, that the "name" should be used to display!

```PHP
$json->name = \get_the_author_meta( 'display_name', $author_id );
$json->preferredUsername = \get_the_author_meta( 'login', $author_id ); // phpcs:ignore
```

**Comment by stevenjaycohen** [comment]
![Screenshot from 2023-02-16 06-09-33](https://user-images.githubusercontent.com/23110485/219348657-695a20da-8fdf-4c95-bbbb-4cb10e47e6b4.png)
Internally, on my site, it makes sense to be Steven. Externally, I would suggest, using my whole name makes sense. The issue here is that I make the decision in the User Profile based upon what I want to be called on my site. Since the plugin transmits that information outward globally, I'd love those same profile dropdowns to appear in the plugin settings, so I could make a different choice based upon the difference in scope.

Does that make sense?

**Comment by pfefferle** [comment]
I understand your point, but I do not want to have too many settings and want to stick with WordPress core settings/features as much as possible.

Will think about it 😊

**Comment by pfefferle** [comment]
If you want a quick fix, you should be able to change it via filter.

**Comment by timtomch** [comment]
Jumping in to first thank you for developing a fantastic plugin and entertaining enhancement requests by your users.

The user name thing has been bothering me as well, in a related manner to #259. For single-user blogs (there probably are many out there), the Wordpress username doesn't necessarily make a lot of sense as a public handle. I wonder if having the ability to set the name manually on the plugin preferences may be a way to resolve this particular issue?

**Comment by Profpatsch** [comment]
I’m not entirely sure what decides the display name (my best guess is `Customizer → General Settings → Website Name`), but we have this problem:

![image](https://github.com/Automattic/wordpress-activitypub/assets/3153638/3390e1c9-2112-48a2-b7a4-76a12df05289)

Our blog is at https://www.openlab-augsburg.de/blog/

It’s annoying, cause we have a „real“ account and one for the blog now, and both have the same display name, yet I don’t want to necessarily change the name of our homepage to distinguish. So a way of customizing this in the plugin would be welcome.

**Comment by Profpatsch** [comment]
Other than that, fantastic plugin, we were able to set it up with a few clicks and everything just works!
