### ISSUE TITLE
BLOG link in Profile does not follow WP > General > Reading > Posts Page

### ISSUE THREAD

**Issue by stevenjaycohen** [Automattic/wordpress-activitypub#288]
![Screenshot from 2023-03-07 03-02-01](https://user-images.githubusercontent.com/23110485/223360115-8018e8cb-7ab8-4630-a4bd-83852b8953f5.png)
That URL is stevenjaycohen.com/journal/

![Screenshot from 2023-03-07 03-03-26](https://user-images.githubusercontent.com/23110485/223360369-119a4ba7-5dda-42d3-822f-214a49f442c4.png)
The profile URL is for the Static Front Page (which is correct for the WEBSITE link but incorrect for the BLOG link).

**EXPECTED BEHAVIOR**
Since the profile has separate links for the Website and the Blog, the Blog Link should follow WordPress's Posts Page setting.

**Comment by janboddez** [comment]
Was wondering if these values could somehow be modified (or even deleted, may not make a lot of sense to have three links to the same site/page) and stumbled upon the `activitypub_json_author_array` filter.

https://github.com/Automattic/wordpress-activitypub/blob/c809dc2cb5556d23a5109a7cce0659ff4c5094a1/templates/author-json.php#L81

Think that means you could do something like (untested, but it's a start):
```
add_filters( 'activitypub_json_author_array', function( $json, $author_id ) {
  $json->attachment['blog_url']['value'] = str_replace(
    home_url( '/' ),
    esc_url( get_permalink( get_option( 'page_for_posts' ) ) ), // This should be `https://stevenjaycohen.com/journal/`.
    $json->attachment['blog_url']['value']
  );
 
  return $json;
} );
unset($a->new_property);
```

**Comment by pfefferle** [comment]
I would love to have a UI for that, so that you will be able to add links and maybe text.

BTW. it is not always the "same" link, it just looks similar in the preview.

In the first step, I add them using a filter, so you could simply remove the hook and add your own: https://github.com/Automattic/wordpress-activitypub/pull/342/files#diff-6cc5f17bb46bd2c49daff4cedaad22399048ee7fa7dd97b3ee2dcfad390fe6d7R36

**Comment by janboddez** [comment]
In Mastodon, there are up to 4 fields (or 2 times 4, because the labels can also be chosen) that you can fill out as you please. Would make sense to have something similar (on the settings or user profile page, for instance).

But hooks are enough for me :-)

**Comment by janboddez** [comment]
Looks like the filter hook `activitypub_json_author_array` is no longer in use either?
