### ISSUE TITLE
subdomain network support 

### ISSUE THREAD

**Issue by shleeable** [Automattic/wordpress-activitypub#289]
I'm planning on hosting a subdomain network for multitenant... because the fediverse is about people. I'm hoping I can make it easy for people to register `https://bobtrust.thefediverse.au` as a WP blog, and have this plugin support `@bobtrust@thefedivese.au` to follow on Mastodon.

I haven't setup https://wordpress.org/documentation/article/create-a-network/  yet, but I'm hoping this will work as expected.

**Comment by shleeable** [comment]
`@bobtrust@bobtrust.thefedivese.au` is fine.. but I'd love to drop that sub from the fediverse username

**Comment by shleeable** [comment]
Tested searching for my networked user.

`@FediPressAUAdmin@fedipress.au` works
`@shlee@shlee.fedipress.au` fails

**Comment by pfefferle** [comment]
puh, that is not that easy! I will think about that!

**Comment by jaschaurbach** [comment]
To at least find you at with `@bobtrust@thefedivese.au`

Have a 302 redirect for
`https://thefedivese.au/.well-known/webfinger?resource=acct:bobtrust@thefediverse.au`
to 
`https://bobtrust.thefedivese.au/.well-known/webfinger?resource=acct:bobtrust@bobtrust.thefediverse.au
`

I do the same for `@jascha@jascha.wtf` which redirects to `@herrurbach@toot.jascha.wtf` (My WordPress-AP user is `@tomate@jascha.wtf` - this will not be redirected by this)
