### ISSUE TITLE
Different settings for posts and pages?

### ISSUE THREAD

**Issue by YuriGal** [Automattic/wordpress-activitypub#300]
Would there be a possibility to have separate settings for post and pages? E.g. for posts I'd like to publish excerpt, but pages don't have one, so I need to publish full content.

**Comment by pfefferle** [comment]
@YuriGal the plugin auto-generates an excerpt for posts if you use that setting.

**Comment by pfefferle** [comment]
I would avoid different settings for the moment, because it adds lot's of complexity and there are still a lot of loose ends. But that does not mean that it will never be possible.

**Comment by pfefferle** [comment]
besides of that, it is a duplicate to #270
