### ISSUE TITLE
Is there someone who got this working on wordpress.com hosted instances

### ISSUE THREAD

**Issue by anantshri** [Automattic/wordpress-activitypub#301]
Seems like the caching is too aggressive on wordpress.com and it doesn't respect the accept headers. I have been trying to get this to work properly and so far have failed miserably.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/236843/230852569-f65dadc3-6572-40a8-b5a5-d70c8db67126.png">

url : https://blog.anantshri.info
user: anantshri

plugin installed : webmentions, indieweb plugin, activitypub, webfinger, nodeinfo 

@anantshri@blog.anantshri.info is suppose to be the fediverse id. seems like webfinger is working https://webfinger.net/lookup/?resource=anantshri%40blog.anantshri.info

Any help or pointer appreciated.

Problems
1. Site health says not a valid json response on author profile (I think what i showed above could be reason for that)
2. Even if i am able to see my id on other servers if i click follow i dont see followers nor i see a approval request.
3. My fediverse tool of choice is gotosocial and it errors out with a message
```
error enriching account from remote: enrichAccount: error dereferencing account https://blog.anantshri.info/author/anantshri/: ResolveAccountable: error unmarshalling bytes into json: unexpected end of JSON input
```
which could be due to caching, but i am clueless on how to handle it. hence raising a request here to get a pointer as to what could be wrong.

**Comment by jeherve** [comment]
> Seems like the caching is too aggressive on wordpress.com and it doesn't respect the accept headers.

That's indeed something that should be fixed in the caching solution used on WordPress.com. The problem is currently tracked here:
https://github.com/Automattic/batcache/issues/104

**Comment by anantshri** [comment]
this working as expected so far. 

![image](https://github.com/Automattic/wordpress-activitypub/assets/236843/c8ed3e64-fe3f-480a-ac05-5a50b21f48a1)


That's gotosocial, calckey, mastodon, bookwrym and kbin in that order. all appearing clearly as followers. 

Thanks folks. Can confirm its working.
