### ISSUE TITLE
URL to post not clickable

### ISSUE THREAD

**Issue by PMCTechSupport** [Automattic/wordpress-activitypub#313]
Hi, 

I have mostly got this working really well, but one thing is still bugging me. The URL whether it's [ap_permalink] or [ap_shortlink] (with hum installed) is not clickable from within the post on mastodon. 

I have tried various mastodon clients and all show the same behavior. 

Is this a known bug or is there something on the server side of mastodon I need to look at?

**Comment by pfefferle** [comment]
You have to use `[ap_shortlink type="html"]`, same for `[ap_permalink type="html"]`. You can find the full list of short-codes in the help section of the settings (top-right corner).

**Comment by PMCTechSupport** [comment]
Sorry should have included, I have tried type HTML and type URL and neither worked.

**Comment by pfefferle** [comment]
can you share an URL to a post, then I can check!

**Comment by pfefferle** [comment]
@PMCTechSupport any update on that?
