### ISSUE TITLE
Display error when posted to mastodon

### ISSUE THREAD

**Issue by brianhurley** [Automattic/wordpress-activitypub#330]
The post-content configuration is as below.
![image](https://github.com/Automattic/wordpress-activitypub/assets/2214481/4299b42d-aa73-4a9e-b968-99e2c9c41b20)

I am not sure if this is a mastodon related or the post-content related. The images below show that the thumbnail displayed is taken from the first link in the contents and not from the post link at the end.

![image](https://github.com/Automattic/wordpress-activitypub/assets/2214481/824c947a-90c3-4258-969a-b3ad733ce582)

![image](https://github.com/Automattic/wordpress-activitypub/assets/2214481/9d9960ae-672d-4bc2-a808-21bfc03a01a2)

**Comment by pfefferle** [comment]
This link preview is generated by mastodon, and mastodon seems to use the first link in a text for that.

**Comment by brianhurley** [comment]
Thanks for your quick response - I appreciate it!
