### ISSUE TITLE
userid incorrect

### ISSUE THREAD

**Issue by brianhurley** [Automattic/wordpress-activitypub#331]
When I initially installed the plug-in, my userid was brianrhurley. I subsequently uninstalled the plug-in, and changed my userid to be newspaceeconomy. The plug-in still shows my user ID to be brianrhurley. Wordpress.com shows that the userid  was changed to be newspaceeconomy. Screenshots are attached. Is there a way to reset the userid that the plug-in is using from the initial installation?

![image](https://github.com/Automattic/wordpress-activitypub/assets/2214481/75cfec8e-0b5d-41ae-86bf-c7902f5cc4a3)
![image](https://github.com/Automattic/wordpress-activitypub/assets/2214481/28be890d-da26-4ea2-b806-3469d1212122)
![image](https://github.com/Automattic/wordpress-activitypub/assets/2214481/2e957bdd-a152-4da1-9430-fb25ca91f497)

**Comment by pfefferle** [comment]
You seemed to change the author slug (you see that the author URL changed) but for the other id (username@domain.tld) the plugin uses the login and nicht the author slug.

**Comment by pfefferle** [comment]
But Account-Settings seem to show it as the Username... hmmm... I have to check this if I find the time!

**Comment by brianhurley** [comment]
Once again, thank you very much for your quick response!

I will wait for your follow up. In the meantime I'll keep working with it. I think this is a great plug-in, I like the way it extends the content across other networks.

**Comment by anantshri** [comment]
I am also stuck in the same situation right now. I have raised a support ticket with wp team.

some digging around curtsey business account confirmed my suspicion that the user id picked by this plugin is the user_login created at blog level. we login using wp.com login but that id and local id are two different things whatever is the local id will be used for activitypub plugin as far as current design is concerned.

**Comment by janboddez** [comment]
I think it's simply to do with "usernames can't ever change," no? So the one thing you can't change is `user_login` (or the author archive URL, which acts as the AP profile page and is derived from it).

Unless there is a way they can? Can't the plugin announce username changes as a "Move" activity, for instance, similarly to how you can move Mastodon accounts (but not change/reclaim a username [without also change servers])?
