### ISSUE TITLE
web finger 404 - 'activitypub_wrong_host'

### ISSUE THREAD

**Issue by drewwestcott** [Automattic/wordpress-activitypub#334]
I've been trying to get webFinger and ActivityPub working on my site with the help of my host. They have changed a few of the bot settings which seem to let webFinger work. However, if I use https://webfinger.net/lookup/?resource=%40drew%40drewwestcott.co.uk I get 404 error.

Trying to view the https://drewwestcott.co.uk/.well-known/webfinger?resource=acct%3A%40drew%40drewwestcott.co.uk via a GET returns 

`{"code":"activitypub_wrong_host","message":"Resource host does not match blog host","data":{"status":404}}`

My site url and blog address are set to https://drewwestcott.co.uk and my primary domain in the hosting is also drewwestcott.co.uk

What's the next step I should take to try and find out what is causing the error?

Thanks

**Comment by pfefferle** [comment]
WebFinger does not support the `@` before a username, that is a construct from the fediverse (mainly mastodon) to simulate the @-replies on Twitter. To check your WebFinger-Endpoint, simply use: `drew@drewwestcott.co.uk` => https://drewwestcott.co.uk/.well-known/webfinger?resource=acct%3Adrew%40drewwestcott.co.uk

To find your profile on Mastodon, you can still use `@drew@drewwestcott.co.uk`. I agree that this might be a bit confusing :)

**Comment by drewwestcott** [comment]
Thanks, hadn't realised I needed to search without the @ symbol on WebFinger. As they say, you learn something new everyday.
