### ISSUE TITLE
Sub-directory hosting instructions break certbot webroot certification challenge

### ISSUE THREAD

**Issue by sjlongland** [Automattic/wordpress-activitypub#339]
https://github.com/Automattic/wordpress-activitypub#what-if-you-are-running-your-blog-in-a-subdirectory

The example code given here breaks `certbot` when executing the web root challenge, as `.well-known/acme-challenge` gets wrongly redirected to the blog instead of left alone.

Looking through the source code, it would seem this is more correct:

```
RedirectMatch "^\/\.well-known/(webfinger|nodeinfo|x-nodeinfo2)(.*)$" "\/blog\/\.well-known$1"
```

**Comment by pfefferle** [comment]
Thanks a lot, I will update the FAQs.

**Comment by pfefferle** [comment]
No problem, I fix it! Thanks again.
