### ISSUE TITLE
Request to follow account “pending” indefinitely on mastodon

### ISSUE THREAD

**Issue by Kyleidoscope** [Automattic/wordpress-activitypub#341]
I’m able to search for and find my Wordpress blog address on mastodon but when I click follow the request is stuck as “pending” Indefinitely. Any suggestions or fixes is can try?

![7D561B00-F97F-41FE-BE8A-C9AF846305C7](https://github.com/Automattic/wordpress-activitypub/assets/6465689/3041021f-997c-4b0a-b399-4f6de8734a09)

**Comment by timnolte** [comment]
Who's your hosting provider? Usually this is a sign that ModSecurity is blocking the request. If that is the case you'll have to reach out to your hosting provider to have them unblock the requests.

**Comment by timnolte** [comment]
Quick search, as I didn't create my own blog post about it when I fixed my issue, and here is some guidance. https://blog.rac.me.uk/2022/11/10/activitypub-for-wordpress-how-to-fix-modsecurity-to-make-it-work/

**Comment by Kyleidoscope** [comment]
@timnolte thanks for the quick reply. I’m with hostgator. 

I’ll have a look at that post and failing that I’ll contact Hostgator for support. Cheers

**Comment by Kyleidoscope** [comment]
@timnolte I got Hostgator via support to fix the issue with modsec based on that article. Thanks

**Comment by Kyleidoscope** [comment]
Issues was with hostgator and they were able to fix the permissions
