### ISSUE TITLE
Updates not always federating?

### ISSUE THREAD

**Issue by janboddez** [Automattic/wordpress-activitypub#343]
Found https://github.com/Automattic/wordpress-activitypub/issues/16 but after some experimenting, I found that for example https://mastodon.vlaanderen/@jan@build.boddez.net/110424976082747799 is still there, whereas the original https://build.boddez.net/articles/last-one/ was deleted (or moved back to draft, or first moved back to draft and then deleted, I'll check again).

So, it seems that either "unpublish" (i.e., "back to draft") doesn't federate, or deletes are broken?

Perhaps the "unpublish" case is simply not covered yet? (But, then, why doesn't `'trash' === $new_status` do its thing when it finally is deleted?)
```
if ( 'publish' === $new_status && 'publish' !== $old_status ) {
	...
} elseif ( 'publish' === $new_status ) {
	...
} elseif ( 'trash' === $new_status ) {
	...
}
```

I'd dig deeper, but wanted to first check no one's already working on this.

**Comment by pfefferle** [comment]
Have you deleted it instantly or kept in trash for a while? The federation of Activities happens async, so it might need the trashed post to stay in trash for some minutes.

**Comment by janboddez** [comment]
Ome or two days ago. Could also be it's because I was messing with URLs, by the way,  I'll try to reproduce later or on a production site

**Comment by mediaformat** [comment]
This, activities are federating with the post their url as `id`, so if the slug was at all changed, it would need to be changed back to the original url it federated with

**Comment by janboddez** [comment]
Oh, it seems to redirect to the deleted page now. Could be browser cache or something,  my other machine would still show it this morning.

**Comment by janboddez** [comment]
Hehe, now deletes work but updates don’t. Wondering if it could be Gutenberg.

**Comment by janboddez** [comment]
Deletes work as long as the URL is the same, but I can't seem to get updates to work. Or undelete(s), i.e., restoring a previously trashed item and then again publishing it doesn't seem to do anything.

**Comment by pfefferle** [comment]
Update is not working properly. The only thing I can think of, is a missing updated property. Re undelete/restore: I have no idea if this is implemented anywhere. Haven't seen any spec yet. @janboddez do you have a reference?

**Comment by janboddez** [comment]
Not immediately, I was thinking of Mastodon's delete and rewrite or whatever it's called.

So the only way to "undelete" a post and have it federate is to create a new one (with a different URL)? (Which is an acceptable workaround.)

**Comment by pfefferle** [comment]
That is at least what I thought so far. But let me know if you find something different!

**Comment by janboddez** [comment]
Is an `updated` property (same format, I assume, as `published`) the only thing that's still missing that prevents remote servers (Mastodon, at least) from processing updates?

If so, would there be any harm in always including such a property? And, if there is, how do we then "decide" when to add it?

Should we keep track, in a custom field or so, whether a post has been federated previously? Do we simply compare published and last updated timestamp and always add `updated` if they're different? What if an update was previously sent? What if the post was updated but it's contents nor attributes didn't actually change? (Should we store a "post content hash" somewhere?)

Sorry for the many questions; the spec seems super vague on this, and I've tried to look into other AP software's source code, but can't readily find the answers ...

**Comment by pfefferle** [comment]
As far as I experienced, it does not harm to always add the updated.

**Comment by pfefferle** [comment]
Mastodon seems to handle `Update` requests without the updated attribute, like a create.

**Comment by janboddez** [comment]
> Mastodon seems to handle `Update` requests without the updated attribute, like a create.

Really? They don't seem to work for me :-(

**Comment by pfefferle** [comment]
If you edit an old post, that is not yet on mastodon, then it is technically an `Update` Activity but it shows up on Mastodon after the `Update`, so Mastodon seem to handle `Updates` without the `updated` timestamp as an `Create`.

**Comment by janboddez** [comment]
> Mastodon seem to handle Updates without the updated timestamp as an Create.

Ah, clear.
