### ISSUE TITLE
Feature Request: Set default Actor for blog

### ISSUE THREAD

**Issue by DeadSuperHero** [Automattic/wordpress-activitypub#346]
Hey there!

Big fan of this plugin and all the work that's gone into it. I'm in the process of bringing back an old publication (https://wedistribute.org), but there is one tiny headache: when federating posts to the rest of the fediverse, those posts are attributed to the author's actor. This is fine for personal blogs, but kind of makes things more complicated for those of us who wish to use the blog itself as an actor instead.

Example: Let's say I want to use `news@wedistribute.org` or something like that. If I create a user with the name `news` and post only from that account, it'll work. But, myself and other contributors would like to use our own accounts, with our own names for attribution.

It would be really great if the Wordpress plugin could push out posts through a singular Actor, rather than use Actors associated with authors. This would make it much easier for people to follow the entire blog, if they wanted to.

**Comment by pfefferle** [comment]
Hey Sean, nice to hear that you bring back wedistribute.org 😍

I am working on exactly that feature: https://github.com/Automattic/wordpress-activitypub/pull/342

It already supports all the profiling and following stuff, open tasks are publishing and settings.

**Comment by DeadSuperHero** [comment]
That's wonderful news! I'm looking at launching in a week or two (have to manually recreate many old posts to build up the archive), but I'd really love to have this feature first, to bring back federated comments. :)
