### ISSUE TITLE
Remote instance not reflecting profile changes

### ISSUE THREAD

**Issue by janboddez** [Automattic/wordpress-activitypub#350]
Stupid question perhaps, but how do profile updates "federate"?

I.e., if I change my user (nick)name and open my profile on a Mastodon instance, the change is not immediately reflected.

Does Mastodon just cache these for a while? Or should WordPress actively "push" actor updates to followers' instances? Maybe I should just be patient. :-D

**Comment by pfefferle** [comment]
Mastodon is caching the informations for quite some time. I have not yet found a way to send an activity to force an update. Please let me know I you find something.

**Comment by janboddez** [comment]
Clear! At least I know I'm not doing anything wrong, then :-)

**Comment by mediaformat** [comment]
From what I read in the docs mastodon will check/update the senders profile after it receives a new post. No idea if it's still true.

**Comment by pfefferle** [comment]
The best (and most ActivityPub like) solution would be to send an `Update` Activity with the Actor as Object. But I would assume no software support that so far.

**Comment by mediaformat** [comment]
I think Friendica and Streams supports this.

**Comment by mediaformat** [comment]
I think Friendica and Streams supports this.

**Comment by janboddez** [comment]
> From what I read in the docs mastodon will check/update the senders profile after it receives a new post. No idea if it's still true.

Just tested, still works!

Alright, I'm going to say what we have now is good enough (for me). Couldn't readily find the info above; perhaps someone else finds it useful, too, who knows. :-)
