### ISSUE TITLE
About the Method of Obtaining Private Posts on Mastodon

### ISSUE THREAD

**Issue by 1719753389** [Automattic/wordpress-activitypub#352]
tried to post a post @xxx@example.com on Mastodon, but I didn’t see this post on my website. What’s the reason? How should I achieve such a function? Make a private post that only my site can access

**Comment by mediaformat** [comment]
This isn't supported yet. 
The plugin (inbox) only supports replies to WP posts, as comments.

**Comment by rasos** [comment]
Yes it would be great to also be able  to subscribe to an ActivityPub feed and show its content as a channel. That way we could embed a Mastodon feed as a Wordpress channel. Currently this is only possible with the plugin `Include Mastodon Feed`.
