### ISSUE TITLE
Extra whitespace on Mastodon

### ISSUE THREAD

**Issue by janboddez** [Automattic/wordpress-activitypub#357]
I had an issue where Mastodon would show extra whitespace that I think is due to the block editor and/or the use of `wpautop()`.

The block editor already adds paragraphs, and it also adds a bunch of newlines that I think `wpautop()` then converts to  `p` or `br` elements and are thus _not_ stripped by `preg_replace( '/[\n\r\t]/', '', $content )`.

What seems to work is:
- a filter where I don't call `wpautop()` (okay for me, I'm using the block editor for all post types that I want to federate)
- call `wpautop( $content, false )` instead, so with the second parameter set to false

Second option seems the better one? Or is there a reason to not do this?

**Comment by janboddez** [comment]
(Also, isn't `wpautop` one of the filters in `apply_filters( 'the_content', $post->post_content )` already?)

**Comment by pfefferle** [comment]
It depends: https://github.com/Automattic/wordpress-activitypub/blob/master/includes/class-shortcodes.php#L201 (This is because a lot of plugins add a lot of %&$§ to the content, so it is up to the user if he wants that /%&§?§$ to be federated or only his content).

I added it once again, because you could add extra content to the ActivityPub content field, like the hashtags, links, ...

As far as I know it wpautop does take care of alreade <p>ed content?!?

**Comment by janboddez** [comment]
I don't seem to be suffering from this anymore; also can't really remember what exactly may have lead to this. But I'm also completely overwriting "ActivityPub" posts' contents in an add-on plugin. :-)

**Comment by janboddez** [comment]
I just noticed this again. https://indieweb.social/@starrwulfe@starrwulfe.xyz/111671414664906704 is a Mastodon copy of the post over at https://starrwulfe.xyz/notes/2023/12/ad18663ee2/. And while Mastodon's web UI shows it just fine, Tusky on Android adds a bunch of newlines that shouldn't be there.

Now, this may be a Tusky issue, but it can be prevented by stripping whitespace in between HTML tags. If I load the indieweb.social URL above and look for the JSON coming from the server, it kinda looks like this:

```
  <p><i>In reply to <a class="u-url" href="https://jan.boddez.net/notes/9a5f268a52" rel="nofollow noopener noreferrer" target="_blank">https://jan.boddez.net/notes/9a5f268a52</a> by <span class="p-author">Jan</span>.</i></p>  <p><a rel="nofollow noopener noreferrer" class="u-url mention" href="https://jan.boddez.net/author/jan" target="_blank">@<span>jan</span></a> <a rel="nofollow noopener noreferrer" class="u-url mention" href="https://indieweb.social/@janboddez" target="_blank">@<span>janboddez</span></a> so hang on a sec; how do I do this on my own WP blog here? What do I “aim” the <code>activitypub_in_reply_to</code> field at to get the “inline federated reply” trick to work? </p><p><em>(side note; how do I put the shortlink next to the date as the permalinks like how you’ve done?)</em></p> <p><a href="https://starrwulfe.xyz/notes/2023/12/ad18663ee2/" rel="nofollow noopener noreferrer" target="_blank">https://starrwulfe.xyz/notes/2023/12/ad18663ee2/</a></p>
```

There's a literal space at the start, and then spaces between the closing `</p>` tag and the opening tag that follows it, and so on.

The reason I don't suffer from it on my site is because I have a custom `activitypub_the_content` filter in place.

**Comment by janboddez** [comment]
Oh, wait. I just checked out my custom filter and it literally only does the following (I only use it so I can use a "template" that's different from what's defined in the settings):
```
$content  = apply_filters( 'the_content', $post->post_content );
$content .= '<p><a href="' . esc_html( get_permalink( $post ) ) . '">' . esc_html( get_permalink( $post ) ) . '</a></p>';
$content = wp_kses( $content, $allowed_tags );
$content = preg_replace( '~[\n\r\t]~', '', $content );
$content = trim( $content );
```

It shouldn't do anything that isn't already done by the AP plugin:
https://github.com/Automattic/wordpress-activitypub/blob/245cda8433b8319856cf3a656f5bd975ee383cfc/includes/transformer/class-post.php#L601-L605

Maybe @starwulffe is using a custom filter too? That somehow adds these spaces?
