### ISSUE TITLE
Conditionally apply ap_title template tag

### ISSUE THREAD

**Issue by mediaformat** [Automattic/wordpress-activitypub#358]
Posting an [indieblocks_note](https://github.com/janboddez/indieblocks), without a title, adds `(No title)` to the AP post content.

This is because I'm using the AP Template Tags, and had set it up for Posts.

```
<p><strong>[ap_title]</strong></p>

[ap_content]

<p>[ap_hashtags]</p>
```

**Comment by janboddez** [comment]
Here's what I've been doing (as a sort of test, at least): https://gist.github.com/janboddez/58a2f3d2c86717cd799048af651fa6b4#file-activitypub-php-L87L94

Basically, I filter (completely overwrite) the default "AP post content" based on the post's type.

**Comment by pfefferle** [comment]
Yes, messed up the issue ID 😣
