### ISSUE TITLE
Can't seem to get the template to change the activitypub post - UTF8 not supported?

### ISSUE THREAD

**Issue by seefood** [Automattic/wordpress-activitypub#380]
https://tooot.im/@admin@ira.abramov.org/110792328169894160
I have added in the title, hashtags, content excerpts but all I get is the link.
My blog content, title and hashtags are all in Hebrew, but that should not really effect the outcome, so I am guessing it is a bug?

![image](https://github.com/Automattic/wordpress-activitypub/assets/409600/7194cf2f-23d7-4afc-aecc-b11e5c5853bf)

![image](https://github.com/Automattic/wordpress-activitypub/assets/409600/84a920b3-202c-47ef-b3d2-009b651d2c57)

**Comment by pfefferle** [comment]
It does! https://ira.abramov.org/blog/2023/07/28/hitting-back-as-a-strategy/activitypub/

Hmmm...

**Comment by seefood** [comment]
That JSON doesn't have keys for the title nor the categories, btw. I wonder if it's something to do with my setup afterall. It's a WP installation that goes back maybe 15-17 years, always upgraded in place, but still the scheme is supposed to always be updated. could it be a bad collation of the mysql in the backend?

**Comment by seefood** [comment]
Ahhh, ok, I see what you meant. the "content" key does have all the links, but Mastodon is ignoring the HTML. Should it just be a bunch of plaintext? I mean I don't need the hashtags to link back to my blog, I want them to become fediverse hashtags. Basically I expected the content to be plaintext and a URL, no HTML code, am I getting it right?

**Comment by pfefferle** [comment]
Mastodon does support HTML https://docs.joinmastodon.org/spec/activitypub/#sanitization

I have to add some HTML, because Mastodon does not auto-link URLs and I am not sure if Mastodon is very good with auto breaks.

**Comment by juengling** [comment]
I suppose it's not only the hebrew language. My blog is totally in German, but I also have no chance to change the template. My template is similar to @seefood's, but the [result in Mastodon](https://www.juengling-edv.de/cicd-ohne-build/) is simply "link + picture".

**Comment by pfefferle** [comment]
Have you set the radio button to "custom"?

**Comment by juengling** [comment]
Yes (German "Individuell"):

![grafik](https://github.com/Automattic/wordpress-activitypub/assets/12947277/52f6c7d0-dcd9-43ef-baa5-2dc7574312ac)

**Comment by pfefferle** [comment]
Can you share an example URL?

**Comment by pfefferle** [comment]
Ah, I just saw that you have chosen "WordPress Beitragsformat" in the next setting. Mastodon only shows the link when Activity-Object-Type is "Article" (see description of "Article"). You should use the default there (Note).

**Comment by pfefferle** [comment]
Might be also the solution for @seefood

**Comment by juengling** [comment]
I'll try that with the next article, thanks.

**Comment by juengling** [comment]
This combination works fine, thank you!

![grafik](https://github.com/Automattic/wordpress-activitypub/assets/12947277/86174d1a-8a36-4a1c-82fd-81dad8a6dd14)

**Comment by pfefferle** [comment]
You have to use type=html

**Comment by juengling** [comment]
> You have to use type=html

Damn, it's always the last I try :-)

**Comment by pfefferle** [comment]
I just had a look @seefood has exactly the same issue! Changing the activity-object-type to note will solve the issue!

**Comment by pfefferle** [comment]
I will close it for now, please re-open if still an issue!

**Comment by seefood** [comment]
there isn't a type=html, you mean Note?

**Comment by pfefferle** [comment]
Yes, if you set the Activity-Object-type to "Note" then it should work.
