### ISSUE TITLE
Feature Request: Admin can see followers by user

### ISSUE THREAD

**Issue by ambanmba** [Automattic/wordpress-activitypub#393]
Would be nice to see which users have which followers, basically /wp-admin/users.php?page=activitypub-followers-list only seems to show the followers of the logged in admin user and not the other users on the site.

**Comment by pfefferle** [comment]
you can check their follower endpoints!?!

**Comment by ambanmba** [comment]
@pfefferle are you referring to https://domain.com/author/username/ ? It's not showing there (I assume there needs to be some code on that page to display things from the plugin?)

Alternatively if I view the profile from a Mastodon instance, I can see the total number of followers but also get "Followers from other servers are not displayed." and I am offered to "[Browse more on the original profile](https://domain.com/author/username/)" which doesn't show it per above.

**Comment by pfefferle** [comment]
I mean this site: https://notiz.blog/wp-api/activitypub/1.0/users/1/followers?page=1

**Comment by ambanmba** [comment]
Going to /wp-api/activitypub/1.0/users/1/followers?page=1 on my site is a 404.
I'm running Wordpress Version 6.3, ActivityPub 0.17.0, PHP 8.2.1

**Comment by pfefferle** [comment]
Oh sorry, I use a custom API prefix. Should be `/wp-json/activitypub/1.0/users/1/followers?page=1` on your side. change the user-id to see the followers of the other blog users.

**Comment by ambanmba** [comment]
Thanks @pfefferle , that works. I still think it would be nice to have it via the admin panel, but this certainly does the trick.

**Comment by pfefferle** [comment]
btw. if you add `&context=full` you get the full profile of the follower

**Comment by ambanmba** [comment]
That didn't work... ""No route was found matching the URL and request method.""

`/wp-json/activitypub/1.0/users/2/followers&context=full`

**Comment by pfefferle** [comment]
`/wp-json/activitypub/1.0/users/1/followers?page=1&context=full`
