### ISSUE TITLE
Lemmy compatibility

### ISSUE THREAD

**Issue by alexture** [Automattic/wordpress-activitypub#394]
I love this extension for Mastodon - and I feel like it would be even better for Lemmy.

In my mind, you'd have 2 main features:

- Tag a Lemmy community / post in a blog article to create a post/comment wherever appropriate
- Pull Lemmy comments on Lemmy link posts that link to my blog article

I'm not sure how feasible either of these is, but it would be so great! Please tell me if it would be more appropriate for the Webmentions and/or Syndication Links plugins :)

I don't know if this helps, because computers are not my thing, but I found this on the Bridgy repository: https://github.com/snarfed/bridgy-fed/issues/372

**Comment by pfefferle** [comment]
This is already working pretty nice: https://lemmy.ml/c/notiz.blog@notiz.blog
