### ISSUE TITLE
Does not work together with hCaptcha

### ISSUE THREAD

**Issue by sindastra** [Automattic/wordpress-activitypub#402]
Using the official hCaptcha WordPress plugin and enabling the "comment form" integration, will block any comments from ActivityPub to be posted on the blog.

Workaround: Disable the hCaptcha comment form integration and install/enable/use "Antispam Bee" instead.

During my testing, Antispam Bee did allow comments from ActivityPub, while successfully blocking spam. So it seems to be a reasonable replacement/workaround for hCaptcha.

I opened an issue with hCaptcha, too: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/issues/265

**Comment by pfefferle** [comment]
I am not sure I can do anything here?!?

**Comment by sindastra** [comment]
When I originally opened this issue (v0.17.0), my hope was that you could add something to make it easier for third-party plugin developers to integrate with ActivityPub. But since I opened the issue, 1.0.0 was released, where you did add `\Activitypub\is_activitypub_request()`, which I think might just be what was needed?

If I understood correctly, hCaptcha could now use that new method to handle ActivityPub requests differently (let them through), which would make this issue obsolete.

So, I guess all you can do now is confirm that this new method would be just what was needed, and then close the issue and leave it to hCaptcha to implement it. (:

**Comment by pfefferle** [comment]
Exactly! This method was introduced by @jeherve to check if a request is an ActivityPub request.

**Comment by sindastra** [comment]
OK, in that case, I will close this issue for now! If I hear anything from hCaptcha where more might be required, I'll reopen it! (:
