### ISSUE TITLE
Testing Blog Profile

### ISSUE THREAD

**Issue by netm** [Automattic/wordpress-activitypub#413]
Some feedback on the Blog Profile feature:

1. I installed 1.0 current
2. My user is visible here https://staging.1964.co.nz/@gwilym
3. I set the Blog Profile to '1964' expecting https://staging.1964.co.nz/@1964 to work as the Blog Wide user
4. I get a 404 "**activitypub_user_not_found**" 
5. I created a Wordpress user for '1964' just in case a User is required (not obvious to me if needed or not)

:-) Happy to do more testing if needed

Gwilym

**Comment by pfefferle** [comment]
It is not needed to have a user with the same name and I haven't tested if it might collide if both have the same name. So please deinstall the user with the same name to be sure.

Can you try to re-build the rewrite rules? You can do that if you go to the permalinks page and hit "save". You do not have to change anything.

**Comment by netm** [comment]
So ... I tried rebuilding Permalinks but no luck. I then changed the user from '1964' to 'team' and it seems to be working :-) Is it possible it didn't like the integer?

**Comment by pfefferle** [comment]
shouldn't be a problem. Maybe because the user and the blog had the same name.

**Comment by pfefferle** [comment]
I will close it for now.
