### ISSUE TITLE
Honor primary_blog user metadata

### ISSUE THREAD

**Issue by aaribaud** [Automattic/wordpress-activitypub#414]
Hello,

I manage a multisite install where some sites are user personal sites, and have their primary_blog user metadata set accordingly.

However, in their profile as seen from a Mastodon instance, the "BLOG" information points to the main site (whereas their "INTERNET SITE" info points at their primary blog.

I think the right option (or at least, a selectable option) should be that BLOG point to the primary blog (and maybe INTERNET SITE be not provided then.

**Comment by aaribaud** [comment]
Answering myself: issue is not in this activitypub plugin but in https://github.com/pfefferle/wordpress-webfinger

**Comment by pfefferle** [comment]
No, you are totally right here. This meta-data is provided by the ActivityPub plugin and not by WebFinger.

These meta-fields will be editable in the near future!

**Comment by aaribaud** [comment]
Great! I'm volunteering for beta-testing :smile: and, if that's useful, to help developing.

Mord details about my issue:

Assuming the following:
* a multisite (subdirectories) Wordpress install at `example.invalid`
* three sites/blogs (the Wordpress terminology seems fluid):
  * the default site at https://example.invalid/`
  * a site `heads` at https://example.invalid/heads/`
  * a site `tails` at https://example.invalid/tails/`
  * a network-declared user `alice` who is only registered at `heads` which is her default site
 Then :
* https://example.invalid/tails/.well-known/webfinger?resource=acct:alice@example.invalid will fail (understandably, as `alice` does not have an account on `tails`)
* https://example.invalid/heads/.well-known/webfinger?resource=acct:alice@example.invalid will succeed (and consistently return URIs pointing to `example.invalid/heads/...`)
* https://example.invalid/.well-known/webfinger?resource=acct:alice@example.invalid -- which is the standard ActivityPub URI for `@alice@example.invalid` -- will fail (but should, as I understand it, return the information for `alice`'s default site/blog -- or, maybe, information on all sites/blogs on which `alice` has an account? Not sure)

If the fields become editable for all blogs then probably all the above should resolve itself quite smoothly!
