### ISSUE TITLE
Image added to post doesn't appear as AP attachment unless uploaded directly

### ISSUE THREAD

**Issue by bocops** [Automattic/wordpress-activitypub#417]
When creating an image post, I'm doing the following in Wordpress:
1. "Posts", "Add new"
2. Select "Image" from list of available post formats
3. Select "Image" as the content of the first block
4. Either upload a new image, or select an existing image from the media gallery
5. Add other blocks, add tags and/or categories (none of this seems to matter)

Expected outcome:
* the AP output for this post (viewed by appending "/activitypub" to the post URL) should contain an image attachment
* the post as viewed e.g. on Mastodon should show an image
* the image should have the alt text that was entered in Wordpress

Actual outcome:
* if the image was uploaded in step 4, it will become an AP attachment and be visible on Mastodon. It will not have an alt text (this is issue #94)
* if the image was selected from the media gallery as a workaround for issue 94, it will not show up in resulting Mastodon posts
* when viewing the AP output, it contains `"attachment":[]`

I can create a temporary example on my blog if this is not reproducible elsewhere. Just let me know.

**Comment by pfefferle** [comment]
This is now fixed if using the block editor #460
