### ISSUE TITLE
.htaccess instructions not working?

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#419]
I've added the following to the `.htaccess` file in the root of my website `shkspr.mobi`

`RedirectMatch "^\/\.well-known/(webfinger|nodeinfo|x-nodeinfo2)(.*)$" "\/blog\/\.well-known$1$2"`

If I visit https://shkspr.mobi/.well-known/webfinger I get redirected to `https://blog///.well-knownwebfinger`

The complete listing of the `.htaccess` file is:

```
RewriteOptions inherit
RewriteEngine on
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]
Header always set Content-Security-Policy "upgrade-insecure-requests;"

# https://wordpress.org/plugins/activitypub/
RedirectMatch "^\/\.well-known/(webfinger|nodeinfo|x-nodeinfo2)(.*)$" "\/blog\/\.well-known$1$2"
```

**Comment by edent** [comment]
If I change the rewrite rule to 

`RedirectMatch "^\/\.well-known/(webfinger|nodeinfo|x-nodeinfo2)(.*)$" /blog/.well-known/$1$2"`

then it works as expected.

**Comment by jarbochov** [comment]
This worked for me as well, thanks for the tip @edent
