### ISSUE TITLE
[ap_title] not showing on Mastodon

### ISSUE THREAD

**Issue by tonydiep** [Automattic/wordpress-activitypub#420]
First of all thanks for making image previews show up on Mastodon version 1.0

FYI: Titles are not showing up.

```
<p><strong>[ap_title]</strong></p>
<div>
[ap_image]
</div>
<p>[ap_permalink]</p>
```

results in no title shown on Mastodon

![Screenshot from 2023-09-13 07-16-30](https://github.com/Automattic/wordpress-activitypub/assets/705269/26deefff-b33d-44cf-a34e-8e9e0bb5be48)

(If I have to choose I'd rather have the image than the title.)

**Comment by pfefferle** [comment]
Do you use "Note" as Activity-Type?

**Comment by tonydiep** [comment]
I just switched it back to 'Note" and the title now shows up. I had it set on 'Wordpress'. 

Thank you so much for this plugin!
![Screenshot from 2023-09-13 07-34-58](https://github.com/Automattic/wordpress-activitypub/assets/705269/7ffe1fee-0ee0-4f25-969c-760758fa4229)

**Comment by pfefferle** [comment]
I added a warning to the settings in 1.0.0. Mastodon only really support "Note" an reduces everything else to a simple link.
