### ISSUE TITLE
Follower requests never complete - ModSecurity off

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#421]
I've successfully set up `@blog@shkspr.mobi` - it appears on the Fediverse. But people can't follow it.

ModSecurity is set to "off" in my cPanel. As per #341 and https://blog.rac.me.uk/2022/11/10/activitypub-for-wordpress-how-to-fix-modsecurity-to-make-it-work/#adding-the-new-mod-security-rule that should fix it. But it doesn't.

![Screenshot showing ModSecurity off.](https://github.com/Automattic/wordpress-activitypub/assets/837136/12f37f48-f3f8-4e68-a838-a0d0b276f716)

Are there any tests I can run to see what the problem is?

Site Health shows:
>  Author URL is not accessible ActivityPub
> Your author URL https://shkspr.mobi/blog/author/admin/ does not return valid JSON for application/activity+json. Please check if your hosting supports alternate Accept headers.

However, I am not using `admin` as the author; I've disabled the author in the settings and have a generic blog profile ID.

**Comment by pfefferle** [comment]
Yes, it seems to return only HTML!

You can check it with

```
## Request (23)
curl "https://shkspr.mobi/blog/author/admin/" \
     -H 'Accept: application/activity+json'
```

Have you enabled caching? Maybe the cache does not support content negotiation?

**Comment by edent** [comment]
Interesting. If I do `curl "https://shkspr.mobi/blog/@qwerty"` I get

`{"code":"activitypub_user_not_found","message":"User not found","data":{"status":404}}`

But if I do `curl "https://shkspr.mobi/blog/@blog"` (which is the username) I get a 301 redirect to my blog's front page.

I had this as the setup:
![Screenshot 2023-09-13 at 14-15-48 Welcome ‹ Terence Eden’s Blog — WordPress](https://github.com/Automattic/wordpress-activitypub/assets/837136/2167c0a5-8e5b-42a1-9024-fa813eff4cd2)
![Screenshot 2023-09-13 at 14-15-41 Welcome ‹ Terence Eden’s Blog — WordPress](https://github.com/Automattic/wordpress-activitypub/assets/837136/2afe3e51-c346-4653-8b9d-5c5467b84118)

I've excluded `/author/` from the cache. And re-enabled the author profile type. But follow requests still aren't processed.

**Comment by pfefferle** [comment]
yes, it redirects if you do not add the `application/activity+json` Accept header. It is the blog user so you see all its posts on the main page :)

Have you also excluded the API and the @-urls? Because the blog-user has no author URL, it is a simple rewrite rule to an API endpoint.

**Comment by edent** [comment]
OK, I think I've done all that - but I still can't accept followers.

`@admin@shkspr.mobi` appears on Mastodon.social and I can see the last few blog posts.

`@blog@shkspr.mobi` appears on Mastodon.social but there are no posts.

Following either of them doesn't work.

I've excluded the following URls from cacheing.

```
/.well-known/*
/wp-json/*
/author/*
/@blog
```

Are there any others which should be excluded?

**Comment by pfefferle** [comment]
shouldn't it be `/blog/...`?

**Comment by edent** [comment]
I've disabled caching for tonight.

**Comment by jarbochov** [comment]
Okay, I'm a novice, but I can find my user account for my blog. The JSON for the account is listing:

`{"@context":["https:\/\/www.w3.org\/ns\/activitystreams","https:\/\/w3id.org\/security\/v1",{"manuallyApprovesFollowers":"as:manuallyApprovesFollowers","PropertyValue":"schema:PropertyValue","schema":"http:\/\/schema.org#","pt":"https:\/\/joinpeertube.org\/ns#","toot":"http:\/\/joinmastodon.org\/ns#","webfinger":"https:\/\/webfinger.net\/#","litepub":"http:\/\/litepub.social\/ns#","value":"schema:value","Hashtag":"as:Hashtag","featured":{"@id":"toot:featured","@type":"@id"},"featuredTags":{"@id":"toot:featuredTags","@type":"@id"},"alsoKnownAs":{"@id":"as:alsoKnownAs","@type":"@id"},"discoverable":"toot:discoverable","sensitive":"as:sensitive","resource":"webfinger:resource"}],"id":"https:\/\/wyomingjarbo.com\/blog\/wp-json\/activitypub\/1.0\/users\/0\/inbox","generator":"http:\/\/wordpress.org\/?v=6.3.1","type":"OrderedCollectionPage","partOf":"https:\/\/wyomingjarbo.com\/blog\/wp-json\/activitypub\/1.0\/users\/0\/inbox","totalItems":0,"orderedItems":[],"first":"https:\/\/wyomingjarbo.com\/blog\/wp-json\/activitypub\/1.0\/users\/0\/inbox"}`

How is `"manuallyApprovesFollowers":"as:manuallyApprovesFollowers",` being populated?

**Comment by blindi0815** [comment]
my blog is https://endeavr.de
my blog user is @endeavr.de@endeavr.de
I can find the user on Mastodon. If I follow I encounter the same issue as per above.
if I do curl I get no result back:

`$ curl "https://endeavr.de/@endeavr.de"
$ 
`

**Comment by pfefferle** [comment]
@jarbochov I assume that there is an issue somewhere, that is caused by WordPress installations in sub-pathes. Currently I am checking if there is an issue with signature verification, because of a wrong generated URL/URI.

**Comment by blindi0815** [comment]
> @blindi0815 works for me
> <img alt="Screenshot 2023-09-14 at 23 14 39" width="896" src="https://user-images.githubusercontent.com/2373/268113231-a7f6097a-f1bb-4964-b9e0-7eec3458a702.png">

Yes because shame on me I should've just RTFM. My blog is in installed in root. I followed 
`location ~* /.well-known {
    allow all;
    try_files $uri $uri/ /blog/?$args;
}`

from the plugin FAQ and made it to

`location ~* /.well-known {
    allow all;
    try_files $uri $uri/ /?$args;
}`

Now I have 
`    location ~ ^/(.+/|)\.(?!well-known\/) {`
        `deny all;`
    `}`
    `location ~* /.well-known {
        allow all;
        try_files $uri $uri/ /?$args;
    }
`

and I am not sure if this is okay?

**Comment by blindi0815** [comment]
@pfefferle 
Doesn't from my instance marctodon.marci.one - it is a plain mastodon instance hosted by myself. Is there anything that the instance must support?

**Comment by pfefferle** [comment]
@blindi0815 sorry, I have no idea! I have no experience in hosting a Mastodon instance!

**Comment by blindi0815** [comment]
Might be an issue with the Mastodon instance version. Mine is running on 4.1.7, yours and @jarbochov is running on 4.2.0 nightly build. I can see the access in the nginx logs and they all look the same. Just that my instance doesn't like the response. Oh well. Thank you anyways

**Comment by pfefferle** [comment]
@edent @jarbochov can you test if the PR fixes your issue?

https://github.com/Automattic/wordpress-activitypub/pull/438

**Comment by edent** [comment]
site_url(): `https://shkspr.mobi/blog`

home_url(): `https://shkspr.mobi/blog`

**Comment by jarbochov** [comment]
That appears to have fixed it. Going to test to see if it pushes a post.

**Comment by jarbochov** [comment]
Post successful. Thanks for your quick turnaround this.

**Comment by pfefferle** [comment]
@edent do you have an update for us?

**Comment by edent** [comment]
@pfefferle I now have 80+ follower and they seem to be receiving my posts 😃

**Comment by scollovati** [comment]
Similar issue here for the blog id https://www.como1.it/@scout

Last version of the plugin and of WordPress.
No caching plugins are active. I've also tested the endpoint and the json file seems to be fine, but the blog cannot be followed.
