### ISSUE TITLE
After installing ActivityPub, I changed my Username and had a problem.

### ISSUE THREAD

**Issue by on1000mark** [Automattic/wordpress-activitypub#424]
Hello.

I installed Acticity Pub on July 9 under the username @on1000mark and,I have confirmed that @on1000mark@on1000mark.club is working on Mastodon.

But later, when I changed the username to on1000mark.club, @on1000mark@on1000mark.club stopped working when WordPress　was updated. 

Moreover, I can't find the user on1000mark.club@on1000mark.club on mastodon.

I have tried reinstalling the plugin, but the problem persists and I am stumped. Please let me know how to solve this problem.

**Comment by pfefferle** [comment]
It seems that you have a naming collision now. `on1000mark.club@on1000mark.club` still "points" to `on1000mark@on1000mark.club`. See https://webfinger.net/lookup/?resource=on1000mark.club%40on1000mark.club

**Comment by on1000mark** [comment]
Thank you.

I changed my username again to on1000mark for the time being and made a test post from WordPress. Am I correct in assuming that if I wait a while, the post will be posted from on1000mark@on1000mark.club as well?

**Comment by pfefferle** [comment]
No, it will only posted from the account you defined latest.

To clearify some things first: Are we talking about a user account or the blog account?

**Comment by on1000mark** [comment]
I was not aware of the distinction between the two.

I am referring to user accounts. I'm not sure about this one either.
![IMG_1171](https://github.com/Automattic/wordpress-activitypub/assets/134938808/122b4b63-0101-45dc-90a7-15121049ac2c)

**Comment by pfefferle** [comment]
Have changed the username and also the login name? Because ActivityPub is using the login name.

**Comment by on1000mark** [comment]
When you log in, you also enter a new username.
It is currently on1000mark.

**Comment by on1000mark** [comment]
Sorry, I looked at the settings and learned that there are two types of IDs: Blog profile ID and Author profile ID. I just changed the Blog profile ID to on1000mark.activitypub.on1000mark.club.
If this can be verified on Fediverse, my problem is solved.
![IMG_1178](https://github.com/Automattic/wordpress-activitypub/assets/134938808/a26807aa-9f00-4bbc-8729-18f7151ffe5d)

**Comment by on1000mark** [comment]
![Uploading IMG_1179.png…]()

**Comment by pfefferle** [comment]
What confuses me is, that it still points to the old identifier:

https://webfinger.net/lookup/?resource=on1000mark.activitypub%40on1000mark.club

(see the subject and the alias)

**Comment by pfefferle** [comment]
Besides of that, you seem to have an issue with caching:

```
## Request (23)
curl "https://on1000mark.club/author/on1000mark/" \
     -H 'Accept: application/activity+json'
```

This call returns HTML instead if JSON.

**Comment by on1000mark** [comment]
Can I solve this problem by changing my username to something completely different from the name of my blog?

**Comment by pfefferle** [comment]
no, the HTML issue can not be solved by re-naming at all. You have to check your caching plugin.

**Comment by on1000mark** [comment]
The cache plugin called Jetpack has stopped working.

**Comment by pfefferle** [comment]
I am glad it works now :)
