### ISSUE TITLE
Follow Me Block: address styling issues in dark themes

### ISSUE THREAD

**Issue by jeherve** [Automattic/wordpress-activitypub#425]
You can see the problem in action here:
https://notiz.blog/follow/#%23Fediverse

<img width="970" alt="image" src="https://github.com/Automattic/wordpress-activitypub/assets/426388/3a527586-36d8-407c-93ea-5dba938f3e2c">

This is happening because the modal background color is set to white:
https://github.com/WordPress/gutenberg/blob/f92f9e28ba4fb2e435cb89d5b327b707cb805ba7/packages/components/src/modal/style.scss#L21

All the while the text color is also a white color as defined by the theme.

I think it would be nice if the modal shipped with some styles to prevent that, maybe using core CSS vars provided by the theme.

**Comment by pfefferle** [comment]
+ it breaks on mobile view.

**Comment by mattwiebe** [comment]
I did fix this by overriding theme colors in the modal
