### ISSUE TITLE
Follow Me Block: too big for sidebar

### ISSUE THREAD

**Issue by anantshri** [Automattic/wordpress-activitypub#427]
First up thanks a lot for working on this plugin. this is a massive help in bringing wordpress to fediverse. 

I am using it for past 2-3 months and its been a smooth ride. New features are awesome and kudoes for the massive work on the upgrade.

Now for my greedy demands.

For http://blog.anantshri.info/ i have a big title and the userid also becomes big. follow block right now adds full title in large font and then adds full id below it. this squeezes the follow button and makes the whole widget ugly.

![image](https://github.com/Automattic/wordpress-activitypub/assets/236843/7d106fcd-cbe2-47bf-8577-0f703655d2b5)

The same scenario plays out in mobile view also. 

I have tried reducing font size assuming that was the culprit even then the widget didn't worked out. 

Couple of suggestion.

1. A re-designed widget may be.
2. A cutomizable block which allows me to change the text could also work out. 
3. A simple Follow me on Fediverse with a logo of fediverse or simmilar might also be a good option.

**Comment by pfefferle** [comment]
Same for main content on small screens (responsiveness).

**Comment by jeckman** [comment]
I'd love to be able to edit the text on the Follow button as well - I can hide in CSS the avatar and likely override some of the layout, but it'd be good to be able to chance the call to action text
