### ISSUE TITLE
Release v1.0.0 breaks existing profile pictures

### ISSUE THREAD

**Issue by sindastra** [Automattic/wordpress-activitypub#434]
### Quick summary

Since the update to version 1.0.0, my profile picture has been replaced by the Gravatar logo

### Steps to reproduce

1. Use version 0.17.0, see how profile picture works
2. Update to 1.0.0, see how profile picture was replaced by Gravatar logo

* See additional notes

### What you expected to happen

To see my profile picture.

### What actually happened

Gravatar logo is shown.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

I created my own plugin to generate avatars locally, which uses the `get_avatar` filter. It returns an `img` tag, with a `data:image` as source. This works well in WordPress itself, and also worked fine in ActivityPub version 0.17.0, so something must have changed in 1.0.0 which breaks the compatibility.

**Comment by pfefferle** [comment]
We are very sorry about that! Can you provide us a link to your blog and a profile/author URL, so that I can check what might be wrong?

**Comment by sindastra** [comment]
Certainly!

Blog URL: https://www.sindastra.de/

Profile URL: https://www.sindastra.de/p/author/sindastra

Handle: @sindastra@www.sindastra.de

**Comment by sindastra** [comment]
I just wanted to give a quick update: It works with the plugin "Simple Local Avatars", but not with mine. In case you encountered a working avatar, it must have been that. I disabled the plugin now so that you should be able to see the issue. Apologies, I had forgotten.

I have a guess: My plugin returns a data uri, could it be that some change was made for 1.0.0, where it expects a full URL to a file now instead?

**Comment by pfefferle** [comment]
I am not sure if other platforms support data-urls. But this part of the code has not changed, so maybe Mastodon has changed something recently and do no longer support data-uris!?!

**Comment by sindastra** [comment]
Hm, counter-point: The issue also affects Misskey. I see a Gravatar logo there as avatar now too.

**Comment by pfefferle** [comment]
We simply use WordPress' [get_avatar_url](https://developer.wordpress.org/reference/functions/get_avatar_url/), you can see it here: https://github.com/Automattic/wordpress-activitypub/blob/master/includes/model/class-user.php#L130C5-L130C19

**Comment by sindastra** [comment]
I just downloaded a copy of 0.17.0 from GitHub, it seems class-user.php didn't even exist back then?

So, how were avatars handled before?

<img width="425" alt="image" src="https://github.com/Automattic/wordpress-activitypub/assets/1236984/3692c6d1-73f5-4459-87e5-eb7dce298728">

**Comment by pfefferle** [comment]
The same way: https://github.com/Automattic/wordpress-activitypub/compare/0.17.0...1.0.0#diff-2b8b830bc889555be0335d61e8e4753dc83a00ec9eb0791d51c340f79ee6259eL19

**Comment by sindastra** [comment]
So, it seems it was moved from `author-json.php` to `class-user.php`. Hm, I wonder if that had some unintended side effect for my specific use-case.

Say, can you tell me where I'd fetch the avatar URL from my WordPress, in the same way fedi instances would fetch it? I'm curious to see the raw response from WordPress. 🤔

**Comment by pfefferle** [comment]
> So, it seems it was moved from author-json.php to class-user.php. Hm, I wonder if that had some unintended side effect for my specific use-case.

Yes, this was done, to simplify code and to not have the same code in several files.

> Say, can you tell me where I'd fetch the avatar URL from my WordPress, in the same way fedi instances would fetch it? I'm curious to see the raw response from WordPress. 🤔

I am not sure what you mean with that. The code we are using is the standard WordPress way to get the Avatar of a user and the default WordPress is using, is Gravatar.

```PHP
get_avatar_url(
	1, // the user-id
	array( 'size' => 120 )
);
```

But I am also using a local-avatar plugin and it works nicely on my page: https://notiz.blog/author/matthias-pfefferle/activitypub/

Plugin: https://de.wordpress.org/plugins/avatar-privacy/

**Comment by pfefferle** [comment]
I found a setting on `/wp-admin/options-discussion.php` called `Local Avatars Only` and if I checked that, the logo will be also used for ActivityPub.

**Comment by sindastra** [comment]
> I am not sure what you mean with that.

You have just answered my question by showing me your own URL:

https://www.sindastra.de/p/author/sindastra/activitypub

This is the URL I was looking for. (:

I can see there that it is indeed returning a Gravatar URL, rather than what my plugin returns.

I guess now that I know where to look, I can set up a test instance, start with 0.17.0, compare the response, and then try to find out what changed in 1.0.0.

PS My plugin uses the standard WordPress `add_filter` for `'get_avatar'`, which will process things, and then return a string with an `<img>` tag containing a data URI. This worked fine with 0.17.0, but I just wanted to point it out, in case I'm doing it the wrong way (my plugin replaces the Gravatars with local processing).

I will report back once I get around to debugging.

**Comment by pfefferle** [comment]
> I found a setting on `/wp-admin/options-discussion.php` called `Local Avatars Only` and if I checked that, the logo will be also used for ActivityPub.

Oh, maybe I forgot to tell you that I found these settings using the same plugin you use! So maybe this solves your issue?!?

**Comment by sindastra** [comment]
I should perhaps clarify that I've written my own plugin, which essentially generates the same images as Gravatar, but locally (it doesn't even request anything from Gravatar). I have not yet gotten around to publishing it as FOSS, but intend to do so.

The idea is that I choose the default "Gravatar" I want in the WordPress dashboard, and behind the scenes, it will generate those on the server and output the result. I use the `'get_avatar'` filter for this. This works fine in WordPress, and worked fine in ActivityPub 0.17.0.

If, from the top of your head, you could tell me whether using the `'get_avatar'` filter to hook into this, is the wrong or right way, or for some reason incompatible with 1.0.0, it would be kind if you could let me know.

**Comment by pfefferle** [comment]
So I will close this for now, feel free to re-open if still an issue.
