### ISSUE TITLE
Follow me widget does not update to selected author

### ISSUE THREAD

**Issue by pfefferle** [Automattic/wordpress-activitypub#440]
### Quick summary

If the blog has only one author and if the blog author is disabled, the widget will only show the default "hello dolly" dummy.

### Steps to reproduce

1. Disable Blog-User and enable Authors
2. Use widget.

### What you expected to happen

Use the only available author as default.

### What actually happened

Dummy user "hello dolly" shows

### Impact

All

### Available workarounds?

Yes, easy to implement

### Logs or notes

<img width="1118" alt="Screenshot 2023-09-15 at 20 47 50" src="https://github.com/Automattic/wordpress-activitypub/assets/2373/885ba352-e416-45ca-95c9-737dde09835f">

**Comment by mattwiebe** [comment]
I think that, if an unselect-able profile is selected, we should probably not render at all, except possibly with a warning for a logged-in user that they have an invalid selection

**Comment by pfefferle** [comment]
@mattwiebe the issue is, that if you only have one author (and blog disabled) the profile is not auto-selected and can't be selected.

**Comment by mattwiebe** [comment]
Sounds bad!
