### ISSUE TITLE
Safari sometimes shows the ActivityPub JSON rather than HTML

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#442]
### Quick summary

As reported by https://mastodon.social/@cazmockett/111076762694805294 and https://hachyderm.io/@benjamineskola/111080909366539827

Some users see the ActivityPub JSON when they visit the most recent blog post using Safari.

Here's a video of it happening on Epiphany (a Linux browser which uses the same engine as Safari).

[Screencast from 17-09-23 15:21:55.webm](https://github.com/Automattic/wordpress-activitypub/assets/837136/3035f2a0-8df2-48c7-ae48-eb5a1da183ff)

This doesn't happen on Firefox or Chrome. It can happen with `curl` (see Ben's post). 

This only seems to happen on the most recent post. 

### Steps to reproduce

1. Be an iOS / MacOS / Safari user.
2. Click on a link to the most recent blog post.

### What you expected to happen

All posts should return HTML unless specifically instructed.

### What actually happened

Some posts return JSON.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

Here's the request and response the browser sends and receives:

Request
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Referer: https://shkspr.mobi/blog/tag/book-review/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15

Response
Content-Security-Policy: upgrade-insecure-requests;
Content-Type: application/activity+json

**Comment by timnolte** [comment]
Are you certain that this isn't a coaching issue? What caching is setup on the site? If you are using Cloudflare there are known issues with Cloudflare and other caching not returning the correct content type.

**Comment by edent** [comment]
I am not using Cloudflare. I do have LiteSpeed cache running locally.

If I manually purge the page from LSCache, it appears to work normally. But I don't understand why it would serve JSON to that UA at all?

**Comment by timnolte** [comment]
OK, good news I also use LiteSpeed. I have written specific mod_rewrite rules to address this issue. You'll find more details here: https://www.timnolte.com/2023/04/09/fixing-openlitespeed-caching-for-activitypub-on-wordpress/

**Comment by edent** [comment]
Cheers Tim, I'll give that a go and see if it works.

**Comment by pfefferle** [comment]
@edent does it work for you?

@timnolte thanks a lot :)

**Comment by edent** [comment]
My next post publishes in a few hours. So I'll let you know this afternoon.

**Comment by pfefferle** [comment]
Btw. fixing LiteSpeed issue will also improve the ActivityPub implementation, because ActivityPub has the opposite issue and will receive HTML from time to time. Depending on which version will be accesses first.

**Comment by pfefferle** [comment]
Maybe you have to clean the cache completely, because it might still contain broken data?

**Comment by edent** [comment]
The timeline was:

1. Published post yesterday
2. People complained about seeing JSON in Safari
3. I cleaned the cache completely
4. Safari works
5. I installed Tim's .haccess rules above
6. Today, published a new post
7. User complained about Safari seeing JSON
8. Cleared the cache completely again
9. Safari works again

It seems to me this is an issue with the way LiteSpeed Cache plays with the ActivityPub plugin.  

If I do `curl https://example.com/blog/1 -H "Accept: application/json" ` I get HTML.

If I do `curl https://example.com/blog/1?a=123 -H "Accept: application/json" ` I get JSON.

Some random thoughts on how to fix it.

* Could the ActivityPub URls have `?activitypub=true` appended to them - rather than solely relying on content negotiation?
* I'll raise an issue with lscache_wp to see what they say.
* Umm... that's it. I'm out of ideas 😆

**Comment by timnolte** [comment]
@edent so I have this working perfectly, on my site. Dis you restart LiteSpeed to ensure that your `.htaccess` rules were picked up. I'm not clear on whether you are running OpenLiteSpeed or the enterprise LiteSpeed server. OpenLiteSpeed doesn't automatically read `.htaccess` files changes on every web request.

**Comment by timnolte** [comment]
@edent can you also provide a copy here of the `.htaccess` rules you implemented and also include where in your site structure you have your `.htaccess` file?

**Comment by edent** [comment]
@timnolte it looks like your rules need to be at the *top* of the .htaccess file. See https://github.com/litespeedtech/lscache_wp/issues/578#issuecomment-1723636235

It also needed to be in my `/blog/` subdirectory - but that's just my own weird set up.

I think this is now fixed. But I'll leave the issue open to see if any Safari users report weirdness tomorrow.

**Comment by timnolte** [comment]
@edent yes, this does need to be at the top of your `.htaccess` file before other rules are processed. For clarity this actually has nothing to do with Safari.

**Comment by brucknerite** [comment]
This exact same issue happened to me today, but my setup is different (Varnish Cache instead). It's happening for some Chrome, Firefox and Safari clients in Android and iOS, but not others. Seemed to sort itself out by clearing the server cache. Will report further if it continues happening. Any log where I should look for clues?

Thank you for your attention :-)

---
Iván Rivera
https://brucknerite.net
https://social.brucknerite.net/@brucknerite
