### ISSUE TITLE
following blog id doesn't work

### ISSUE THREAD

**Issue by anantshri** [Automattic/wordpress-activitypub#443]
### Quick summary

for this https://blog.anantshri.info/ i had a anantshri user that was used for posting stuff before the global blog level id came into picture i configured that user and about 8-9 followers were following me. 

on upgrading to 1.0 version i moved to blog level user id but kept the id same as before so its still anantshri@blog.anantshri.info

However.
a. all ~~exciting~~ existing followers are gone from the list (i can understand this due to movement of profiles)
b. all followers were still thinking they were following. so i went and unfollowed and refollowed.
c. i dont see a single follow request for approval, nor i see follows auto approved. 
d. profiles on mastodon show that its still waiting for confirmation. 

as you can see https://github.com/Automattic/wordpress-activitypub/issues/301#issuecomment-1541877374 this was working for me earlier.

### Steps to reproduce

a. activate new version.
b. move from user to global profile
c. unfollow and refollow subscribers

### What you expected to happen

subscribers should appear in new setting window

### What actually happened

subscribers are getting a waiting for approval and no message recieved at blog level.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

the impact questions are vague. If an individual is making a note they will mostly be on user impact. also available workarounds is wierd. what is platform in this case wordpress or this plugin.

**Comment by pfefferle** [comment]
It is not a real migration if you change the username of the blog, to the username of an author. I would not recommend to do that, because of several reasons:

1. The Followers are mapped to an internal ID, so changing only the usernames, does not move the followers to the new user.
2. The API endpoints for the blog user are different to the endpoints of an author. Because Mastodon use caching, he tries to send messages to the old cached inbox of the author and that seem to cause some issues.

It seems that your blog is now in an inconsistent condition and you might have to wait until mastodon clears the cache.

**Comment by anantshri** [comment]
That makes sense. however is there a warning that can be issues if people end up doing such a thing. 

Also in my scenario i assume the cache itself will clear and then things would work just fine i assume i will circle back after 6-7 days hopefully that will invalidate the cache.

**Comment by pfefferle** [comment]
> however is there a warning that can be issues if people end up doing such a thing.

Good point! Will work on that!

**Comment by pfefferle** [comment]
I will close this for now, please re-open if the problem still exists.

**Comment by anantshri** [comment]
Just a FYI problem persisted till now. i have now gotten around to that by renaming the user id. so now my user id is 

@anant@blog.anantshri.info and this is being visible and mastodon users are able to follow it.
