### ISSUE TITLE
Image removed from post is still kept in json attachment list

### ISSUE THREAD

**Issue by anantshri** [Automattic/wordpress-activitypub#447]
### Quick summary

I was working on a blogpost. added an image and removed it to replace it with new version. When the post was published the old image is still referenced as attachment.

### Steps to reproduce

1. Create a blogpost
2. add an image
3. remove that image
4. add another image
publish the page

json contains both the old image and new image reference.

### What you expected to happen

only new image as attachment

### What actually happened

old image as well as new image in attachment

![image](https://github.com/Automattic/wordpress-activitypub/assets/236843/6b134361-db90-4f6e-b66b-94c1cd04b251)

**Github-Actions-1.png**

Only when i deleted the image from media library did that image went away from the attachment

![image](https://github.com/Automattic/wordpress-activitypub/assets/236843/6c0f1a77-7f87-473e-b42d-570098ea7202)

Double checked both html of blogpost and feed xml they were not referencing to **Github-Actions-1.png** only to **Github-Actions-1-1.png**

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by mattwiebe** [comment]
@anantshri thanks for the report, I stumbled across this in testing too and this was the reminder I needed to circle back
