### ISSUE TITLE
Ability to delete posts on ActivityPub

### ISSUE THREAD

**Issue by cbirdsong** [Automattic/wordpress-activitypub#449]
### What

You should be able to delete Mastodon/ActivityPub posts without affecting the post in Wordpress.

### Why

While configuring the plugin I accidentally pushed two very long blog posts out to ActivityPub since the default is set to push the full content. These posts are stuck on my profile since you can't delete the post on Mastodon/ActivityPub without also deleting the post in Wordpress.

### How

It seems like this feature would be located in a meta box in the edit post screen or available in a new "Posts" tab in the plugin settings page.

---

### Related: 
- #264

**Comment by pfefferle** [comment]
thats not that easy, because mastodon can re-grab it, if someone puts the URL of the post into the search field. so we need to remove the post from any API endpoint and to disable the JSON representation of it.
