### ISSUE TITLE
Other servers looking for nodeinfo/serverinfo in wrong places

### ISSUE THREAD

**Issue by carbeck** [Automattic/wordpress-activitypub#450]
### Quick summary

I activated the plugin recently to toy around with it and now my server constantly receives info requests from other Fediverse servers it can't answer.

### Steps to reproduce

1. Install and activate the plugin in your Wordpress
2. Access the URLs in the log excerpt

### What you expected to happen

JSON content with the relevant info gets returned

### What actually happened

A 404 page gets retruned

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

"GET /.well-known/x-nodeinfo2 HTTP/1.1" 200 278 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://[some friendica server]"
"GET /api/v1/directory?limit=1 HTTP/1.1" 404 31561 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://[some friendica server]"
"GET /poco HTTP/1.1" 404 31561 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://[some friendica server]"
"GET /api/v1/instance/activity HTTP/1.1" 404 31561 "-" "Friendica 'Giant Rhubarb' 2023.01-1502; https://[some friendica server]"
"GET /nodeinfo/2.1 HTTP/1.1" 404 31561 "-" "curl/7.81.0"
"GET /nodeinfo/2.0 HTTP/1.1" 404 31561 "-" "curl/7.81.0"
"GET /api/v1/instance HTTP/1.1" 404 31561 "-" "curl/7.81.0"
"GET /api/v1/config HTTP/1.1" 404 31561 "-" "curl/7.81.0"
"GET /api/nodeinfo HTTP/1.1" 404 31561 "-" "curl/7.81.0"
"GET /api/v3/federated_instances HTTP/1.1" 404 31561 "-" "curl/7.81.0"
"GET /wp-json/nodeinfo/2.1 HTTP/1.1" 404 114 "-" "curl/7.81.0"

**Comment by pfefferle** [comment]
Hey @carbeck there are a lot of APIs that try to help identify the server and some to get some meta data about the server. Friendi.ca and others are trying to find one of these endpoints.

The ActivityPub plugin currently only supports [NodeInfo](https://github.com/jhass/nodeinfo), which is the most common and open format out there.

The `/api/v1/*` URLs are Mastodon specific API endpoints and not part of ActivityPub.

You can see an example of the NodeInfo endpoint here: https://notiz.blog/.well-known/nodeinfo
