### ISSUE TITLE
Help! How do I accept follow requests?

### ISSUE THREAD

**Issue by Cassolotl** [Automattic/wordpress-activitypub#467]
### Quick summary

My blog is `@machspace@machspace.org`. I requested to follow it from `@cassolotl@eldritch.cafe` (my main Mastodon account) and it's showing up as a follow request having been sent, and posts are not reaching my main Mastodon account's instance.

I can't find a way within the plugin's UI on Wordpress where follow requests are being held, so I assume something strange is happening. Does anyone know the most likely reason(s) why this might be happening?

### Steps to reproduce

.

### What you expected to happen

Follow request to be automatically accepted by my Wordpress blog with the ActivityPub plugin installed.

### What actually happened

My follow from eldritch.cafe is being held as a follow request.

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment]
Hey @Cassolotl the plugin should auto-accept all requests, so it seems to be an issue. Maybe this helps https://github.com/Automattic/wordpress-activitypub/issues/341 ???

**Comment by Cassolotl** [comment]
@pfefferle Thank you, I'll have a look at that now!

**Comment by Cassolotl** [comment]
Okay so that guide says:

> If you do have root access, you’ll be able to view rule 92040 in either your control panel (`WHM users->Security Center->ModSecurity Tools->Rules List`)

I can't find anything like this in my control panel on Bluehost. The closest I can find has a list of email addresses, some I've set up and some with a string of random letters and numbers @mydomain.com

> or in your server at the listed path ( `/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf` ).

The /etc folder on my server doesn't have an apache2 folder, it just has a folder for each domain on the server, like so:

<img width="543" alt="Screenshot_2023-09-25_at_19_08_26" src="https://github.com/Automattic/wordpress-activitypub/assets/6607512/f93a2cd7-4b65-42bc-a033-d5d06f6d5ccc">

So I'm a bit stuck!

**Comment by pfefferle** [comment]
Have you caching enabled? It seems that your user profiles do not work:

```
curl "https://machspace.org/author/cassian/" \
     -H 'Accept: application/activity+json'
```

**Comment by Cassolotl** [comment]
@pfefferle Thanks, I didn't know how to do that but I brought it up with Bluehost too.

They said they've whitelisted the rule IDs and made some mod security corrections, and it should all be working normally within 1-2 hours. I'll post an update if things are working. :)

**Comment by Cassolotl** [comment]
Update: I had to cancel and refollow, but following works immediately now. :) Thank you!
