### ISSUE TITLE
New posts are not being published on Mastodon after upgrade to 1.0.1

### ISSUE THREAD

**Issue by suramyatomar** [Automattic/wordpress-activitypub#470]
### Quick summary

I upgraded to 1.0.1 earlier today and since then the posts on the blog are not being published to Mastodon. 
Blog: https://www.suramya.com/blog/
Mastodon : https://mastodon.social/@suramya@www.suramya.com

As you can see the last post pushed to Mastodon was 5 days ago, even though I posted 2 posts today. I didn't see any error messages and the only change made was to upgrade the plugin version.

### Steps to reproduce

1. Log into suramya.com/blog
2. Make new post 
3. Submit

### What you expected to happen

The post should be available at https://mastodon.social/@suramya@www.suramya.com 

### What actually happened

The post is not available at https://mastodon.social/@suramya@www.suramya.com 

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment]
It seems that you have used a username, that was previously an author-name for the blog. Is that correct?

**Comment by pfefferle** [comment]
The URL `https://mastodon.social/@suramya@www.suramya.com` redirects to `https://www.suramya.com/blog/author/suramya-2/` but it should redirect to `https://www.suramya.com/blog/@suramya`. This is because Mastodon caches Profiles for quite some time, so all the signatures and IDs of the blog user, does not match the user, Mastodon has in the cache and so it will decline your post.

**Please do not use author names for the blog, because it could mess up a lot.**

(I will also add a disclaimer to the settings soon!)

**Comment by suramyatomar** [comment]
Yes, I had originally posted the blog entries as admin (display name was suramya), which I then changed to suramya (removing the admin user). The author profile is available at: https://www.suramya.com/blog/author/suramya-2/

The current settings are as follows: 

![Screenshot 2023-09-25 at 15-31-41 Welcome ‹ Suramya's Blog — WordPress](https://github.com/Automattic/wordpress-activitypub/assets/35488010/49b81f20-1c8f-435a-9a34-f68b8b340695)

**Comment by pfefferle** [comment]
@suramyatomar see my last comment.

**Comment by suramyatomar** [comment]
> The URL `https://mastodon.social/@suramya@www.suramya.com` redirects to `https://www.suramya.com/blog/author/suramya-2/` but it should redirect to `https://www.suramya.com/blog/@suramya`. This is because Mastodon caches Profiles for quite some time, so all the signatures and IDs of the blog user, does not match the user, Mastodon has in the cache and so it will decline your post.
> 
> **Please do not use author names for the blog, because it could mess up a lot.**
> 
> (I will also add a disclaimer to the settings soon!)

Hmm... ok. Let me see if I can figure out how to change it and I will get back to you with an update. Interestingly it was working till last week. 

Thanks for the fantastically fast response! (5 mins from my 1st post before you responded)

**Comment by suramyatomar** [comment]
How do I change this URL https://mastodon.social/@suramya@www.suramya.com to redirect to https://www.suramya.com/blog/@suramya? 

I don't see any obvious way to change it in the settings.

**Comment by pfefferle** [comment]
> How do I change this URL https://mastodon.social/@suramya@www.suramya.com to redirect to https://www.suramya.com/blog/@suramya?
>
> I don't see any obvious way to change it in the settings.

You can not do that, that is cached by Mastodon! And that is the big issue. Theoretically everything you did, should work, but in practice, Mastodons cache breaks it.

So you have two options:
1. Change it back to how it was before and use a different name for the blog-user.
2. Wait until Mastodon changes the cache.

But be aware that there is another issue: Using the same name as a former author is not a migration, all the followers are still on the authors profile, so the blog user (even if he has the same name) is a different user and has no followers so far.

**Comment by suramyatomar** [comment]
Changing the  blog profile ID to @blog@suramya.com resolved the issue. 
However, now the name of the blog is now coming as: Suramya&#039;s Blog @blog@www.suramya.com
instead of Suramya's Blog  @blog@www.suramya.com

**Comment by pfefferle** [comment]
I will close this for now, please re-open if still an issue!
