### ISSUE TITLE
My blog's posts aren't appearing on Mastodon Home feed

### ISSUE THREAD

**Issue by Cassolotl** [Automattic/wordpress-activitypub#476]
### Quick summary

I've installed the plugin on the blog at https://www.machspace.org (`@machspace@machspace.org`), and I'm following it from my main account on Mastodon (`@cassolotl@eldritch.cafe`), and I've made some test posts on the machspace blog (machspace.org/blog), but they're not appearing on my Mastodon home feed. (It's been about an hour, and I've since deleted the test posts.)

Any troubleshooting resources, FAQs, etc. for this issue?

Thanks in advance!

### Steps to reproduce

.

### What you expected to happen

The post should appear

### What actually happened

The post did not appear

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment]
You have enabled both author types (Authors and Blog-User). In this case the Blog-Posts will be federated under the name of the Author and the Blog-User boosts these posts. But your Author profiles are not accessible atm.

```
curl "https://machspace.org/author/cassian/" \
     -H 'Accept: application/activity+json'
```

That is mostly the case if you have a caching plugin in place.

You have two options:

1. Deactivate the Authors in the ActivityPub-Settings, then all posts will be published under the name of the Blog.
2. Try to exclude author Profiles (`https://machspace.org/author/cassian/`) from the caching.

I hope this helps.
