### ISSUE TITLE
Images are being stripped from post and appended at the end at Mastodon

### ISSUE THREAD

**Issue by suramyatomar** [Automattic/wordpress-activitypub#499]
### Quick summary

Hi... Sorry, but I have another issue I want to report :)

When I add Images inline in a blog post and publish it, the post on the Mastodon server removes the inline images and attaches them as an attachment at the end of the post. Also, if we have defined an alt tag for the image that gets stripped as well.

I would like to retain the images inline with the text when publishing to mastodon.
e.g. The original post (https://www.suramya.com/blog/2023/10/this-is-why-you-should-never-throw-out-old-cables/): 
![Screenshot_20231009_235201](https://github.com/Automattic/wordpress-activitypub/assets/35488010/245d8ade-5d14-45a6-be03-70e62c6be8fb)

What was published on Mastodon (https://mastodon.social/@blog@www.suramya.com/111188080117901752)
![Screenshot_20231009_235127](https://github.com/Automattic/wordpress-activitypub/assets/35488010/bb52b680-cb2b-4b64-ab9d-802142d64f99)

### Steps to reproduce

1. Create a blog post
2. Add an image in the middle of the post
3. Publish

### What you expected to happen

The post on Mastodon should have the image in the middle of the post.

### What actually happened

The inline image is removed and added as an attachment at the end of the post

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Running the latest version 1.0.2 of the plugin

**Comment by pfefferle** [comment]
This is (sadly) an issue of Mastodon, the plugin does not strip any image.

**Comment by pfefferle** [comment]
Here you can see the allowed HTML elements https://docs.joinmastodon.org/spec/activitypub/#sanitization

Sadly no `<img />` allowed!

**Comment by suramyatomar** [comment]
Ah ok. That sucks, but thanks again for responding so quickly (within 2 mins!!!)
Closing the ticket since this is not a plugin issue.
