### ISSUE TITLE
I can find single users but not the account which should represent the whole blog

### ISSUE THREAD

**Issue by schiessle** [Automattic/wordpress-activitypub#507]
### Quick summary

I have enabled the latest activitypub plugin on the blog https://gruene-urbach.de and activated the blog profile:

![image](https://github.com/Automattic/wordpress-activitypub/assets/1589737/0eec21b8-86aa-483d-a760-36352fca7af6)

But from Mastodon I can only find the individual accounts from authors. If I search for @wir@gruene-urbach.de I get a 302 in the wordpress server log and Mastodon doesn't find the blog profile:

````
49.13.6.146 - - [12/Oct/2023:21:21:51 +0200] "GET /.well-known/webfinger?resource=acct:wir@gruene-urbach.de HTTP/1.1" 500 302 "-" "http.rb/5.1.1 (Mastodon/4.2.1; +https://mastodon.social/)" 909 6315
````

### Steps to reproduce

1. try to find @wir@grune-urbach.de on any Mastodon server

### What you expected to happen

You can find the blog profile and follow it

### What actually happened

blog profile are not found

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment]
Hallo @schiessle 👋

Can you share your PHP, WordPress and ActivityPub version?

**Comment by schiessle** [comment]
Hi, I just tried it again and now it works... :slightly_smiling_face:  Either it was a caching issue or it was fixed by the latest version of the plugin, the plugin was updated last night automatically from version 1.0.6 to 1.0.7
