### ISSUE TITLE
Comments deleted from the fediverse are not deleted on Wordpress

### ISSUE THREAD

**Issue by lapineige** [Automattic/wordpress-activitypub#51]
If a comment is posted for instance from Mastodon, and then deleted from Mastodon, it's still appearing in Wordpress.
Which means people can't remove their comments (ok, it's the case in Wordpress by default, but not intended to happen for someone on the fediverse) while they could think they were deleted; rewriting them create doubles; mistaken mentions (private statuses too, right now #50) are also in the comments.

I believe it should at least be placed in the trash.

**Comment by mediaformat** [comment]
Will fix

**Comment by lapineige** [comment]
Great, let me know if you want testing :)

**Comment by pfefferle** [comment]
Keep

**Comment by pfefferle** [comment]
Keep

**Comment by pfefferle** [comment]
This is fixed now!
