### ISSUE TITLE
blog not on root folder breaks links

### ISSUE THREAD

**Issue by JollyOrc** [Automattic/wordpress-activitypub#510]
### Quick summary

for historic reasons, my wordpress installation lives in the /blog/ subfolder and is adressable as such. I assume that there are more than just my installation with this kind of setup.

(so instead of www.domain.tld, the url is www.domain.tld/blog)

This breaks the profile id of the blog in Activity Pub, as it defaults to blog@www.domain.tld.

### Steps to reproduce

1. start at  www.domain.tld/blog
2. add activity pub plugin
3. go to Activity Pub settings
4. enable activityPub profile for blog
5. Profile-Id for the blog points to www.domain.tld, which creates a non-working profile link

### What you expected to happen

have a profile link that actually works

### What actually happened

the profile link returns 404

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment]
In the FAQ of the readme is a section for blogs in subpaths. This needs some config in the root domain and that's why the plugin can't do it out of the box.

**Comment by JollyOrc** [comment]
that does the trick, thanks a lot!

do you want me to create a new issue so that there's a hint in the UI? (if one just installs the plugin through the wordpress UI, one doesn't necessarily see the readme. Exhibit a: me :) )
