### ISSUE TITLE
POST in inbox gives Error 500

### ISSUE THREAD

**Issue by uk3** [Automattic/wordpress-activitypub#514]
### Quick summary

[ cut & paste from wordpress support site ]

I now (re-)installed the Activity-Pub Plugin. But it just randomly works. Most of the time the following request just produces error 500.)

From the Log of the Mastodon Instance (the access log from the wordpress system shows the same).
Mastodon::UnexpectedResponseError: https://le-chat-a-velo.at/wp-json/activitypub/1.0/users/0/inbox returned code 500

Some requests eventually get through. But

I tried disabling various plugins without success. The Error-Log of wordpress or PHP.

After a bit of playing around, we observed the following:
Pixelfed <-> WordPress works reliable.
Mastodon <-> WordPress does not work – gives the 500 on the POST reqest to the inbox.

We cleared various caches on both sides, enabled and disabled caches etc. with no difference in the outcome. We also tried 2 different Mastodon Instances with the same result. (Mastodon versions 4.2.0 and 4.3.0 alpha).

What I observed is, that sometimes the followers even end up in the database of wordpress. But for the failed requests the “activitypub_user_id” meta attribute to the follower is missing. However manually adding it does not change the behavior (it just shows up in the list in the admin-panel afterwards).

key problem for me is how to find out what causes the 500 – since the log is empty.

Cheers, ulrich

### Steps to reproduce

See above

### What you expected to happen

202 instead of 500 ;-)

### What actually happened

Error 500
le-chat-a-velo.at "POST /wp-json/activitypub/1.0/users/0/inbox HTTP/1.1" 500 680 "-" "http.rb/5.1.1 (Mastodon/4.2.0; +https://miau.le-chat-a-velo.at/)"

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

blog running at le-chat-a-velo.at
User: lechat@le-chat-a-velo.at

**Comment by uk3** [comment]
After further observation, it looks like either a cacheing issue or some kind of race condition.
Requests from Mastodon eventually get through - but if so, only the first one succeeds, then we are back in 500-Land. 
But I did not figure out any pattern yet.

**Comment by pfefferle** [comment]
Is it possible to give me an account on one of the Mastodon instances, so I am able to debug the issue?

**Comment by uk3** [comment]
> Is it possible to give me an account on one of the Mastodon instances, so I am able to debug the issue?

The one Instance is https://toot.cat/
This is not operated by us - it's a public one, there you can easily create an account.

**Comment by uk3** [comment]
> And do you maybe have a full example of what is sent to the inbox, causing the issue?

```
"{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://miau.le-chat-a-velo.at/8b2a5f7c-142a-4df9-8a7e-fad4fb1d324e\",\"type\":\"Follow\",\"actor\":\"https://miau.le-chat-a-velo.at/users/gudroot\",\"object\":\"https://le-chat-a-velo.at/@lechat\"}", 109415847633434590, "https://le-chat-a-velo.at/wp-json/activitypub/1.0/users/0/inbox"
```

**Comment by uk3** [comment]
> Is it possible to give me an account on one of the Mastodon instances, so I am able to debug the issue?

And you can also try to follow `@lechat@le-chat-a-velo.at` from any other instance (behavior would be interesting anyway)

**Comment by pfefferle** [comment]
this is weird, I can't even see requests coming through to my WordPress installation, so it must be already blocked by the webserver!

**Comment by uk3** [comment]
I found the problem - it is a timing issue.

in /includes/functions.php Line 82
the timeout of 3 seconds is to short. 

For testing setting it to 30 Seconds and everything works as expected and reliable.

And appearently the error handling in case of a timeout is missing out on something and just throws a 500.

**Comment by pfefferle** [comment]
erster :)

**Comment by uk3** [comment]
I tried 5 in my setup and was fine for now - but 10 should be very safe.
Appearently the server responded in a way that 3 was slightly to short most of the time and sometimes sufficient.
👍

**Comment by uk3** [comment]
At some point a slightly better error handling of problems in the Http::get part would be helpful to pinpoint problems easier.

**Comment by pfefferle** [comment]
Yes, we are generally thinking a lot about re-tries!
