### ISSUE TITLE
Usernames with spaces lead to problems with Mastodon usernames

### ISSUE THREAD

**Issue by beergeekdotcom** [Automattic/wordpress-activitypub#515]
### Quick summary

Example -- spaces are valid in username in WordPress -- so a username of "First Last" in WP would lead to a Mastodon username of @First Last@domain.com -- which is a bit of an issue for some Mastodon clients.

Suggestion -- escape the usernames to make sure they make valid Mastodon usernames -- like @FirstLast@domain.com

### Steps to reproduce

Obvious

### What you expected to happen

See above

### What actually happened

See above

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by jazmichaelking** [comment]
Now that WP user names need portability, maybe AP account creation should sanitize using $strict

https://developer.wordpress.org/reference/functions/sanitize_user/
