### ISSUE TITLE
Feature Request: Large Blogs / Multiple Writer sites would like better organization of content to "users" on Mastodon

### ISSUE THREAD

**Issue by beergeekdotcom** [Automattic/wordpress-activitypub#516]
### What

Think of a large content blog -- with multiple users and sections, like a newspaper. While users will likely love to follow individual writers, they also would like to follow content types or categories of content as well -- instead of just writers or all content. That same site might have user generated content -- like classified ads (sticking with the newspaper idea).

### Why

For example in the newspaper site example -- a user may want to follow all sports coverage, but not news or business. So being able to define a post type, category, or tag as a virtual Mastodon user would be ideal for this.

### How

Example -- assuming that the newspaper publishes at @newspaper.com@newspaper.com for all content:

All content in the "Sports" category could map to @sports@newspaper.com
All content tagged as San Francisco Giants could map to @sfgiants@newspaper.com
All content with post type "classified ad" could map to @classifieds@newspaper.com
etc.

**Comment by Timothyjchambers** [comment]
Especially for larger sites, this is a very compelling feature request and would enable a robust means of following specific content users care about independently of any individual author from the site. Highly encouraged that this be considered.

**Comment by jazmichaelking** [comment]
This could lead to an almost infinite number of federated accounts being created, rendering account search unusable when trying to find a user.  We don't want a repeat of the BirdSiteLive account creation fiasco - https://write.as/nicolas-constant/closing-the-official-bsl-instance

I suggest:

1. No matter what, do not allow the creation an account for "@uncategorized@example.com" (800 million user accounts could be created)
2. Allow the enabling of a federating account for each Contributor and above, but do not do it by default (see fedidb for an example of a wordpress site already showing >10k user accounts https://fedidb.org/software/wordpress)
3. "tag" already exists in AP https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tag and WP tags can map to this easily
4. Consider use of AP's Collection to map to WP Category (eg https://www.w3.org/ns/activitystreams#CollectionPage and /category/[slug]/ - AP clients may need to learn to use Collection in...
5. context. I wonder if wp_post_type could use AP's Object context as a means to help clients know what to do with a given post. This may also help with inReplyTo for threaded replies to a post.
6. More of an aside, but if more AP clients allowed users to follow an RSS feed as well as AP accounts (1) the world would be a better place (2) people would stop creating "accounts" for RSS feeds and (3) you could then simply use the existing WP rss feeds and hooks.

**Comment by beergeekdotcom** [comment]
Yeah, I agree that something automated would not be all that useful. But something more manually created could be very useful. Especially so for content features on a subject -- either long term (a sports team, editorial focus) or short term (Election 2024, Olympics, etc.)

Something like defining a "user" by selecting any mix of single or multiple post_types and taxonomy / taxonomies.

An Example:

user = @wwc20203@publication.com is defined as
post_type = post, category = sports, and tag = worldcup2023

Cheers,
Jeff

**Comment by Timothyjchambers** [comment]
Curious if this feature was officially closed, or only closed due to a bot making it so after no action? Any chance of moving this idea back to life?
