### ISSUE TITLE
Feature Request: Allow specific posts to be excluded?

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#517]
### What

I added an old post to my site which I gave the published date of March 2011.  This has now appeared at the most recent post on `@blog@shkspr.mobi`

Would it be possible to add an option to either:

* Exclude specific posts from appearing in the AP?
* Exclude a category of posts from appearing?

### Why

Users may want to exclude specific posts from appearing in their feed.

### How

JetPack has this filter which allows an editor to prevent a post being emailed to subscribers.

`add_filter( 'jetpack_allow_per_post_subscriptions', '__return_true' );`

Which adds this option to the editor

![Screenshot showing a checkbox.](https://github.com/Automattic/wordpress-activitypub/assets/837136/988da4c8-ed9a-4fbf-8df7-fffb37af311c)

JetPack also has [`jetpack_subscriptions_exclude_these_categories`](https://developer.jetpack.com/hooks/jetpack_subscriptions_exclude_these_categories/) which is a filter to exclude specific categories from being emailed to subscribers.

**Comment by iamwebrocker** [comment]
>  I gave the published date of March 2011. This has now appeared at the most recent post on @blog@shkspr.mobi

chiming in on that one - shouldn't the published date in general be treated as "the" date for post syndication?
How does the RSS feed handle this?
From an author's point of view the behavior described is very surprising.
