### ISSUE TITLE
Pages show in ActivityPub despite being disabled (in a weird way)

### ISSUE THREAD

**Issue by uk3** [Automattic/wordpress-activitypub#521]
### Quick summary

I have checked ActivityPub only for Posts (not Pages or media).
When I do an activity-Pub search for a Page it still shows up, but with all the [ap_*] fields being empty. The other custom fields and the page thumbnail are still populated.

### Steps to reproduce

1. Search for https://le-chat-a-velo.at/reisen/karpatenbecken-2023/ in on a mastodon server.

### What you expected to happen

i'd expect either the full content (since it is still publically avaliable) or a not found response (since pages are disabled)

### What actually happened

![image](https://github.com/Automattic/wordpress-activitypub/assets/8853188/1a4044f6-57dc-463b-adda-6b712f608f8f)

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by janboddez** [comment]
Experiencing this as well.

I think the issue is here: https://github.com/Automattic/wordpress-activitypub/blob/efd98acd0bf3f2c42f0ffc3d8f10920e74cb8512/includes/class-activitypub.php#L95

There should be a check on whether the post type is actually enabled. I think?
