### ISSUE TITLE
Mastodon's replies not showing up

### ISSUE THREAD

**Issue by splacat** [Automattic/wordpress-activitypub#535]
### Quick summary

Mastodon server at mastodont.cat
Wordpress version 6.3.2 at blog.mastodont.cat
ActivityPub plugin version: 1.0.10 

Wordpress's posts are showing up fine in my Mastodon server but replies from Mastodon are not showing up in Wordpress.

### Steps to reproduce

1. Publish a post in Wordpress
2. Reply the Wordpress's post from Mastodon

### What you expected to happen

Mastodon's replies showing up in Wordpress

### What actually happened

No replies at all

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

Any error in the logs.

**Comment by splacat** [comment]
After several hours without issues now site health is showing this

![IMG_9924](https://github.com/Automattic/wordpress-activitypub/assets/64102663/eef3bc0e-c0bd-4ab6-a703-a50c7b7a5120)

**Comment by pfefferle** [comment]
Have you checked spam, pending and thrash?

**Comment by splacat** [comment]
> Have you checked spam, pending and trash?

yes, nothing there

![IMG_9925](https://github.com/Automattic/wordpress-activitypub/assets/64102663/9be9f265-aad3-4db6-afee-80201a3459bf)

**Comment by splacat** [comment]
> OK, you can't misread that :)
> 
> Do you have a firewall, comment-captcha, spam or similar plugin installed?

These are the active plugins 

![IMG_9927](https://github.com/Automattic/wordpress-activitypub/assets/64102663/f8f832b9-d245-4a8f-897b-bfdfb889ecd4)
![IMG_9926](https://github.com/Automattic/wordpress-activitypub/assets/64102663/bda6f6cf-df7c-43fa-ac06-1e0d993655e0)

**Comment by splacat** [comment]
> Can you try to disable the caching and try again?

Do you mean Fast Cache?

**Comment by pfefferle** [comment]
And redis.

**Comment by splacat** [comment]
> And redis.

Deactivated and deleted WP Fastest Cache and now comments are arriving fine. 
redis is still active though.

![IMG_9929](https://github.com/Automattic/wordpress-activitypub/assets/64102663/1fc5052d-8de2-4383-a831-f3d28478ae83)

**Comment by splacat** [comment]
Noticed it works but with new created posts only. If I reply a yesterday WP post from my Mastodon account, the comment does not show up.
