### ISSUE TITLE
`contentMap` in AP objects is not a map, breaking compatibility with Pleroma and possibly other AP servers

### ISSUE THREAD

**Issue by ddvarpdd** [Automattic/wordpress-activitypub#548]
### Quick summary

Per https://www.w3.org/TR/activitystreams-vocabulary/#dfn-contentmap, "The content MAY be expressed using multiple language-tagged values". However, current implementation seems to be putting an array with a string instead of said map. This breaks compatibility with Pleroma and its forks, and possibly other ActivityPub servers that strictly conform to the standard.

### Steps to reproduce

1. Try requesting an object with any tool of choice (e.g. `curl -H "Accept: application/activity+json" https://pleromanonx86.wordpress.com/2022/09/30/quick-summary/`).
2. Alternatively, fetch an object by pasting its link into a search bar on any Pleroma instance.

### What you expected to happen

The object has a correct structure and thus is being successfully fetched by other servers. Using the link from my example, contentMap should look like this:
```
"contentMap": {
    "en": "<p>So I have work later today, but the tl;dr is I&#8217;m going to make a Pleroma instance/server run on a Sun Ultra 45, and if that fails I&#8217;m going to make it run on any other non-x86 old computer I have lying around in my basement. </p><p><span id=\"wordads-inline-marker\" style=\"display: none;\"></span></p><p><a href=\"https://pleromanonx86.wordpress.com/2022/09/30/quick-summary/\">https://pleromanonx86.wordpress.com/2022/09/30/quick-summary/</a></p>"
  },
```
Alternatively, it can be omitted entirely until WordPress introduces an ability to make a single blog post with multiple languages, as `content` already has a copy of post contents.

### What actually happened

contentMap field has a structure that follows:
```
  "contentMap": [
    "<p>So I have work later today, but the tl;dr is I&#8217;m going to make a Pleroma instance/server run on a Sun Ultra 45, and if that fails I&#8217;m going to make it run on any other non-x86 old computer I have lying around in my basement. </p><p><span id=\"wordads-inline-marker\" style=\"display: none;\"></span></p><p><a href=\"https://pleromanonx86.wordpress.com/2022/09/30/quick-summary/\">https://pleromanonx86.wordpress.com/2022/09/30/quick-summary/</a></p>"
  ],
```
And here's an exception thrown by a server that expects the proper map inside this object field:
```
** (BadMapError) expected a map, got: ["<p>So I have work later today, but the tl;dr is I&#8217;m going to make a Pleroma instance/server run on a Sun Ultra 45, and if that fails I&#8217;m going to make it run on any other non-x86 old computer I have lying around in my basement. </p><p><span id=\"wordads-inline-marker\" style=\"display: none;\"></span></p><p><a href=\"https://pleromanonx86.wordpress.com/2022/09/30/quick-summary/\">https://pleromanonx86.wordpress.com/2022/09/30/quick-summary/</a></p>"]
    (stdlib 4.1.1) maps.erl:581: :maps.to_list(["<p>So I have work later today, but the tl;dr is I&#8217;m going to make a Pleroma instance/server run on a Sun Ultra 45, and if that fails I&#8217;m going to make it run on any other non-x86 old computer I have lying around in my basement. </p><p><span id=\"wordads-inline-marker\" style=\"display: none;\"></span></p><p><a href=\"https://pleromanonx86.wordpress.com/2022/09/30/quick-summary/\">https://pleromanonx86.wordpress.com/2022/09/30/quick-summary/</a></p>"])
    (pleroma 2.5.54-321-g17c336de-develop) lib/pleroma/web/activity_pub/transmogrifier.ex:347: Pleroma.Web.ActivityPub.Transmogrifier.fix_content_map/1
    (pleroma 2.5.54-321-g17c336de-develop) lib/pleroma/web/activity_pub/object_validators/article_note_page_validator.ex:93: Pleroma.Web.ActivityPub.ObjectValidators.ArticleNotePageValidator.changeset/2
    (pleroma 2.5.54-321-g17c336de-develop) lib/pleroma/web/activity_pub/object_validators/article_note_page_validator.ex:33: Pleroma.Web.ActivityPub.ObjectValidators.ArticleNotePageValidator.cast_and_apply/1
    (pleroma 2.5.54-321-g17c336de-develop) lib/pleroma/web/activity_pub/object_validator.ex:218: anonymous fn/1 in Pleroma.Web.ActivityPub.ObjectValidator.cast_and_apply_and_stringify_with_history/1
    (pleroma 2.5.54-321-g17c336de-develop) lib/pleroma/web/activity_pub/object_validator.ex:317: Pleroma.Web.ActivityPub.ObjectValidator.do_separate_with_history/2
    (pleroma 2.5.54-321-g17c336de-develop) lib/pleroma/web/activity_pub/object_validator.ex:106: Pleroma.Web.ActivityPub.ObjectValidator.validate/2
    iex:1: (file)
```

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

**Comment by pfefferle** [comment]
Then you seem to not have set a default language for your blog or it is overwritten by something else (a plugin or so). Check the output of my blog: https://notiz.blog/2023/10/23/the-next-big-social-network-is-just-the-web/activitypub/

**Comment by pfefferle** [comment]
Oh, I am sorry, it seems to be an issue on WordPress.com!

**Comment by ddvarpdd** [comment]
That isn't my blog, just something I had around in bookmarks. Here's a few other examples:
https://tukinet.wordpress.com/2023/10/18/抜粋のテスト2/activitypub/
https://alphabeticalzurich.wordpress.com/2023/11/01/altweg/activitypub/
Considering how many AP-enabled wordpress instances there are (at least 3585 that have federated elsewhere, according to [Fedilist](http://demo.fedilist.com/instance?software=wordpress)), and the fact said default language setting can be omitted (which many probably do), I would still consider this a bug.

**Comment by pfefferle** [comment]
Yes, as I said above, this seems to be an issue with the WordPress.com hosting. I will check why this behaves differently. Thanks for the report!

**Comment by ssundell** [comment]
Hmm, shouldn't the `contentMap` be removed altogether if the locale can't be parsed?

**Comment by pfefferle** [comment]
@ssundell the locale is existent but was wrongly parsed and that broke the functionality.

**Comment by ssundell** [comment]
> @ssundell the locale is existent but was wrongly parsed and that broke the functionality.

If I read 549 correctly, it fixes the situation where locale was two letters?

Here, locale is set as `fi_FI` but AP has borked `contentMap`: https://tarakka.fi/2023/11/05/tampereen-polkupyorailijat-nyt-fediversessa/

If I misread the bug, sorry about all this 8)

**Comment by pfefferle** [comment]
I assumed that WordPress always use the `fi_FI` format to define locales, but it seems that there are also cases where instances only store `fi`. In the case of `fi` the code snippet `\strstr( \get_locale(), '_', true )` returns false, and that broke the implementation.

The new version supports `fi_FI`, `fi-FI` and `fi` and transforms it to `fi`.
