### ISSUE TITLE
Images showing in ActivityPub feed even though they are not in the published post

### ISSUE THREAD

**Issue by mattedgar** [Automattic/wordpress-activitypub#553]
### Quick summary

When authoring a post I changed my mind about which image to include a couple of times. Only the latest image is included in the published version but the fediverse feed still embeds all 3

### Steps to reproduce

1. In /wp-admin/edit.php click to Add New Post
2. Insert an image to the post
3. Remove the image from the post
4. Add a different image to the post
5. Publish the post

### What you expected to happen

The ActivityPub version of the post to include only the image(s) that are in the published post
https://blog.mattedgar.com/2023/11/04/weeknote-30-october-to-3-november-2023/

### What actually happened

The ActivityPub version of the post includes images that were inserted then deleted from the draft before publication
https://mastodon.me.uk/@blog.mattedgar.com@blog.mattedgar.com/111353363264938089

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

I used Classic Editor on wordpress.com; not tested with Blocks editor or non-WP.com blogs
Privacy risk if users are unaware of the bug, and inadvertently leak private information that they have decided not to share

**Comment by janboddez** [comment]
(This is because WordPress labels those images as "attached" to that post. Attached doesn't mean they're part of the post, just that they were uploaded when creating/editing it.)

**Comment by pfefferle** [comment]
This is actually only the legacy fallback if you do not use the Block-Editor. If you are using the Block-Editor, it will parse the Images/Gallery blocks instead.

**Comment by mattwiebe** [comment]
Yes please use the Block Editor if at all possible, it is the only place where we can sensibly parse out what images are being used in the post, and also as of #536 we also have support for audio and video attachments in the Block Editor as well.

Patches are of course welcome to [`get_classic_editor_images`](https://github.com/Automattic/wordpress-activitypub/blob/1437b5acd80fa12d0accf3ccf450322aa226fe12/includes/transformer/class-post.php#L201) to improve this behaviour but it is not on our roadmap as the Classic Editor is deprecated in WordPress.
