### ISSUE TITLE
Feature Request: Support for "more" delimiter

### ISSUE THREAD

**Issue by MatzeKitt** [Automattic/wordpress-activitypub#556]
### What

I just came across a thing I don’t like for publishing the content of my posts. Would it be possible to add support for the “more” delimiter/block, that means that just the content above this delimiter is being posted in the Fediverse?

I tested `[ap_content]` as well as `[ap_excerpt length="400"]` and `[ap_excerpt]`.

### Why

I would find it more natural if it has the same functionality as WordPress itself so that you post only the content until the “more” delimiter.

And it’s a default WordPress functionality.

**Comment by mdingemanse** [comment]
What may be helpful to know (which was not clear to me from the documentation) is that ActivityPub's `[ap_excerpt]` does support `the_excerpt()` if you supply it, i.e. the separate excerpt you can provide for each post in WordPress.

**Comment by tomfinitely** [comment]
These seems like reasonable requests from a functionality standpoint, @MatzeKitt. Weighing in because I don't want to see this get closed.

**Comment by MatzeKitt** [comment]
I still have it on my list to create a pull request for it, but hadn’t yet the time to do so. 🥲

**Comment by pfefferle** [comment]
Is implemented now!
