### ISSUE TITLE
Feature Request: Label or hide image captions from the post's content

### ISSUE THREAD

**Issue by bruvellu** [Automattic/wordpress-activitypub#567]
### What

Hello :)

When a blog post has images with captions, the captions appear in Mastodon as if they were regular paragraphs of the main text. For example, a content like this:

<img src="https://github.com/Automattic/wordpress-activitypub/assets/361179/3a2e126a-8208-4bdf-b72e-8e1e3d97ef23" width="500px">

Becomes:

<img src="https://github.com/Automattic/wordpress-activitypub/assets/361179/a4debf94-42aa-4c88-b720-13fdedcd96fc" width="500px">

The image caption looks like a regular paragraph (except that there's no blank line to the next paragraph).

I'd like to suggest a way to distinguish or hide the captions from the post's content.

### Why

Captions appearing as regular paragraphs can be confusing and break the flow of the text.

### How

One solution would be to hide all captions. They are usually sideline information describing the image itself. And since the media files become attachments, not showing the captions in the post makes sense. 

The other solution I can think of would be to prepend a label to the caption. Something like:

```
A regular paragraph.

[caption] This is an image caption.

Another regular paragraph.
```

Thanks!

**Comment by pfefferle** [comment]
That is not trivial, because Mastodon is not the only platform out there, but one of the few that does not allow inline images. Friendi.ca on the other hand shows all properly.

So if we remove the caption, we would limit other users that focus on/optimize for Friendi.ca.

**Comment by pfefferle** [comment]
See: https://github.com/mastodon/mastodon/issues/29747

**Comment by bruvellu** [comment]
Thanks, @pfefferle!
