### ISSUE TITLE
PHP deprecated: activitypub/includes/class-webfinger.php

### ISSUE THREAD

**Issue by cybeardjm** [Automattic/wordpress-activitypub#574]
### Quick summary

While checking my PHP errorlog, found this error repeated multiple times.

[20-Nov-2023 18:24:40 UTC] PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /srv/data/web/vhosts/(domain)/htdocs/wp-content/plugins/activitypub/includes/class-webfinger.php on line 44

### Steps to reproduce

Seems to happen in the background

### What you expected to happen

Check error...

### What actually happened

Nothing visible as seems to happen in the background.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
Thanks for all your debugging! I really appreciate it!

I have already fixed that issue: https://github.com/Automattic/wordpress-activitypub/blob/master/includes/class-webfinger.php#L44
