### ISSUE TITLE
Feature Request: Option to set page where the feed url redirects to as an alternative to the site's homepage

### ISSUE THREAD

**Issue by MaryMuse** [Automattic/wordpress-activitypub#576]
### What

Follow up to this discussion: https://wordpress.org/support/topic/profile-url-goes-to-home-page-on-multisite/#post-17228167

Add either a radio button that allows the choice between home page or blog page and then use the page defined under settings > reading as the home page for the feed url. Or, provide a way to choose which page of the blog the feed url will redirect to as an alternative to the home page.

### Why

For websites where the blog isn't the same as the home page, or where there isn't a link to the blog in the menu (Or it's named something else like "episodes"), this would allow the site admin to choose where the feed url would redirect to for easier access to all the posts. Thank you.

**Comment by eiland-asbl** [comment]
i have multiple post types not showing all on the front page, so i'd like to be able to redirect actiitypub visitors to my all-posts page instead of to the front page.
