### ISSUE TITLE
Typo in my display name when posts go out to federated feed

### ISSUE THREAD

**Issue by annathepiper** [Automattic/wordpress-activitypub#581]
### Quick summary

My last name is "Korra'ti", which displays correctly when you look at my posts on my blog. But when I put up a new post and the ActivityPub plugin sends it out to the Fediverse, the apostrophe in "Korra'ti". is replaced with an HTML escape code.

### Steps to reproduce

I can reproduce this in a couple different ways.

1. Just viewing my blog's profile via the Mastodon web interface
2. Seeing a new post come over my feed for my main Mastodon profile

Screenshot of what my ActivityPub profile looks like when I look at it in Mastodon's web interface:

<img width="1512" alt="Screenshot 2023-11-28 at 11 36 14 AM" src="https://github.com/Automattic/wordpress-activitypub/assets/44175637/0af21fe5-6358-4212-9a95-2ba75828b870">

Screenshot of what a new post looks like when I view it showing up in my Mastodon account's feed:

<img width="1512" alt="Screenshot 2023-11-28 at 11 39 18 AM" src="https://github.com/Automattic/wordpress-activitypub/assets/44175637/ba311413-69c4-4f2e-9785-ee923c6255d8">

Lastly, a screenshot of the bottom of a post when I look at it on my actual Wordpress site:

<img width="1512" alt="Screenshot 2023-11-28 at 11 42 03 AM" src="https://github.com/Automattic/wordpress-activitypub/assets/44175637/a72b69bb-7b5f-45fd-9256-fa8b9a44f6ea">

### What you expected to happen

Since Wordpress correctly shows "Korra'ti" on the blog itself, I expect my name to show correctly on the ActivityPub feed and in the profile page information.

### What actually happened

Instead of seeing "Angela Korra'ti" as my name, I saw "Angela Korra&#039;ti".

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

My current browser of choice is Vivaldi, typically used on a MacBook Pro running Sonoma. But I can confirm that I repro this issue if I use the Safari browser instead.

The blog I'm using the ActivityPub plugin on is Anna Plays Skyrim, which lives at: https://skyrim.annathepiper.org/

The theme I'm using on that blog is the Pro version of Ashe. As per the screenshots I've provided, the theme shows my name in all caps at the bottom of any post, but even given that, the apostrophe in Korra'ti shows up correctly.

So far what I've tried to see if I can fix this on my own is to change how my name displays in the profile for my user in Wordpress' own Edit Profile page. However, this isn't working. If I try to set it to displaying my name as "annathepiper" instead, Wordpress picks up on it, but this change is not propagated out through ActivityPub.

**Comment by annathepiper** [comment]
GAH, GitHub processed the HTML escape code I was trying to show you all in the "What actually happened" section of the text. What I meant to say there was the text version of what you see in the provided screenshots. Sorry about that!

**Comment by pfefferle** [comment]
Oh, I thought I fixed that ages ago 😳

I will check why this is still an issue, thanks for reporting!

**Comment by annathepiper** [comment]
Last I checked this issue is still reproducing. Is this still on the queue to fix?

**Comment by tomfinitely** [comment]
Bump.
