### ISSUE TITLE
Turning off tags for my feed OR using Categories instead?

### ISSUE THREAD

**Issue by annathepiper** [Automattic/wordpress-activitypub#582]
### What

I'm putting this in as a Feature Request rather than a bug, though I'm not sure if this is something ActivityPub might do already? I'd like to know if it's possible for doing either of these things in ActivityPub already, and if not, could these be implementable as a future feature?

1. Specifically exclude any tags on the post from going out on the feed
2. Instead of using tags, use categories on the post as tags instead

### Why

On my blog Anna Plays Skyrim, I use a <i>lot</i> of tags on every post. These typically refer to whatever locations I visit in the game in a play session, and I use them for ability to search posts on the site. But since I can often visit over a dozen places in one play session, the list of tags can get very long very quickly.

When I manually post to Mastodon about a new post I've just put up, I typically ONLY just use the tag "AnnaPlaysSkyrim", as well as a tag for whatever game the post is about, such as "Skyrim" or "Morrowind" or "Oblivion" or "ElderScrollsOnline". This keeps the list of tags down to a minimum, which I feel is tidier for Mastodon purposes.

Here's a screenshot of how I usually do one of these posts manually. As you can see this includes the post excerpt, two tags, the actual link to the post, and the display card:

<img width="1512" alt="Screenshot 2023-11-28 at 11 57 11 AM" src="https://github.com/Automattic/wordpress-activitypub/assets/44175637/b71e341c-ab6f-4d0f-8844-4a641edab163">

Ideally I'd like to be able to replicate this if at all possible via the ActivityPub plugin, so I would no longer have to do manual posts to Mastodon every time I put up a post. That would let me encourage people to follow the blog directly!

Is this doable? Thanks in advance!

### How

I didn't see any relevant settings in the UI I have access to.

But I could see this being done simply with a couple of optional checkboxes:

1. Exclude post tags from feed
2. Convert post categories to tags

**Comment by pfefferle** [comment]
You can fully customize what should be sent to the Fediverse. Simply go to the settings, search for "Post content", choose "Custom" and add the short-codes you want to use.

**Comment by annathepiper** [comment]
> You can fully customize what should be sent to the Fediverse. Simply go to the settings, search for "Post content", choose "Custom" and add the short-codes you want to use.

I found that part of the UI, yes. But that doesn't seem to let me explicitly turn off tags. I've tried building a custom structure there, but that still doesn't let me turn off the huge list of tags that I want to have on my post when viewed directly on the site... but NOT when the post goes out to the Fediverse.

**Comment by pfefferle** [comment]
If you do not add "[ap_hashtags]" the tags will not be included.

**Comment by pfefferle** [comment]
To test your settings, you can simply add `/activitypub` at the end of each post URL, to see the JSON file: https://skyrim.annathepiper.org/2023/11/28/test-for-activitypub-issue/activitypub/

**Comment by annathepiper** [comment]
> If you do not add "[ap_hashtags]" the tags will not be included.

Okay, thank you! I have just successfully tested this on the blog. So that covers item one on my request.

Followup then: is it possible for me to achieve item 2? I could obviously include "#AnnaPlaysSkyrim" in the custom configuration. But since this blog is a playthrough post for multiple games, sometimes I'll want to use "#Skyrim", and sometimes I'll want to do one of the other games instead. Having to change the custom setting manually every time I post defeats the entire purpose, I feel. :) Hence my question about whether it would be possible to have ActivityPub look at the categories I specify on the post, since those typically reflect what I put out into the feed when I do it manually.

**Comment by annathepiper** [comment]
> To test your settings, you can simply add `/activitypub` at the end of each post URL, to see the JSON file: https://skyrim.annathepiper.org/2023/11/28/test-for-activitypub-issue/activitypub/

Ooh, thank you for the tip.

**Comment by annathepiper** [comment]
HOLD UP I think I just answered my own question, looks like there IS a way to do this?

Finally spotted this in the full Help list, this looks like what I want:

[ap_hashcats]
The post's categories as hashtags.

Let me test this out and if this works the way I want, then I'll go ahead and close this ticket out. :D

**Comment by annathepiper** [comment]
Going ahead and closing this out, because yeah, I found the answer to my own question in the Help list for the custom settings. Thanks to all who gave tips on this post. Appreciated! :)
