### ISSUE TITLE
Profile Editor

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wordpress-activitypub#584]
The first thing most people want to do when setting up a social media profile is to edit/customize that profile. Currently the ActivityPub plugin draws its profile settings from various places in WP, and it neither helps make those connections, nor does it collect them into a single convenient place.

This project will create a consolidated UI for editing ActivityPub profiles in the plugin. It will probably also be a deluxe drop-in replacement for the Follow Me block, although that will need to be tested in practice vs creating a new Profile block.

To illustrate, here is a Mastodon profile view of my mattwiebe.blog profile

![image](https://github.com/Automattic/wordpress-activitypub/assets/195089/2ceaa9b4-754e-466e-b180-f37cbf3778f2)

It's not clear to a user where any of those settings are being drawn from. This makes sense from a WP integration perspective, but not from a user's perspective.

A few notes:

1. This can live in both Settings -> ActivityPub and also become a kind of supercharged version of the Follow Me block. The latter is currently read-only, but would become read/write and allow support for a Header image (this would effectively allow using the Follow Me block for your Site's header).
2. Header images have various problems:
    * Core header images are unsupported in block themes
    * users only use the whole-blog header image, no per-user settings
3. We should allow overriding the default `blogname` and `blogdescription` title/tagline stuff with specific ActivityPub Profile content.
4. Allow adding extra profile links

**Comment by cogdog** [comment]
This would be extremely helpful! 

Not likely related, but the odd New York, New York username style of a WordPress.com Activity pub enabled site seems clunky, speaking for my test instance @cogdoglab.wordpress.com@cogdoglab.wordpress.com  why the dupe naming?

**Comment by pfefferle** [comment]
this is because most of the platforms only show the informations before the middle "@" `@cogdoglab.wordpress.com` and we wanted to represent the blog, so the domain made a lot of sense for us.

**Comment by pfefferle** [comment]
the plugin now supports image and description editing and because inline editing is no longer a priority, I will close this for now.

@mattwiebe please re-open if you think this is still relevant!
