### ISSUE TITLE
Excerpt doesn't reliably use `the_excerpt` if set

### ISSUE THREAD

**Issue by mdingemanse** [Automattic/wordpress-activitypub#589]
### Quick summary

Despite my [earlier enthusiasm](https://github.com/Automattic/wordpress-activitypub/issues/577) and conviction that `[ap_excerpt]` uses `the_excerpt` if you set that, I can't seem to get ActivityPub to reliably recognize `the_excerpt` even when I tell it to in the settings.

My settings for post content are `custom` like so:
```
<p><strong>[ap_title]</strong></p>
[ap_excerpt]
<p>[ap_permalink type="html"]</p>
```

Example of affected post here: https://ideophone.org/interactive-repair-and-the-foundations-of-language/

The excerpt (set in wordpress, i.e. `the_excerpt` is visible in the rss at the top of https://ideophone.org/feed/ ; it is:

```<description><![CDATA[We have a new paper out in which we argue that the robustness and flexibility of human language is underpinned by a machinery of interactive repair. Repair is normally thought of as a kind of remedial procedure: just one of those things we need because we are only human. But we argue its import is more fundamental. Simply put (and oversimplifying only a bit), we argue we wouldn't have complex language if it weren't for this system of interactive repair. Paper: https://doi.org/10.1016/j.tics.2023.09.003 <a href="https://ideophone.org/interactive-repair-and-the-foundations-of-language/">```

But the actual fediverse post by @blog@ideophone.org shows up on mastodon as follows, which seems to be the default 400-character truncated version with a "read more" link:

![image](https://github.com/Automattic/wordpress-activitypub/assets/9883915/406457c2-b2ed-408d-ac2c-d9b4c76528a6)

### Steps to reproduce

1. create a post, fill out the_excerpt in a way that differs from the post itself
2. publish it
3. look at AP output 

### What you expected to happen

The AP post should use `the_excerpt` and should not truncate it at 400 characters. It should also not add a "continue reading" link, as he next element in my custom post content is the permalink anyway.

### What actually happened

The AP post creates its own excerpt from the first lines of the post and always truncates at 400 characters.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by mdingemanse** [comment]
(I say "doesn't reliably", because in my earlier testing I did on one occassion manage to get `the_excerpt` to show up in the post — but I have not been able to reproduce _that_!)

**Comment by pfefferle** [comment]
Does your theme maybe use the `excerpt_more` filter to add the "Continue Reading" link?

I can also try to check tomorrow!

**Comment by mdingemanse** [comment]
Oh I hadn't thought that a theme might interfere with those settings — will test a different one tomorrow

**Comment by kanru** [comment]
Maybe related to #558

**Comment by mdingemanse** [comment]
Confirming that with a different theme (Primer), the excerpts show up (on mastodon) as expected. 

I don't suppose there is a way to regenerate them for the few earlier posts that were affected by this?

https://ideophone.org/another-activitypub-test/
![image](https://github.com/Automattic/wordpress-activitypub/assets/9883915/13e162ff-5407-43d2-8442-d05c2409d05c)

FYI the prior theme was Reddle, not updated in 6 years. Nonetheless there might be other themes that filter `excerpt_more` for which ActivityPub would not show the expected behaviour.

**Comment by mdingemanse** [comment]
Answering my own question

> I don't suppose there is a way to regenerate them for the few earlier posts that were affected by this?

Making a slight change to the excerpt triggers a post edit on the AP side, which is rather neat.
