### ISSUE TITLE
Error message in Cronjobs

### ISSUE THREAD

**Issue by saschafoerster** [Automattic/wordpress-activitypub#592]
### Quick summary

I get this error message in my cronjobs since the last update: 
> Error: Invalid cron event 'activitypub_delete_actor_interactions'

### Steps to reproduce

Updated to latest versions of WordPress und the ActivityPub plugin

### What you expected to happen

No error message

### What actually happened

> Error: Invalid cron event 'activitypub_delete_actor_interactions'

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

> Error: Invalid cron event 'activitypub_delete_actor_interactions'

**Comment by pfefferle** [comment]
When do you receive the issue?

Can you give some more context how you have configured cronjobs?

**Comment by pfefferle** [comment]
It looks like a race condition, that two crons try to handle the events simultaneously.

**Comment by saschafoerster** [comment]
I am using a Wordpress Multisite Multinetwork installation. 
There is a manual cronjob for wordpress every 5 minutes in /etc/crontab 
This is the script I am using: 
https://gist.github.com/KingYes/37fecc169cc1be15e7dd9e6e79543467

**Comment by pfefferle** [comment]
Shouldn't this be enough `wp cron event run --due-now` ???

**Comment by saschafoerster** [comment]
I am using WordPress in a multisite and additionally in a multi-network setup: 
https://wordpress.org/plugins/wp-multi-network/ 
And as far as I know, every site needs his own cronjob, as they are all independent. 
But I will try and play around with the cronjob firing up every 10 minutes and reducing PHP execution time to 240 seconds. Maybe I had the jobs running to long and this is the reason for the "race condition".

**Comment by saschafoerster** [comment]
It seems to work now. :) Thank you for the help!
