### ISSUE TITLE
Feature Request: Allow creating AP posts for selected existing posts (e.g. blast from the past)

### ISSUE THREAD

**Issue by mdingemanse** [Automattic/wordpress-activitypub#605]
### What

As we aim to grow our audience in the Fediverse, it would be perfect if we could also occasionally create AP posts for WordPress posts that exist already.

This feature request ties in with others that ask for more control over exactly when things get posted to AP, but it is specifically about posts that data from before the moment you activated AP on your blog.

### Why

Just as in newsletters or on social media we can sometimes feature a blast from the past, or highlight content at a time when it has renewed relevance.

### How

Simplest kind of UI I can think of would be a block in the 'post' sidebar that shows the AP status of the *published* post currently being edited:
* Posted on AP [repost]
* Not yet posted on AP [post]

**Comment by pfefferle** [comment]
I am not sure how this should look like from an UI perspective, but there is already a possibility (workaround) if you simply edit an old post. It will then be send to the fediverse.

**Comment by mdingemanse** [comment]
I've tried this, and that doesn't seem to be the case. Though I am not sure how to be sure. (At least the apparition of the AP account on my mastodon instance doesn't show it.)

I have tried editing already AP-posted posts, and that _does_ update those AP posts (which is really nice). But editing an older post doesn't seem to trigger an AP post for my blog @blog@ideophone.org instance.

(Nor should it by default I think — there's probably more people like me who sometimes weed out dead links or make other random edits without the intention of triggering an AP post. But that the possibility exists is good.)

**Comment by mediaformat** [comment]
> I am not sure how this should look like from an UI perspective

I think a post table row action would be appropriate within the current WP design system.

**Comment by mdingemanse** [comment]
> if you simply edit an old post. It will then be send to the fediverse.

Is this confirmed behaviour? Because I have not managed to reproduce it.

**Comment by pfefferle** [comment]
Yes, otherwise it is an issue of the plugin or something went wrong because of your hosting or problems with other plugins.

**Comment by mdingemanse** [comment]
Returning to this issue to note that it may have simply been my own partial understanding of how AP and caching and instances work. I read in another issue that you can retrieve AP objects in a mastodon clients by searching for the original URL of the post on the blog. When I do this for posts (that I have edited), they do indeed surface, from which I conclude that they have indeed been sent to the fediverse. Good!

What threw me off is that this doesn't mean they then appear in followers' feeds or indeed in the blog feed. I.e. going to the blog profile from where I follow it on my instance, the edited posts didn't show up in the list of posts, *unless* it was a post published after I installed AP _or_ *until* I had specifically searched for the URL (and thereby made my instance retrieve it? from where?). 

Observed behaviour
- by default, the blog feed is populated only with posts published while AP is active on the wordpress blog
- edited posts exist in fedi limbo (= don't populate the blog feed) _until_ someone sees fit to retrieve them
- the edited posts have the original post date (probably just as well), so they appear chronologically in the right place

But point 2 and 3 together mean that editing posts is not really a workaround for a 'blast from the past' or 'repost' feature: the edited posts don't appear in the blog feed until specifically retrieved, and (probably because of their date) they don't appear as a new post in any followers' feeds.
