### ISSUE TITLE
Add favicon.(ico|png|svg) as fallback for site's avatar on fediverse

### ISSUE THREAD

**Issue by rghedin** [Automattic/wordpress-activitypub#607]
### What

I learned that ActivityPub (AP) plugin uses site icon to retrieve and show user avatar on fediverse. As discussed with @pfefferle [on Mastodon](https://mastodon.social/@manualdousuario/111569617138911874), I'd be happy to have a fallback to standard favicon, since I don't use site icon in my WordPress instance and, for this reason, right now its fediverse profile has a WP.com icon as avatar (`@feed@manualdousuario.net`).

### Why

I can't tell if WP site icon is widely used to justify this decision from AP plugin, but I can tell that favicon in `*.png` and specially in `*.svg` has way better quality and smaller footprint.

Here's an evidence/example (mine, in the red squircle, is a small `*.svg` file with transparency):

<img width="70" alt="Captura de Tela 2023-12-13 às 12 37 34" src="https://github.com/Automattic/wordpress-activitypub/assets/19216581/95351c57-e8c3-4ef5-97a0-427d03fb4b6f">

**Comment by pfefferle** [comment]
Would be interesting if Mastodon supports `.svg` or `.ico` as Avatars?!?

**Comment by rghedin** [comment]
Good catch, @pfefferle! Mastodon only supports `*.png`, `*.gif` and `*.jpg` for avatars.

In this case, an alternative would be fallback to `apple-touch-icon`, which is mostly (always?) a `*.png` image.

**Comment by pfefferle** [comment]
But how do I get these? I think parsing the HTML code is not really efficient, so I either need to know the plugin you use or you should use the `site_icon` feature ;)

**Comment by rghedin** [comment]
It's a standard `link rel=` on header. For example:

```html
<link rel="apple-touch-icon" href="/apple-touch-icon.png?v=4">
```

I resist using `site_icon` because it generates a lot of redundant images. Right now, my favicon structure is this:

```html
<link rel="icon" href="/favicon.ico?v=4" sizes="any"> <!-- Pretty basic, a general fallback for older browsers -->
<link rel="icon" href="/favicon.svg?v=3"> <!-- Main favicon, high quality and small footprint -->
<link rel="apple-touch-icon" href="/apple-touch-icon.png?v=4"> <!-- For Apple devices. There are other uses I'm not aware of -->
<link rel="icon" href="/favicon-192x192.png" sizes="192x192"/> <!-- For Android devices -->
```

**Comment by pfefferle** [comment]
That is not the question. The question is what generates the codes or have you added it by hand (directly in your Themes HTML)?

**Comment by rghedin** [comment]
Oh, sorry about that. I added by hand.

**Comment by pfefferle** [comment]
Then it is not possible to do it automatically, because I think parsing the HTML is not a performant thing.

So in this case you have to use some custom code and a filter to change the icon.

**Comment by rghedin** [comment]
I understand. Can you or someone help me with custom code, @pfefferle? Maybe we could add it to AP's documentation. Although I recognize this is an edge case, maybe there are more weird people like me out there 😄🥲

**Comment by pfefferle** [comment]
For the Blog User it is something like:

```PHP
add_filter( 'activitypub_activity_blog_user_object_array', function ( $array ) {
    $array['icon']['url'] = '{absolute path to your image}';
} );
```

for an author it is 

```PHP
add_filter( 'activitypub_activity_user_object_array', function ( $array ) {
    $array['icon']['url'] = '{absolute path to your image}';
} );
```

**Comment by rghedin** [comment]
Awesome! I'll try right now. Thanks, @pfefferle

**Comment by rghedin** [comment]
I tried the first snippet and, so far, it didn't work. Maybe Mastodon has an aggressive cache? It's been 3 hours. I'll wait until tomorrow (~24h) and if nothing changes, I'll let you know.

**Comment by pfefferle** [comment]
The code seem to have broken something... your profile page is not accessible atm. 🫣

**Comment by rghedin** [comment]
Oops. Weird, I can see it on `mastodon.social`, including posts published after I inserted the code.

Just in case, I just removed the code from `functions.php`.

**Comment by pfefferle** [comment]
now it works again! the infos on mastodon are cached, so they will last for quite some time even if your site might not be accessible any more. can you share the exact code you used, so that I can have a look?

**Comment by rghedin** [comment]
Sure! Here it is:

```php
add_filter( 'activitypub_activity_blog_user_object_array', function ( $array ) {
    $array['icon']['url'] = 'https://manualdousuario.net/apple-touch-icon.png';
} );
```

**Comment by pfefferle** [comment]
oops, forgot to return the array!

```PHP
add_filter( 'activitypub_activity_blog_user_object_array', function ( $array ) {
    $array['icon']['url'] = 'https://manualdousuario.net/apple-touch-icon.png';

    return $array;
} );
```

**Comment by rghedin** [comment]
Code added. Can you reach my instance?

**Comment by pfefferle** [comment]
yup, works 👍

to get the cache cleared, it helps when you publish some posts :)

**Comment by pfefferle** [comment]
I will close this for now, feel free to still comment or re-open.

**Comment by rghedin** [comment]
It worked, @pfefferle! 

<img width="600" alt="Captura de Tela 2023-12-16 às 10 57 07" src="https://github.com/Automattic/wordpress-activitypub/assets/19216581/04c8c2eb-1370-4996-be6f-62580b8e4234">

Thank you! 😊
