### ISSUE TITLE
Feature Request: Flag when permalink structure is "plain"

### ISSUE THREAD

**Issue by mexon** [Automattic/wordpress-activitypub#609]
### What

I want wordpress to flag an issue for the administrator if the plugin is installed on a system with a "plain" permalink structure.

### Why

When setting up the plugin, you can't use a permalink structure of "plain".  Anything else works.

I'm not sure exactly why that is, but I think it's because "plain" means wordpress doesn't add any rewrite rules, which means webfinger URLs don't work.  I guess that's a good reason.

So, the plugin should notice when it's installed with such a permalink structure and raise this as an issue for the administrator to fix.

**Comment by erebion** [comment]
@mexon @pfefferle Why? It worked perfectly fine with URLs such as `https://example.com/?p=42`.

**Comment by erebion** [comment]
Correction, it actually still does work. I cannot find the issue.

**Comment by pfefferle** [comment]
Have you added the mod rewrite rules to the htaccess by hand?
