### ISSUE TITLE
High CPU Usage and Excessive Server Processes Caused by ActivityPub Plugin

### ISSUE THREAD

**Issue by lautfunk** [Automattic/wordpress-activitypub#611]
### Quick summary

I am reaching out to report a critical issue I've encountered with your ActivityPub plugin on my WordPress installation. After thorough observation and analysis, I have discovered that the plugin is causing unusually high CPU usage on my server and generating an excessive number of processes. This has led to a significant degradation in the performance of my website.

### Steps to reproduce

Occurs every 5 to 10 minutes.

### What you expected to happen

Run

### What actually happened

Not reachable.

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by alecmuffett** [comment]
I don't have a fix for this, but I can confirm that I was suffering it on
my standalone WordPress instance on an old RaspberryPi running an older
version of PHP, where I was using the Friends plugin and following a couple
of users who had very noisy and frequently updated feeds. All of the CPU
burning was attributable to these two users who I was following, I am not
sure why other than the observations that they both had very frequently
updated timelines..

**Comment by pfefferle** [comment]
I am sorry, but ActivityPub is a very noise protocol in general, that means every time one of your posts will be shared it could cause quite some http traffic.

**Comment by pfefferle** [comment]
The plugin itself does not do a lot more than sending new posts to the fediverse and receiving/processing reactions.

**Comment by pfefferle** [comment]
An interesting read that explains the general problem really good https://ar.al/2022/11/09/is-the-fediverse-about-to-get-fryed-or-why-every-toot-is-also-a-potential-denial-of-service-attack/

**Comment by janboddez** [comment]
Probably related: #522.

**Comment by EricaHargreave** [comment]
Same thing is happening on my sites. Frustrating as I like the plugin otherwise.
