### ISSUE TITLE
Posts pictures added and subsequently removed from the post

### ISSUE THREAD

**Issue by zackbatist** [Automattic/wordpress-activitypub#612]
### Quick summary

I uploaded images to the media library and decided I did not want to use one of them. I removed the image from the post. When previewing and publishing the post, the image was not publicly present on the blog. However, it *was* visible to subscribed mastodon users. Same issue exists when using the Share on Mastodon plugin https://wordpress.org/plugins/share-on-mastodon/ Had to entirely delete the image from the media library to resolve the issue.

### Steps to reproduce

1. Upload images to media library
2. Include images in the blog post
3. Preview post
4. Remove one of the images
5. Publish the post
6. Observe that the un-used image is present in my social media feed
7. Delete the image from the media library
9. Re-share

### What you expected to happen

I expected the publish process to share only images I explicitly stipulate in the blog post.

### What actually happened

Images that I did not want to include in the post were shared.

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by pfefferle** [comment]
This is only a problem if you do not use the Block-Editor, see #553 for some context.

**Comment by zackbatist** [comment]
Ah, good to know. I understand that this is not on the roadmap since classic editor is no longer officially supported, but so many people still use it so it seems like core functionality under realistic circumstances.
