### ISSUE TITLE
Blank page after activating Activitypub, debug with PHP Fatal error:  Uncaught Error: Call to undefined function Activitypub\register_post_meta() 

### ISSUE THREAD

**Issue by okingfisher** [Automattic/wordpress-activitypub#620]
### Quick summary

ActivityPub installs correctly, but when trying to activate I get a blank page.

### Steps to reproduce

1. Install ActivityPub
2. Activate plugin
3. Blank page

### What you expected to happen

Get a working ActivityPub plugin. First attempt in this blog.

### What actually happened

Blank page. Above debug log.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

WP 4.9.5, PHP 7, Apache 2 on Ubuntu Linux 18.04.6 LTS (I have my own server with Wordpress).
Activating the debug mode, I get this error log:
[23-Dec-2023 18:51:00 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Activitypub\register_post_meta() in /data2/www/wordpress/wp-content/plugins/activitypub/includes/class-activitypub.php:361
Stack trace:
#0 /data2/www/wordpress/wp-content/plugins/activitypub/includes/class-activitypub.php(43): Activitypub\Activitypub::register_post_types()
#1 /usr/share/wordpress/wp-includes/class-wp-hook.php(286): Activitypub\Activitypub::init('')
#2 /usr/share/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /usr/share/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /usr/share/wordpress/wp-settings.php(450): do_action('init')
#5 /etc/wordpress/config-reprobio.unileon.es.php(108): require_once('/usr/share/word...')
#6 /usr/share/wordpress/wp-config.php(19): require_once('/etc/wordpress/...')
#7 /usr/share/wordpress/wp-load.php(37): require_once('/usr/share/word...')
#8 /usr/share/wordpress/wp-admin/admin.php(31): require_once('/usr/share/word...')
#9 /usr/share/wordpress/wp-admin/plugins.php(10 in /data2/www/wordpress/wp-content/plugins/activitypub/includes/class-activitypub.php on line 361

**Comment by pfefferle** [comment]
I am sorry, we missed to update the requirements of the Plugin, but it does no longer work with WP 4.9.5!

`register_post_meta` was introduced in WP 4.9.8 https://github.com/WordPress/wordpress-develop/blob/6.4/src/wp-includes/post.php#L2585-L2589

I will check what the minimum required version is and will update the "WordPress Version" setting.

**Comment by okingfisher** [comment]
Thank you! I suppossed that was the reason, but it seemed odd that it allowed me to installing the plugin. I will wait until that version is in the repository for upgrading.
