### ISSUE TITLE
Follow timestamp gets overwritten with last update timestamp

### ISSUE THREAD

**Issue by frank42hh** [Automattic/wordpress-activitypub#621]
### Quick summary

As the title says, the timestamp for "followed" is the same as the timestamp for "last updated" (or wrongly displayed?).  See screenshot.  I (the entry at the bottom) followed right after installing about a week before, but now it states that I follow since yesterday only. This "reset" happened for all entries, so it's impossible now to check out when people started following.

### Steps to reproduce

- install plugin
- wait some days for some followers
- review followers tab

### What you expected to happen

followed and last updated shouldn't be the same.

### What actually happened

followed and last updated are the same

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

![Screenshot 2023-12-24 130503](https://github.com/Automattic/wordpress-activitypub/assets/17932878/2a7dd7a8-cc3a-45aa-a262-6fe6663d8a83)

Wordpress version: 6.4.2
Plugin version: 1.3.0

**Comment by janboddez** [comment]
I think what _may_ be happening is that when `wp_insert_post()` is called without a `post_date` or `post_modified` argument, the that the default post date of `000-00-00 00:00:00` is used, which then gets updated to the _current time_ by `wp_resolve_post_date()`. `post_modified` always gets updated to the current time (for updates, it seems this part works as intended).

So I would first attempt to call `wp_insert_post()` _with_ the post's datetime. I _think_ right now the code incorrectly assumes `post_date` will stay the same if omitted ...

**Comment by janboddez** [comment]
Thought I'd fixed it here https://github.com/Automattic/wordpress-activitypub/commit/636d67e20a49b29076d74889db06e11d53ea35ef#diff-8ba3308498bd0ff0c8c5cbfef3cd8fe811ab16c58e829755c3e9a77eeb6cb88bR174 but this sets "followed" to the date the follower account was created. Guess I shouldn't be using `$this->get_published()` but instead get the actual `post_date` column from the `ap_follower` post object.
