### ISSUE TITLE
Feature Request: `<link rel="alternate" type="application/activity+json">`

### ISSUE THREAD

**Issue by saschanaz** [Automattic/wordpress-activitypub#626]
### What

Consider adding the link rel=alternate element as you can see in Mastodon/Misskey, e.g. in https://fosstodon.org/@krosylight:

```html
<link href='https://fosstodon.org/@krosylight.rss' rel='alternate' type='application/rss+xml'>
<link href='https://fosstodon.org/users/krosylight' rel='alternate' type='application/activity+json'>
```

### Why

This element advertises that the page can be read in ActivityPub form too. Browser extensions can detect it and reopen it on Mastodon for example.

**Comment by pfefferle** [comment]
I thought about that a lot and wanted to write a FEP to use rel-alternate as alternative to content negotiation!

My issue with the current implementations is that it still needs conneg, but I would assume that it should work similar to the RSS version (you referenced) instead.

From the HTML spec:

> If the alternate keyword is used with the type attribute, it indicates that the referenced document is a reformulation of the current document in the specified format.

So it should be more like 

```HTML
<link href='https://fosstodon.org/@krosylight.json' rel='alternate' type='application/activity+json'>
```

instead!

**Comment by pfefferle** [comment]
See https://github.com/mastodon/mastodon/issues/22306

**Comment by saschanaz** [comment]
Have you written an RFP? 👀
