### ISSUE TITLE
Website Zustand falsche Fehlermeldung: "Der WebFinger-Endpoint is nicht erreichbar"

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#627]
### Quick summary

Ich bekomme diese Meldung angezeigt:
<img width="880" alt="Bildschirmfoto 2024-01-01 um 10 43 52" src="https://github.com/Automattic/wordpress-activitypub/assets/2017105/e12cd312-6e46-478a-8279-c2fc734c6268">

Der WebFinger-Endpunkt `https://jascha.wtf/.well-known/webfinger?resource=acct:jascha.wtf@jascha.wtf` ist aber sehr gut zu [erreichen](https://jascha.wtf/.well-known/webfinger?resource=acct:jascha.wtf@jascha.wtf).

Was kann ich tun, um das weiter zu debuggen?

### Steps to reproduce

Ich habe keinen

### What you expected to happen

Das die Fehlermeldung nicht da ist

### What actually happened

Die Fehlermeldung ist da.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
Ist das dauerhaft? ich hab manchmal auch glitches mit verschiedenen "Website-Zustand" checks...

**Comment by jaschaurbach** [comment]
Ich hab das jetzt seit Tagen durchgehend.

**Comment by pfefferle** [comment]
If you are sure the plugin works properly, you can disable the Health Check completely with:

`remove_action( 'init', array( '\Activitypub\Health_Check', 'init' ) );`

**Comment by jaschaurbach** [comment]
Ich bin leider nicht sicher - also die Posts erscheinen im Fediverse aber die meisten Menschen interagieren via bridgy, da mein Account eine größerer Reichweite im Fediverse hat als mein Blog. 

Wo kann ich denn nachschauen, was angeblich zu dem Fehler führt? Dann kann ich ein wenig debuggen

**Comment by pfefferle** [comment]
Ah, dann schau ichs mir mal an!

**Comment by iamwebrocker** [comment]
ich habe den Effekt jetzt auch. k.A., ob das durch die 2.0 kam oder schon vorher da war (ich gucke nicht so oft auf diese Zustandsdinger). Wäre aber auch interessiert, ob/wie man checken kann, ob der webfinger angefasst werden kann

**Comment by pfefferle** [comment]
Zum testen, einfach die ID in das suchfeld hier rein packen: https://webfinger.net/

**Comment by iamwebrocker** [comment]
@pfefferle danke, da kommt was sinnvolles zurück.

**Comment by jaschaurbach** [comment]
Auch nach dem Update auf 2.0 bekomme ich die Meldung. Offensichtlich funktioniert Webfinger bei mir und ich möchte ungern einen Fehlermeldung per Code entfernen - denn was ist, wenn wirklich mal was kaputt ist?

Wenn ich irgendwie helfen kann - sag Bescheid - gerne auch per Mail oder anderen Wegen.

**Comment by iamwebrocker** [comment]
Hi, ich habe gerade den aktuellen Master runtergeladen und aktiviert; der Effekt ist immer noch da.
Aber, was mir auffällt: Im Bericht des Healthcheck steht, dass es 

![grafik](https://github.com/Automattic/wordpress-activitypub/assets/1223080/a023f4ee-d551-42cb-9090-e50f3df2403d)

die Autor-URL benutzt (versucht?) des gerade angemeldeten Admin-Users. Ich habe aber ein Blog-weites Setting, also gibt es diese Autoren-URL nicht für das Activitypub. Könnte das die Erklärung sein?

**Comment by pfefferle** [comment]
Was habt ihr denn wieder für ein wildes setup... ist der benutzer unter dem ihr euch immer einloggt nicht für ActivityPub aktiviert oder einfach nur anders blockiert? (kann keine artikel schreiben z.B.)

**Comment by pfefferle** [comment]
@iamwebrocker @jaschaurbach könnt ihr is mit dem aktuellen master nochmal probieren?

**Comment by iamwebrocker** [comment]
> Was habt ihr denn wieder für ein wildes setup... ist der benutzer unter dem ihr euch immer einloggt nicht für ActivityPub aktiviert oder einfach nur anders blockiert? (kann keine artikel schreiben z.B.)

Mein Adminuser schreibt keine Beiträge, und mein everyday User hat keine Adminrechte, sieht also den Healthcheck nicht :-)

**Comment by pfefferle** [comment]
geht mit der nächsten version live! ^^
