### ISSUE TITLE
looking at an article returns JSON

### ISSUE THREAD

**Issue by YourAutisticLife** [Automattic/wordpress-activitypub#641]
### Quick summary

JSON is returned instead of the HTML content of the article.

This happens both in 1.3.0 and 2.0.0.

### Steps to reproduce

I don't know how to create an article that results in JSON being returned.

### What you expected to happen

I expected to see the article rendered as HTML.

### What actually happened

Look at this page:

https://www.yourautisticlife.com/2024/01/08/regular-individuals-foot/

Or this page:

https://www.yourautisticlife.com/2024/01/08/stimming-is-life-007/

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

I'm assuming that this plugin is the problem because I'm seeing JSON that looks like ActivityPub,., but I'm not sure.

Help with tracking down the problem is appreciated. I can modify the code, but I'm no PHP specialist.

I've tried in both Firefox and Chrome. I get the same thing.

**Comment by pfefferle** [comment]
This happens if your caching solution does not support content-negotiation. What caching plugin/system do you use?

**Comment by YourAutisticLife** [comment]
I'm running my site naked right now, but earlier I had some caching plugins that I installed, but then I uninstalled. Other than that, nginx is doing caching the same way it used to.

**Comment by YourAutisticLife** [comment]
Hmm... I went ahead and deleted nginx's disk cache, and it seems to be fixed right now. I'm going to close this. Thanks for the help.
