### ISSUE TITLE
Federation of comments does not work as expected

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#642]
### Quick summary

I answered a comment from the fediverse on my blog. The comment is here: https://jascha.wtf/schoeffe-arbeitszeit-und-entschaedigung/#comment-2977

The comment is indeed published in the fediverse but it misses the reference:

<img width="335" alt="Bildschirmfoto 2024-01-09 um 20 55 17" src="https://github.com/Automattic/wordpress-activitypub/assets/2017105/cf5874f0-6db6-4c20-8ea0-8d5ca1928104">

### Steps to reproduce

Answer to a fediverse comment from your blog 

### What you expected to happen

the answer gets posted and has a reference to the post answering to.

### What actually happened

it has no reference nor mention.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
Was the comment you replied to before the update to 2.0.0?

**Comment by pfefferle** [comment]
I added a comment to https://jascha.wtf/gedicht-slash-slash/ from Mastodon, can you reply to it?

**Comment by jaschaurbach** [comment]
Ah yes, it worked! Thanks for testing with me!

This issue now can be closed!

![image](https://github.com/Automattic/wordpress-activitypub/assets/2017105/a1e2be58-4c17-454f-a9df-a1189c7e3afd)
