### ISSUE TITLE
Option to set visibility of answers to comment

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#644]
### What

I would like to be able to set the visibility of answers to „not listed“ in general and be able to set it for every comment before posting it on demand.

### Why

Answering to many comments would clutter the timeline of folks just following the website. 

The feature of sending answers to comments back to the fediverse is great but may be not usable in cases with a hugh ammount of interactions.

Sometimes if a comment from the fediverse gets big traction one might want to answer public in the timeline.

**Comment by janboddez** [comment]
> I would like to be able to set the visibility of answers to „not listed“ in general and be able to set it for every comment before posting it on demand.

Ooh, this sounds like something I may want to add to my add-on plugin.
