### ISSUE TITLE
Fediverse replies to bidirectional comments get “blackholed”

### ISSUE THREAD

**Issue by Oblomov** [Automattic/wordpress-activitypub#648]
### Quick summary

We're seeing a peculiar issue with the bidirectional commenting supported by the latest version of the WordPress plugin: (some) Mastodon comments to a blog comment to a previous Mastodon comment fail to appear in the proper place, breaking the chain post > Mastodon comment > blog comment > Mastodon comment.

Apparently the second Mastodon comment gets assigned blog-side to the “main page” rather than the original comment, “disappearing” blog-side, since the main page generally doesn't actually support comments itself.

An example of this in action can be seen here

https://www.matteozenatti.net/2024/01/10/delle-laudi-della-musica-09/

vs

https://sociale.network/@oblomov/111731248300928414

This may or may not be related to #638

### Steps to reproduce

1. Write a post on the blog.
2. Comment from the Fediverse.
3. Reply to the Fediverse comment from the blog
4. Reply to the blog comment from the Fediverse

### What you expected to happen

The reply at step 4. appears in the comment thread starting from 2., on the blog.

### What actually happened

The threading seems to work correctly Fediverse-side, but not blog-side.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Oblomov** [comment]
The blog owner confirmed that he could see the comment, approve it, even reply to it, but it was attached to the wrong object (main page rather than the blog comment it was a reply to).

**Comment by pfefferle** [comment]
Does he also use webmentions in combination with fed.brid.gy?

**Comment by matteozenatti** [comment]
Hi, I'm the owner. I did't use webmentions neither fed.brid.gy. Now I installed Webmentions plugin for wordpress. But I don't get what I'd do with fed.brid.gy

**Comment by Oblomov** [comment]
No.

**Comment by matteozenatti** [comment]
Edit: i got wrong what I read before, so now I disinstalled Webmentions and can answer: no, i don't use webmentions with fed.brid.gy

**Comment by matteozenatti** [comment]
Ok, today same issue: an answer to an answer gets this 
"Un nuovo commento all'articolo "Main Page" è in attesa della tua approvazione https://www.matteozenatti.net/": it address to the home page, and not to the page of the post to comment.
