### ISSUE TITLE
Comment Edits aren’t federating

### ISSUE THREAD

**Issue by mediaformat** [Automattic/wordpress-activitypub#649]
### Quick summary

See https://mediaformat.org/wordress-activitypub/signature-verification-in-wordpress/#comment-752 on the web vs in another Fediverse app

### Steps to reproduce

1. Reply to your own blog post
2. Edit the comment and save

### What you expected to happen

Comments should be editable

### What actually happened

Comment edit not federating

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by janboddez** [comment]
I believe I saw this, too. Didn't dig any further because I've been changing so many things at once. :-D

**Comment by janboddez** [comment]
Did a tiny bit of digging. The activity gets sent out, servers respond with 200 or 202. (That doesn't necessarily mean anything, they typically respond this way.)

When I pull up the comment's ActivityPub representation in my browser (using `?activitypub&c=id`), it shows the updated version just fine.

It _looks_ like edits for posts still work.

I _don't_ see a lot of incoming GET requests in my server logs, like I do after a post gets boosted or so.

I guess that means that Mastodon and other AP servers verify the edit using a public key they've cached someplace (this part of AP is still a bit of a mystery to me).

So it looks like something in the update activity, be it a signature or an ID or another kind of property that Mastodon parses or expects to be there ... is "wrong"?

**Comment by janboddez** [comment]
Another thing: when I search for the comment I used to test (https://jan.boddez.net/?c=1874), in Mastodon, it finds it OK (e.g., https://indieweb.social/@jan@jan.boddez.net/111725404913235167).

**But** when I hover over Mastodon's "Open original page" link for the comment it shows me, the address is https://jan.boddez.net/notes/363e425922#comment-1874 (which is correct, but that URL's _AP representation_ will not return the _comment_, as pointed out before).

(I don't know if it could mean anything.)

**Comment by janboddez** [comment]
Another thing I _think_ I saw (but I don't know if it means anything, I'm guessing it doesn't), is that comments aren't included in a user's outbox ...

**Comment by pfefferle** [comment]
Ah, I think it's the issue that the updated date does not differ from the published date?!? Will check that tomorrow!

**Comment by mediaformat** [comment]
Yes, there MUST be a newer updated date!

**Comment by mediaformat** [comment]
Also while we're on the topic of comment edits, I do think Edits should be transparent to users.

My original PR used a filter to mention the Edit time/date.

I think we may also need a site setting for sending remote Edits back to moderation.

**Comment by pfefferle** [comment]
@mediaformat do you want to make a PR to re-add the "mention the Edit time/date."
