### ISSUE TITLE
Add Option to add external Fediverse Account into "follow me"-block

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#653]
### What

I would love to make a follow me block pointing to my personal account. 

### Why

Have a full list of accounts I maintain to follow and all have the same awesome design and it just looks nice :)

### How

The idea is to have an extra option "Follow external account" and enter the user and domain. Of course the account needs to support web finger.

Then the avatar gets loaded from the instance and cached locally (update every week or something - have a setting for that in the plugin settings) and after hit on the follow button the same workflow as with blog users starts.

**Comment by pfefferle** [comment]
I am already working on that, thanks!

**Comment by jaschaurbach** [comment]
Why arte you that awesome?!?

**Comment by pfefferle** [comment]
If I would be "that awesome" this issue wouldn't even exist :joy:

**Comment by pfefferle** [comment]
And btw. I commented on the wrong ticket 😂

I am fixing the comment stuff 🤦
