### ISSUE TITLE
Show likes and reposts below post

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#655]
### What

At the moment I am using the web mention plugin to show likes and reposts of fediverse posting I made with my non-blog-account and using bird.gy to show the likes and reposts of THAT postings. 

I would love to see the reposts and likes on the postings on the original posting as well

### Why

Because now I do not know the number nor does anyone else

### How

Make use of the webmention plugin (to keep compatibility) and add to the piles of Likes and Reposts which are already created by the webmention plugin :) 

<img width="743" alt="pile" src="https://github.com/Automattic/wordpress-activitypub/assets/2017105/8b111e13-49c3-4d7d-9a8a-20480ab3f3f1">

For the basic comment fields the fields could be filled as follows:
<img width="841" alt="basic fields" src="https://github.com/Automattic/wordpress-activitypub/assets/2017105/593b6f19-67de-4a73-bd3f-4c5a96ab6fe1">

Name: Name of the account
E-Mail: empty
URL: URL to the profile
Content: Fediverse Response

For the webmention part I think the same fields could be used:
<img width="1242" alt="webmentionfields" src="https://github.com/Automattic/wordpress-activitypub/assets/2017105/f0dfe2d1-6977-42fb-92e0-db02c17b6c0a">

Comment Type: Like / Repost
Target: $POSTURL
Source: I think this one can stay empty (but I don to know if the webmention plugin works without it)
Avatar: Avatar of the account posting/liking
Canonical URL: Same as Source

**Comment by lencioni** [comment]
I think this may be a duplicate of https://github.com/Automattic/wordpress-activitypub/issues/235

**Comment by jaschaurbach** [comment]
Indeed it is. I just forgot about my original request -.-
