### ISSUE TITLE
URL of comments does not resolve to the comment's ActivityPub object

### ISSUE THREAD

**Issue by Menrath** [Automattic/wordpress-activitypub#658]
### Quick summary

The `url` of a reply to a comment (or just a top-level comment by an user of the same WordPress instance) looks for example like this: `https://notiz.blog/2024/01/10/hier-bloggt-der-chef-noch-selbst/#comment-1859840`

Querying this URL via the header Accept: `application/activity+json` does not return the comment object but the WordPress post the comment belongs to instead.

This makes it currently impossible to reply to author-comments that are not yet cached on my instance (because someone on my instance followed that actor who created the comment already).

### Steps to reproduce

```bash
curl --request GET \
  --url 'https://notiz.blog/2024/01/10/hier-bloggt-der-chef-noch-selbst/#comment-1859840' \
  --header 'Accept: application/activity+json'
```

### What you expected to happen

The post appers.

### What actually happened

The comment should appears.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Example:
1. Have an Mastodon Account on `mastodon.example`
2. Someone of your followers boosts a WordPress post of `blog@wordpress.example`
3. I checkout that post via visiting the WordPress site of wordpress.example
4. I want to respond to a comment made by the author
5. I try to copy the comments permalink
6. Paste it into the Mastodon search field
7. Receive the WordPress post not the comment
8. Inspect it and only see the replies already known to my instance

**Comment by mediaformat** [comment]
Part of this is a Mastodon UX issue, the other part is the lack of content-negotiation for comments.

For mastodon where browsing and sharing a status uses the `url` instead of the object `id`.

And since WP has no core comment permalink beyond the fragment url (post_url#comment_id), there is no possible content negotiation. 

So comment's ActivityPub `id` are only available via a rest endpoint.

**Comment by pfefferle** [comment]
The quick fix would be to use the ID also for the URL!?!

**Comment by Menrath** [comment]
I think that this should be possible! Or using another redirect with a custom pretty comment url (only for federated comments).

**Comment by pfefferle** [comment]
Because it always will "only" redirect to the Hash version, if the `Accept` header is not `application/json+activity`, I personally wouldn't use a pretty permalink.

**Comment by Menrath** [comment]
> Because it always will "only" redirect to the Hash version, if the `Accept` header is not `application/json+activity`, I personally wouldn't use a pretty permalink.

Totally O.K., I just wanted to throw in all alternatives that came to my mind :)
