### ISSUE TITLE
Feature Request: AC follow, boost, reply, ... template tags

### ISSUE THREAD

**Issue by eiland-asbl** [Automattic/wordpress-activitypub#659]
### What

An example author-template theme file, or template tags, to provide functional "follow", boost, reply, favorite and bookmark functionalities 

### Why

I would like my visitors to have a full mastodon experience, with options to interact

### How

![image](https://github.com/Automattic/wordpress-activitypub/assets/5505151/7d34f314-8b03-42ee-896f-a083d0bdeedf)

**Comment by pfefferle** [comment]
Have you seen the blocks for the block editor and FSE?

**Comment by eiland-asbl** [comment]
Oh, only just now,  but blocks only work on content, not on templates, right?
Or can i already add the follow me block to the author page?

**Comment by pfefferle** [comment]
It depends on the theme you use, it works nice on themes that support "Full Site Editing"

**Comment by eiland-asbl** [comment]
Ah, call me old fashioned.... would it be hard to include template tags?
