### ISSUE TITLE
Feature Request: Update Readme to include the Users > Followers page

### ISSUE THREAD

**Issue by shawnhooper** [Automattic/wordpress-activitypub#660]
### What

I would like to see the readme for the plugin to include documentation about the Followers page that is created in **Settings > Users**.  

### Why

It isn't obvious how to see who's following you, in my opinion.  I'd first looked through the Settings tab for the plugin, then ended up creating a page with the Followers block on it before someone pointed out that it was available under the Users tab.

**Comment by eiland-asbl** [comment]
Are those followers of only the current user, or from the blog user, or for all users? And how to see followers of other blog users?
