### ISSUE TITLE
"Please set a permalink structure" is an incomprehensible message when freshly installed

### ISSUE THREAD

**Issue by jernst** [Automattic/wordpress-activitypub#664]
### What

Fresh install of WordPress with the AP plugin. Logging in the first time, I'm greeted by message "You are using the ActivityPub plugin without setting a permalink structure. This will prevent ActivityPub from working. Please set a permalink structure." with no obvious hint what to do.

### Why

This is off-putting and probably hinders adoption.

Suggestion:
* Set the correct default for permalink structure for new installs, or
* at least provide a link from the error message to the settings where one can make the right selection

Also, the Permalink Settings page says, before I make any change, that I have a permalink structure called "Plain". Maybe the error message could be clarified. Right now it implies there is "None" not "Plain".

**Comment by pfefferle** [comment]
Hey @jernst nice that you tried out the plugin ☺️

I would not `Set the correct default for permalink structure for new installs` because, based on the server setup (of mod-rewrite is not installed for example) this might break WordPress, but I agree that we should provide some more guidance!
