### ISSUE TITLE
Installing Woocommerce automatically posts content of new pages

### ISSUE THREAD

**Issue by zkg** [Automattic/wordpress-activitypub#665]
### Quick summary

The default settings of ActivityPub have support enabled for posts and pages.
Installing Woocommerce creates new pages.

### Steps to reproduce

1. Install activitypub
2. Install Woocommerce
3. Create a product 

### What you expected to happen

I was not expecting any action on activitypub's side.

### What actually happened

Posts on the fediverse were created with the content of the cart page, the login page, and the checkout page.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

This issue would not be a big deal if there was an easy way to control the content generated on the Fediverse. An entity-level toggle to publish/unpublish would do the trick.

**Comment by pfefferle** [comment]
@zkg Do you think it helps to disable the federation of pages by default?

**Comment by zkg** [comment]
I could be wrong, but I struggle to see a use case where someone is creating many pages -more static entities in WordPress philosophy- and needs them federated. It's great to have that option, but yes, I would disable it by default.
