### ISSUE TITLE
User Avatar Not Updated

### ISSUE THREAD

**Issue by cibersheep** [Automattic/wordpress-activitypub#669]
### Quick summary

The avatar of the Wordpress user is not updated in Mastodon after being followed

### Steps to reproduce

1. Assaign an avatar to the Wordpress user via Gravatar
2. Follow Wordpress user in Mastodon
3. Upload a new avatar for the user in Gravatar. Set it as default
4. Update user info in Mastdon

### What you expected to happen

Avatar is updated to the current Gravatar picture

### What actually happened

In Mastdon, you still see the first avatar from Gravatar
Unfollow and refollow doesn't make any difference

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

**Comment by pfefferle** [comment]
The problem with that is, that WordPress does not really know if the Avatar is updated 🤔

**Comment by janboddez** [comment]
As a (temporary?) workaround, could you not subsequently also _update your user profile_ (like change your bio, or even just press the Update button, in WordPress, after having updated the Gravatar image)?

Wouldn't that cause WordPress to push an update to followers' servers?

Not sure if that'd get those servers to (re-)download the image ... Could still be Mastodon is like, "Meh, same URL, don't need to check if maybe the image itself has changed." (If so, that would be a Mastodon issue.)

A "better" solution _could_ be to have WordPress check (like, once a day or so) if the image hadn't changed (by downloading it and compare the [binary] data or a hash thereof or something with an earlier version).

Another possible solution _might_ be to use a local avatar, maybe? Through a plugin? Although I'm not sure if updating it _would_ trigger an Update request. I guess it'd depend on _where_ you set it, too.

**Comment by cibersheep** [comment]
> As a (temporary?) workaround, could you not subsequently also _update your user profile_ (like change your bio, or even just press the Update button, in WordPress, after having updated the Gravatar image)?

Thanks for the suggestion. I have tested with same results.

I searched for the user in a private tab of Firefox. It shows old avatar

![imatge](https://github.com/Automattic/wordpress-activitypub/assets/6640041/5d7bd9b2-6ca1-4057-8ce7-bb8990003240)

User in WordPress has new one. I have updated the bio yesterday for the test

![imatge](https://github.com/Automattic/wordpress-activitypub/assets/6640041/0207607e-24a2-41c1-afa3-f71df26b3c67)

**Comment by pfefferle** [comment]
But the Bio was updated on Mastodon?

**Comment by cibersheep** [comment]
Yes. It did (instantly)
