### ISSUE TITLE
Comments being published on blog's Mastodon profile

### ISSUE THREAD

**Issue by rghedin** [Automattic/wordpress-activitypub#671]
### Quick summary

After updating to 2.0.1 (I skipped 2.0), new comments in WordPress, from registered users without `publish_posts` permission), are being cross-posted to blog's profile on fediverse. See: https://mastodon.social/@feed@manualdousuario.net

### Steps to reproduce

1. Register a new user as subscriber;
2. Activate blog profile in ActivityPub plugin settings (authors profiles are deactivated);
3. Registered user posts a comment;
4. Comment appear as a comment made by the blog's profile on Mastodon.

### What you expected to happen

WordPress comments from nobody shouldn't appear on blog's profile on Mastodon.

### What actually happened

WordPress comments by registered users appear on Mastodon as replies by blog's profile.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by mediaformat** [comment]
Thanks, this is indeed a bug!

I was able to find the comment:
https://manualdousuario.net/mesa-de-trabalho-felipe-souza/comment-page-1/#comment-237679

![image](https://github.com/Automattic/wordpress-activitypub/assets/2895351/f618a8cb-0b81-4c34-9ff1-30e5822fcfba)

**Comment by pfefferle** [comment]
Ah! this only works if you only have enabled the blog-user. Thanks for the report!

**Comment by rghedin** [comment]
@pfefferle I'm sorry if I misunderstood you, but in my case it's not working as intended, right?

**Comment by pfefferle** [comment]
Yes, I just needed an excuse why I hadn't thought of it myself yet 🫣

**Comment by janboddez** [comment]
Sorry to bring this up _again_, but wouldn't it make sense this somehow fit into a "better" post/comment "validation" strategy? See also #631 where I was able to federate a private post, simply because federation was delayed (in this case, due to me having WP Cron disabled, but there are more scenarios where federation happens either "too late," or even "[too soon](https://github.com/Automattic/wordpress-activitypub/issues/668)"). 😬

**Comment by pfefferle** [comment]
sure, and I am currently working on it, but in case of the comments it is not trivial :(

**Comment by janboddez** [comment]
Something like an `is_post_valid()` helper function or so, that checks whether the post or comment author still exists, is allowed to publish posts, the post (if it's a post) is really still public at the time of federation, or the comment (if it's a comment) still approved? 

And then it should probably be run/checked against not only when scheduling but also right before actual federation.

**Comment by janboddez** [comment]
In my crossposting plugin, I basically do this: https://github.com/janboddez/share-on-mastodon/blob/3d26953f286e068edfb4d396c2a74f8c8aa27cd4/includes/class-post-handler.php#L476-L490

In my _Webmention_ plugin, I'm a bit more pragmatic and only check if a comment was (and still is!) approved: https://github.com/janboddez/indieblocks/blob/4708d4a53e8c43277c61a3bd1139e46f43355d96/includes/class-webmention-sender.php#L152-L167

Not saying this is how it should be done, but it's something.

For webmentions, I'm not worried if me approving someone else's comment triggers a webmention. Most receiving servers will probably not even know how to parse comments and simply ignore the mention.

In the case of ActivityPub, I'd probably also not want _someone else_ to be able to "use" my site to interact with the Fediverse.

**Comment by janboddez** [comment]
Well, I was saying, I liked the idea of having the Transformer classes return an error whenever they "encounter" _anything_ that should not be published.

**Comment by pfefferle** [comment]
I am doing nearly the same validation, but maybe at the wrong end (before the scheduling).

I would like to lock myself in for a week and build a real outbox. that would help with scheduling, chunk-processing and at the same time I could also rebuild the validation.

**Comment by rghedin** [comment]
@pfefferle, I have a doubt related to this bug. If I enable blog-users in my blog, is there a way for them to associate their own fediverse accounts so that when they comment in my blog, the comment is published on their fediverse account, instead of `@profile@myblog.com`?

An example: I have `myblog.com` and enable ActivityPub plugin and blog-users on it. A reader of mine, who has an account `reader1` in my blog and is on Mastodon as `@user1@mastodon.social`, associate this account to their `reader1` profile. When they publishes a comment in my blog logged in as `reader1`, this comment appears on fediverse as published by `@user1@mastodon.social`, instead of `@reader1@myblog.com`.

Is that available, or could be a future feature?

**Comment by pfefferle** [comment]
This can not be done using ActivityPub! You can not post in the name of a different account, this would be a security problem! To do that you have to use the Mastodon API!

**Comment by rghedin** [comment]
Yeap, I was wondering if ActivityPub plugin could offer an option to link blog accounts to profiles in a different server/instance. It seems (at first thought) as a safe, orderly way to achieve this.

**Comment by rghedin** [comment]
Hmmm, I'm having trouble to picture this. This way, they wouldn't comment in my blog (using the WordPress form)? I see WordPress as a main actor in this scenario, and fediverse as an accessory (something like [POSSE](https://indieweb.org/POSSE), with WordPress as the place to "publish once").

**Comment by pfefferle** [comment]
But this way (POSSE) it would not be possible to comment on the blog as user `@reader1@myblog.com` and to federate it as user `@user1@mastodon.social`.

**Comment by rghedin** [comment]
Yeah, it would skip entirely the @reader1@myblog.com and establish a direct connection of `reader1`'s WordPress account to their fediverse account. Is this scenario out of the plugin's scope? Because it sounds amazing. Add a new field to WordPress profile ("fediverse handle"), plus a checkbox to repost comments there, and we're good to go.

I say this with utmost respect for your awesome work, but current implementation for blog-users creates a limbo, with new accounts created for each user that they can't manage directly — for instance, if someone replies a post or comment by `@reader1@myblog.com` on Mastodon, this reader/author isn't notified anywhere (for comments at least, I guess) and can't interact with the person that replied to them.

**Comment by pfefferle** [comment]
The problem is, (as I already said) that this is not possible using ActivityPub. This feature would require to implement Mastodons proprietary API and it would require that blog visitors would have to authenticate themselves to your blog with their Mastodon Accounts.

There are two tricky things about this:

1. It would be a lot of work for simply POSSEing comments to Mastodon and only Mastodon, any other platform has to be implemented separately.
2. If you Authenticate yourself on "blog.example.com", this blog and its admins would have an `Access` token, that could be used to post ANYTHING to Mastodon in your name!

**Comment by pfefferle** [comment]
> I say this with utmost respect for your awesome work, but current implementation for blog-users creates a limbo, with new accounts created for each user that they can't manage directly — for instance, if someone replies a post or comment by @reader1@myblog.com on Mastodon, this reader/author isn't notified anywhere (for comments at least, I guess) and can't interact with the person that replied to them.

I am currently working on a fix, to only be able to comment to federated comment as Author on the blog or from the Fediverse, to not have this issue any more.

Yes it would separate conversations, but at least there wouldn't be any local answers to federated comments any more.

**Comment by pfefferle** [comment]
I understand your point, but in this specific case, POSSE is not the fediverse way to do it.

If someone should answer to a comment thread on your blog using a mastodon account, he has to do it on mastodon and his/her comment will be then federated to your blog!

**Comment by rghedin** [comment]
I see, now I understand your point. It really is a tricky balance to integrate both platforms, and knowing what I've just learned, ActivityPub plugin decisions seems sensible indeed.

**Comment by pfefferle** [comment]
Yes, the comment implementation was the hardest one so far! Mixing up a former local comment system with federated and decentralised comments is tricky. I learned a lot from the feedback after the launch of 2.0.0, so comments will be a major topic for quite some more releases.

I totally agree that the current version has not a really good UI/UX, but we will improve it over time!

Thanks for all your feedback, I really appreciate it, even if not everything is possible :)

**Comment by mdingemanse** [comment]
I had the same problem and would argue we need a way to **opt out** from posting comments WordPress -> AP, especially in blog user mode.

Specific example: a regular commenter responded on the blog (this did not federate, and I don't think it should). I responded to that comment, logged in as myself. 

That response is now federated, leading to an out of context reply showing up in the Fediverse feed. I didn't expect a response to a non-fedi comment to federate. And moreover there is no way for me now to delete that from my feed. (Short of removing the comment on my blog, and even that may not work.)

For me this is a breaking feature: I cannot use my own blogs commenting system in the way I want currently. 

Another reason we should be able to opt out: Think of a well read blog where feeding subscribers set their notifications for new posts. Now they would be pinged for every new comment.

**Comment by pfefferle** [comment]
> Specific example: a regular commenter responded on the blog (this did not federate, and I don't think it should). I responded to that comment, logged in as myself.

This is a bug I am currently working on and I am also adding methods to disable comment federation.

**Comment by mdingemanse** [comment]
Sorry for commenting on a closed issue @pfefferle but I wasn't sure what exactly has been implemented in the last update. Do comments not federate anymore? Is there a way to opt out? I hesitate to try it on my blog currently for fear of blasting another series of unwanted comments into the fediverse.

**Comment by pfefferle** [comment]
@mdingemanse Only comments that are published by an blog user and only in reply to the post or a comment from the fediverse will be federated.

To deactivate comments completely, you can use constants: https://wordpress.org/plugins/activitypub/#constants

> `ACTIVITYPUB_DISABLE_INCOMING_INTERACTIONS` – Block incoming replies/comments/likes. Default: `false`.
> `ACTIVITYPUB_DISABLE_OUTGOING_INTERACTIONS` – Disable outgoing replies/comments/likes. Default: `false`.
