### ISSUE TITLE
Feature Request: Map WordPress post type to Activity Type

### ISSUE THREAD

**Issue by DeadSuperHero** [Automattic/wordpress-activitypub#678]
### What

Publications and blogs can make extensive use of different WordPress types: images, videos, podcasts, reviews, articles, and more. The problem is that the current ActivityPub plugin makes a big assumption that a blog's admin wants all of their stuff to appear as a singular uniform type to Fediverse Actors, even when specific WordPress types might be suited to something else.

![Screenshot_20240125_140218_Firefox](https://github.com/Automattic/wordpress-activitypub/assets/401560/80783c93-2ecd-4a81-9ec5-281e6d49dab4)

![Screenshot_20240125_140157_Firefox](https://github.com/Automattic/wordpress-activitypub/assets/401560/cd6b34b4-3732-482a-8265-da38320d1ea2)

We humbly request an extension of the existing customization feature to be applicable on a per-Wordpress-post-type basis.

### Why

One struggle that we've had with the WordPress-ActivityPub plugin is that it currently takes an "all or nothing" approach for a blog.

We Distribute has multiple types of WordPress posts:
* Long-form Articles
* Podcast Episodes
* Newsletters

We're also looking at adopting short-form posts for quick news updates.

Here's the problem: all of these will only be rendered as one uniform Activity type. If we choose `Article`, even short-form content will be unreadable from platforms such as Mastodon. If we choose `Note`, that might cause problems for platforms specifically designed to post and read `Article` activities.

It would be incredibly useful to extend the existing customization options for federation to be applied on a per-Wordpress-post-type basis.

### How

The plugin could check to see which post types are currently enabled on a WordPress site, then provide customization options for what `Activity` type is used, and how the template is customized. 

This would allow content coming out of WordPress look more native to Fediverse platforms supporting particular types. From a UX perspective, maybe the Customization section would represent different tabs for each WordPress post type, and users could decide which activity type should be mapped.

**Comment by pfefferle** [comment]
Thanks for filing that issue! I am totally with you and already prepared a PR for that, I am curious about your feedback: https://github.com/Automattic/wordpress-activitypub/pull/661

**Comment by DeadSuperHero** [comment]
Wow! 🤯 I guess we're on the same page about this.

**Comment by DeadSuperHero** [comment]
I just wanted to follow up on this, as it's something I'm still thinking about.
I see that you have improved the defaults in your PR - which is good! That is definitely a great improvement.

One thing that I have been thinking about for We Distribute, is the idea of mapping different WordPress Post Types to different ActivityPub vocabulary representations.

Here are the WordPress Post Types we currently support:

* Post - all of our articles
* Note - Basically short-form content, could pretty much be used as Mastodon-like statuses.
* Episode - Basically, an episode of our podcast

It would be really cool to be able to use something like this dialog:
![image](https://github.com/Automattic/wordpress-activitypub/assets/401560/3a278c7b-dfe3-4372-b68f-229501c1f6b6)

On individual WordPress Post Types. So, it could be something like this:

* Post - `WordPress Post-Format`
* Note - It's actually just `Note`! We think it would be interesting to have Mastodon-like posts for short pieces of breaking news.
* Episode - `Note` with an excerpt and one audio attachment

I realize I might be asking a lot, but being able to do this for better compatibility with the network would be great for our site.

**Comment by pfefferle** [comment]
> I realize I might be asking a lot, but being able to do this for better compatibility with the network would be great for our site.

I like that you ask a lot, that means you care! 🫶

The current code uses `Article` as default and sets `Note` if it is of the type: 'aside', 'status', 'quote', 'note', 'gallery', 'image', 'video' or 'audio', it changes to `Note`.

So if I change it so that "Note" is the default and that "Article" is set specifically for articles only, it might work like you proposed?

I think I like the idea, because as `Note` is handled the best, every unknown WordPress content should us that as default!

Thanks for your feedback!

**Comment by DeadSuperHero** [comment]
I think I'm pretty comfortable with that idea! That should work for most use-cases.
