### ISSUE TITLE
Toot personalization for custom post type

### ISSUE THREAD

**Issue by ulaulaman** [Automattic/wordpress-activitypub#686]
I have defined several custom post types on the site I manage and I would find it very useful, without having to change the settings every time, to be able to define a different message for each custom post type. For example, with some types I would prefer to send only the excerpt, while with others all the content.
I hope you can introduce a differentiation of this kind.

Thanks,
Gianluigi.

**Comment by rghedin** [comment]
Up. This would be very useful to my usage.

**Comment by seindal** [comment]
+1
This would be fantastic.

**Comment by janboddez** [comment]
Although far from a definitive solution ... if anyone is up for some experimenting, I have developed a sort of "AP template system" (it's really quite simple) for custom post types: https://github.com/janboddez/addon-for-activitypub/?tab=readme-ov-file#content-templates

**Comment by rghedin** [comment]
Not a chance to add this feature? @pfefferle
