### ISSUE TITLE
Not possible to edit incoming Fediverse comments

### ISSUE THREAD

**Issue by janboddez** [Automattic/wordpress-activitypub#687]
### Quick summary

Another thing (beside [the missing reply link](https://github.com/Automattic/wordpress-activitypub/issues/652#issuecomment-1930661817)) I noticed when using the _latest master_ (or, at least yesterday's version), is that an admin can no longer edit a comment that came from the Fediverse.

### Steps to reproduce

1. Use Mastodon to comment on a post/previous comment.
2. Log into WP.
3. Notice how you can only (un)approve and trash the comment, but not edit it.

### What you expected to happen

I'd expect to still be able to edit the comment (typos, brevity ...). It's my site, after all. Even if it is considered "cheating." E.g., maybe I'd want to shorten a specific comment, and add a "read more" link back to its origin or something.

### What actually happened

The Edit link disappeared. Came back when v2.0.1 was reactivated.

I'm guessing this is by design. (No "cheating"!) A Mastodon admin also can't easily (without hacking the database) change incoming statuses. But it still came unexpected.

I was also looking to add a comment meta box (to the screen which I can no longer access for these comments), where I can easily view its origin, avatar URL, etc., similar to how Webmention does it. So that also isn't possible when access to this screen is denied even for admins.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

Additional info: I also got this Query Monitor (a different plugin, I know!) error: `PHP Fatal error:  Uncaught TypeError: QueryMonitor::filter_user_has_cap(): Argument #1 ($user_caps) must be of type array, bool given, called in /.../wp-includes/class-wp-hook.php on line 324 and defined in /.../wp-content/plugins/query-monitor/classes/QueryMonitor.php:111`

This happened when I tried to still access the Edit Comment screen for the comment in question. Wonder if this could be an (unintended) bug.

**Comment by pfefferle** [comment]
That is, to be honest, how it should be... even if it is your site, it is a comment by someone else that is only "cached" on your site... I had a lot of discussions and rants on Mastodon, how the WordPress plugin handles things differently than on social media...

We can discuss a better way to disable it, but I would love to keep it as default, but still open for discussions.

You can disable the new behaviour by removing the following filters:

```PHP
\remove_action( 'load-comment.php', array( self::class, 'edit_comment' ) );
\remove_filter( 'comment_row_actions', array( self::class, 'comment_row_actions' ), 10 );
```

**Comment by janboddez** [comment]
Ah, that's kind of what I expected. No worries then, and good to know there's an "easy" workaround!
