### ISSUE TITLE
Readme: shrink all sections to < 1500 words

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wordpress-activitypub#702]
The plugin repo has instituted a new 1500 word limit on readme sections in order to combat spam: https://meta.trac.wordpress.org/ticket/7477

Our only impacted section is the changelog, which is roughly 1500 words presently. How should we trim it going forward? Should we just link to this repo's Releases section? It would save on some release housekeeping, but it might be nice to still have the most recent few changes right there?

**Comment by pfefferle** [comment]
What about adding a `changelog.md` that we simply reference in the changelog section?

See also: https://github.com/Automattic/wordpress-activitypub/issues/439
