### ISSUE TITLE
`activitypub-remote-reply` script enqueues 29 dependencies on all `is_singular()` requests

### ISSUE THREAD

**Issue by kasparsd** [Automattic/wordpress-activitypub#705]
### Quick summary

Introduced in #689 the `activitypub-remote-reply` script handle now enqueues itself with 29 dependencies:

> wp-polyfill-inert, regenerator-runtime, wp-polyfill, wp-hooks, wp-i18n, wp-url, wp-api-fetch, react, react-dom, wp-dom-ready, wp-a11y, wp-deprecated, wp-dom, wp-escape-html, wp-element, wp-is-shallow-equal, wp-keycodes, wp-priority-queue, wp-compose, moment, wp-date, wp-html-entities, wp-primitives, wp-private-apis, wp-redux-routine, wp-data, wp-rich-text, wp-warning, wp-components

This happens on posts and pages that (1) don't support comments, (2) don't have comments enabled.

This also adds a combined total of almost 2MB of potentially unused JS to all of those requests. 

### Steps to reproduce

1. Enable the plugin.
2. Visit any single post or page and confirm that all of the mentioned dependencies are enqueued in the HTML source code.

### What you expected to happen

1. The reply script is enqueued only on posts and pages that support comments and have comments enabled.
2. The script is lazy-loaded only when the user clicks on the call-to-action link/button.

### What actually happened

The mentioned script and style gets enqueued on all post and page views. The enqueued dependency bundle size is incredibly large.

### Impact

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

**Comment by pfefferle** [comment]
Sadly #706 removes the JS completely, so I had to remove it for now. I reopened the issue, because we still need a solution for the issue.

**Comment by edent** [comment]
I've just found a ton of GlotPress translation stuff in my blog which appears to be coming from this plugin.

![Screenshot from 2024-04-08 18-02-38](https://github.com/Automattic/wordpress-activitypub/assets/837136/1c639ae3-c97e-4306-83ee-71e1d3812956)

I love having my blog on the Fediverse. But I want to run a lean and quick website which, as far as possible, works *without* JS.

Would it be possible to have an option to switch off the things we don't need?

**Comment by jeherve** [comment]
Related: #426

**Comment by mattwiebe** [comment]
I've https://github.com/Automattic/wordpress-activitypub/pull/725 that should eliminate loading the script (and its heavy dependencies) in all situations where it's not needed
