### ISSUE TITLE
Federate Replies with User mode disabled

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/wordpress-activitypub#711]
### Quick summary

The [`are_comments_allowed()` check](https://github.com/Automattic/wordpress-activitypub/blob/15ae5f68ed775ccd5475f53a1b5436a8889e39c0/includes/class-comment.php#L88) will prevent a logged-in user from replying to comments on a site with only the Blog User enabled. 

### Steps to reproduce

1. Add `define( 'ACTIVITYPUB_SINGLE_USER_MODE', true );` to your `wp-config.php`
2. Reply to a federated post from a Mastodon (or similar) service.
3. Only see the "Reply on the Fediverse" link for the comment, not allowing me to make a federated reply from WP

### What you expected to happen

As a logged-in user with sufficient rights, I should be able to reply to the comment and have it federated as the Blog User.

### What actually happened

I only see the "Reply on the Fediverse" option.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
Oh, that is a good point! and not that easy to solve... :(
