### ISSUE TITLE
More filters, please

### ISSUE THREAD

**Issue by seindal** [Automattic/wordpress-activitypub#716]
### What

It would be very useful if the plugin would use more filters in several places.

### Why

A filter on the generated content before the toot is sent would allow local customisations which are not otherwise possible.

For example, using [ap_content] on a post and cut the text at the  marker, for when the excerpt is too little, but the entire content is too much. It would make it possible to share a few paragraphs. This could easily be implemented with a filter in the ap_content shortcode.

Another useful filter would be for the template, so other plugins could apply separate templates to different post types.

Likewise for ap_hashtags and categories, for those who have custom taxonomies.

This is just what I've stumbled upon in my usage of the plugins, which is absolutely brilliant.

### How

A content filter is one line:
```
$content = apply_filters( 'activitypub_content', $content, $post );
```

Likewise for the template, something along the lines of
```
$template = apply_filters( 'activitypub_template', $template, $post );
```

**Comment by pfefferle** [comment]
You use the following filters for that:

* filter all object params with `activitypub_activity_object_array`: https://github.com/Automattic/wordpress-activitypub/blob/7ae3e7383d9c3fa1530940f7345b90b8e2bef642/includes/activity/class-base-object.php#L670C29-L670C62
* filter the template with `activitypub_object_content_template`: https://github.com/Automattic/wordpress-activitypub/blob/7ae3e7383d9c3fa1530940f7345b90b8e2bef642/includes/transformer/class-post.php#L752
