### ISSUE TITLE
Blog not found from Mastodon

### ISSUE THREAD

**Issue by aqeeliz** [Automattic/wordpress-activitypub#729]
So, I just setup ActivityPub plugin, tried searching  (@aqeel@aqeeliz.com) from mastodon (floss.social), found it, and followed it. (Yay!)

Then after playing around with some general settings and themes, I made a test post, and it didn't federate, after waiting a while, I tried looking up my account from other mastodon sites, and I can't find it now. I can still find it if I search from the first site (floss.social), but that could be cached data.

I have checked other issues here, and webfinger seems to be the general culprit, but it seems to be working fine. Anything else that I might be missing?

I am using nginx on archlinux, with latest wordpress (6.5.2), and no plugins enabled (other than ActivityPub ofcourse)

**Comment by pfefferle** [comment]
I can only see the default post. Did you publish them as private posts or did you delete them? The plugin sends the post with WP_Con, so it might take some time for it to be federated.

**Comment by aqeeliz** [comment]
> I can only see the default post. Did you publish them as private posts or did you delete them? The plugin sends the post with WP_Con, so it might take some time for it to be federated.

I deleted the default post, and just created a new one. Forgot that default one is also "Hello World", could that be the issue? 

As for the time, it was posted around 3 hours ago.

Also, can you find me if you search from mastodon?

**Comment by pfefferle** [comment]
I can find and follow you. Maybe post something new with a different slug, to be sure!

**Comment by aqeeliz** [comment]
Ah, it worked. So just a faulty slug :grin: 

Thanks for your time and help!
