### ISSUE TITLE
Auto-generated excerpt used for content warning when mapping post formats

### ISSUE THREAD

**Issue by kvibber** [Automattic/wordpress-activitypub#735]
### Quick summary

After the most recent plugin update, I turned on the "WordPress Post-Format - Maps the WordPress Post-Format to the ActivityPub Object Type. " option. I didn't notice it at first, but blog posts I made or updated over the next few days started federating with a multi-line paragraph as the content warning, with the rest of the post behind it. After looking around, I noticed that they were the auto-generated excerpts, complete with the "[...]" at the end. When I switched back to always sending as a note, and edited a few of those posts to send out an update, they returned to showing the custom template I'd defined.

### Steps to reproduce

1. Follow blog from a Fediverse platform. (I saw this with both Akkoma and GoToSocial, and I would've checked Mastodon if I hadn't just marked my account as migrated the day before.)
2. Turn on WordPress Post Format in the ActivityPub settings.
3. Write some posts. Don't write a custom excerpt for any of them. Try some different formats.
4. Look at the post in your Fediverse software.

### What you expected to happen

The posts should appear as configured.

### What actually happened

The posts appeared with a multiline content warning containing the full text of the auto-generated excerpt (which in some cases was 90% of the text followed by "[...]"), with the full content appearing behind the content warning.

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by pfefferle** [comment]
Oh no! I thought platforms do not use the `summary` for content warnings any more (mastodon supports them as summary now). This is sad!

I will try to report that issue to the mentioned platforms!

Thanks for your investigation!

**Comment by pfefferle** [comment]
FYI: @janboddez 😞

**Comment by DeadSuperHero** [comment]
+1 for this, we've been having the problem as well. It seems that most platforms are still following Mastodon's old behavior for content warnings.
