### ISSUE TITLE
Debugging why following isn't working

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#741]
### Quick summary

In #730, I noticed that I've had no new followers since February. I've tried following the blog from various Fediverse accounts and the follow never completed.

I am using a caching plugin, but I have excluded `/blog/@blog` and `/blog/wp-json/activitypub/*` and any requests with `application\/((activity|ld)\+json|json|ld\+json.*profile.*activitystreams`

My "Site Health" is good and all tests pass.

Is there any way to debug what's going wrong?

### Steps to reproduce

1. Try to follow `@blog@shkspr.mobi`
2. Notice the request doesn't complete

### What you expected to happen

The Accept should be sent back.

### What actually happened

It is not

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

Plugin 2.3.1 
WordPress 6.5.2
PHP 8.2.18

**Comment by edent** [comment]
It's whatever is in the WordPress Plugins repository. I just update it from within my blog. So I assume stable?

**Comment by pfefferle** [comment]
Anything that might have changed in this time-frame? mod-sec rules? lightspeed cache?

**Comment by pfefferle** [comment]
You can enable `WP_Debug` and check for an outgoing `Accept` request, as response to the follow. We use the classic WordPress `error_log` implementation for that.

**Comment by edent** [comment]
I can't see anything that I've changed. I've disabled Litespeed cache now, but no changed. I've added WP_DEBUG, but I don't see an error_log being created. The `debug_log` has a lot of `PHP Notice:  ob_end_flush(): Failed to send buffer of zlib output compression (1) in /home/openbenc/shkspr.mobi/blog/wp-includes/functions.php on line 5420` - but I don't think that's related.

**Comment by pfefferle** [comment]
Ah, you have to also define a debug log or at least activate it https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/#wp_debug_log

**Comment by edent** [comment]
Yes, my wp-config.php has:

```
// Enable WP_DEBUG mode
define( 'WP_DEBUG', true );

// Enable Debug logging to the /wp-content/debug.log file
define( 'WP_DEBUG_LOG', true );

// Disable display of errors and warnings
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );
```

There's nothing in debug_log which relates to ActivityPub that I can see.

All my posts appear to be syndicated out, and I can see the account from various fediverse servers. But it isn't accepting any new followers.

**Comment by edent** [comment]
OK, as near as I can tell, here's where it is failing - `includes/handler/class-follow.php`

```php
	public static function handle_follow( $activity ) {
		error_log("handling a follow: " . var_export($activity, true) );
                $user = Users::get_by_resource( $activity['object'] );

                if ( ! $user || is_wp_error( $user ) ) {
			error_log("handling a follow - no user");
                        // If we can not find a user,
                        // we can not initiate a follow process
                        return;
                }
...
```

The activity it receives is:
```php
array (
  '@context' => 'https://www.w3.org/ns/activitystreams',
  'id' => 'https://mastodon.social/faa1c773-e74c-481c-af9b-bf887921df1f',
  'type' => 'Follow',
  'actor' => 'https://mastodon.social/users/Edent',
  'object' => 'https://shkspr.mobi/blog/@blog',
)
```

`is_wp_error( $user ) )` evaluates as true because `$user` is:

```php
\WP_Error::__set_state(array(
   'errors' =>
  array (
    'activitypub_no_user_found' =>
    array (
      0 => 'User not found',
    ),
  ),
   'error_data' =>
  array (
    'activitypub_no_user_found' =>
    array (
      'status' => 404,
    ),
  ),
   'additional_data' =>
  array (
  ),
))
```

Is this because `get_by_resource()` doesn't like that my user is `https://domain.example/blog/@user`?

**Comment by pfefferle** [comment]
Ok, thanks for debugging! I will see why this breaks and how we can fix it!

**Comment by pfefferle** [comment]
Ah, I have the issue! It is because of the `@` check if the path! And because your blog is in a subdirectory!

So many tricky things on self-installed WordPresses :)
