### ISSUE TITLE
Critical error when accessing self-hosted Wordpress blog with ActivityPub plugin activated

### ISSUE THREAD

**Issue by minnixtx** [Automattic/wordpress-activitypub#748]
### Quick summary

When I activate the ActivityPub plugin and go to my site URL https://tech.minnix.dev I get the standard WP message "There has been a critical error on this website."

### Steps to reproduce

When I activate the ActivityPub plugin and go to my site URL https://tech.minnix.dev I get the standard WP message "There has been a critical error on this website." 

If I go to the author page defined within the AP plugin settings page it looks fine https://tech.minnix.dev/index.php/author/minnix/ . Also if I click on a post from there I can see it, eg: https://tech.minnix.dev/index.php/2024/04/26/use-docker-and-nicotine-to-build-a-righteous-music-archive/ The main index page and my info page https://tech.minnix.dev/index.php/2024/04/23/find-me/  give me the critical error. 

My WP is deployed via Docker if that may be an issue via this compose file: https://github.com/docker/awesome-compose/blob/master/official-documentation-samples/wordpress/README.md although I am using jammy instead of focal for the DB.

I can also find my blog on Mastodon @minnix@tech.minnix.dev and successfully follow it.

### What you expected to happen

I expect it to give me a view of my front page

### What actually happened

Instead I get the critical error page

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

Debian 12 VM within Proxmox
Wordpress deployed via Docker

**Comment by pfefferle** [comment]
Can you enable WP_DEBUG so that we maybe see a more detailed error?

**Comment by minnixtx** [comment]
> Can you enable WP_DEBUG so that we maybe see a more detailed error?

Here's debug info:

```
Fatal error: Uncaught TypeError: ltrim(): Argument #1 ($string) must be of type string, array given in /var/www/html/wp-includes/formatting.php:4494 Stack trace: #0 /var/www/html/wp-includes/formatting.php(4494): ltrim(Array) #1 /var/www/html/wp-content/plugins/activitypub/includes/class-mention.php(111): esc_url(Array) #2 [internal function]: Activitypub\Mention::replace_with_links(Array) #3 /var/www/html/wp-content/plugins/activitypub/includes/class-mention.php(80): preg_replace_callback('/@(?:([A-Za-z0-...', Array, 'funkwhale: @min...') #4 /var/www/html/wp-includes/class-wp-hook.php(324): Activitypub\Mention::the_content('

\n

matrix:...') #5 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters('
\n

matrix:...', Array) #6 /var/www/html/wp-includes/formatting.php(3992): apply_filters('the_content', '\n

\n\n\n\n

...') #7 /var/www/html/wp-includes/class-wp-hook.php(324): wp_trim_excerpt('\n

\n\n\n\n

...', Object(WP_Post)) #8 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array) #9 /var/www/html/wp-includes/post-template.php(434): apply_filters('get_the_excerpt', '', Object(WP_Post)) #10 /var/www/html/wp-includes/blocks/post-excerpt.php(28): get_the_excerpt(Object(WP_Post)) #11 /var/www/html/wp-includes/class-wp-block.php(463): render_block_core_post_excerpt(Array, '', Object(WP_Block)) #12 /var/www/html/wp-includes/class-wp-block.php(443): WP_Block->render() #13 /var/www/html/wp-includes/class-wp-block.php(443): WP_Block->render() #14 /var/www/html/wp-includes/class-wp-block.php(443): WP_Block->render() #15 /var/www/html/wp-includes/blocks/post-template.php(119): WP_Block->render(Array) #16 /var/www/html/wp-includes/class-wp-block.php(463): render_block_core_post_template(Array, '
```

**Comment by pfefferle** [comment]
This helps, thanks for the debug message @minnixtx !

**Comment by minnixtx** [comment]
> This helps, thanks for the debug message @minnixtx !

Thank you for taking the time for me.

**Comment by pfefferle** [comment]
Can you send me the HTML code of the article that throws the error?

(https://tech.minnix.dev/index.php/2024/04/23/find-me/)

**Comment by pfefferle** [comment]
Or maybe simply deactivate the ActivityPub plugin, so that I can check it?

**Comment by minnixtx** [comment]
> Or maybe simply deactivate the ActivityPub plugin, so that I can check it?

Ok I've deactivated it. Also the theme I'm using is called Cue: https://wordpress.org/themes/cue/

**Comment by pfefferle** [comment]
Hmmm, can't reproduce it in my test system. Can you maybe provide me a list of the plugins you use?

**Comment by minnixtx** [comment]
The only plugin I was using is ActivityPub. I installed WP_DEBUGGING to get you the error messages. Akismet came by default with the install but it's not activated. I will deactivate the find me page and see if that changes anything.

**Comment by minnixtx** [comment]
Ok, once I moved the find me post to draft the site works fine. Something about that page it doesn't like. One thing is that it's the only page I linked to the bar at the top for quick access. The link is still there but it goes to 404 now that I've moved it to draft. Maybe there's something with the formatting on that page. Pretty much all the links on that page are for my federated services. I could try removing link by link and see what happens.

**Comment by pfefferle** [comment]
the plugin tries to make links out of these profiles. but it worked on my test system!

**Comment by minnixtx** [comment]
Ok I found the offending link on the find me page, it's the funkwhale link. If I write @minnix@allnightlong.minnix.dev I get the error. If I just write minnix@allnightlong.minnix.dev. It doesn't happen with any of the other links. What's special about this particular one I don't know.

**Comment by pfefferle** [comment]
Ah, I think I found the issue! Will prepare a PR!

**Comment by pfefferle** [comment]
This will do the trick https://github.com/Automattic/wordpress-activitypub/pull/753 !

**Comment by pfefferle** [comment]
@minnixtx can you maybe try this version, to see if it works for you?

**Comment by minnixtx** [comment]
Ok I'll try it now

**Comment by minnixtx** [comment]
That fixed it. The only other thing I see is the lemmy profile is not converted to a link like the others. It's not a big deal, just thought I'd point that out. It doesn't cause any errors though.

**Comment by pfefferle** [comment]
ok, will have a look at the lemmy profile too! good point!

I really appreciate that you have so many profiles... This is a nice testcase ☺️

**Comment by minnixtx** [comment]
If you want me to close this as solved just let me know. I can leave it open if you want to for lemmy.

**Comment by pfefferle** [comment]
no no, it will be auto closed if I merge the PR

**Comment by minnixtx** [comment]
OK thanks for all your help BTW
