### ISSUE TITLE
Migrating from Pterotype

### ISSUE THREAD

**Issue by DeadSuperHero** [Automattic/wordpress-activitypub#75]
Hey all,

I've been using Pterotype for one of my sites for some time. While it works pretty well, unfortunately the project has fallen into an unmaintained status, with no conceivable updates happening anytime soon.

Given that my blog (wedistribute.org) has a pretty sizable following across the fediverse, I was wondering whether there was anything that could be done to migrate the data being used by the Pterotype plugin to instead be used by `wordpress-activitypub`. Aside from the manual process of moving data from one place to another, what kind of considerations would need to be made? How different are the database schemas between Pterotype, and this one?

Please let me know!

**Comment by pfefferle** [comment]
Oh: https://github.com/pterotype-project/pterotype/issues/18#issuecomment-561010105

I will have a look how much work it is... But my plugin is very light weight and does work witch most of the WP Core data. I think the only thing that has to be migrated is the followers list.

@DeadSuperHero can you tell me how much followers you have?

**Comment by DeadSuperHero** [comment]
Hey @pfefferle , thanks for getting back to me!

> can you tell me how much followers you have?

If [this endpoint](https://wedistribute.org/wp-json/pterotype/v1/actor/-blog/followers) is any accurate indication, it appears that there are approximately 569 followers as of right now.

**Comment by jaywink** [comment]
Won't the most difficult thing be keeping the actor ID, which currently is `https://wedistribute.org/wp-json/pterotype/v1/actor/-blog` ? Because if that changes, all implementations will see it as a new actor anyway :thinking:

**Comment by pfefferle** [comment]
@jaywink good point... Using an API endpoint as profile page is not that nice... I will think about how to work around that problem... Perhaps providing the endpoint and redirect to the profile page if the `accept header` is something `html`.

**Comment by DeadSuperHero** [comment]
Just wanted to ping on this, as we have a rising spam problem stemming from Pterotype. Are there any thoughts on how the data could actually be migrated from one plugin to the other?

I suspect I might have to manually pull MySQL tables/rows from the db and somehow move them over to the other respective plugin, but I'm not totally sure on what the process even is right now.

**Comment by sunjam** [comment]
Would resolving issue #43 fix this?  That should allow @DeadSuperHero to continue using @blog@webdistribute.org scheme employed by pterotype, if I'm understanding this correctly.

**Comment by DeadSuperHero** [comment]
Theoretically, yes, but the existing articles would need to retain
attribution to the original actor object, and said actor would also need to
retain its follower collection from before the transition.

**Comment by DeadSuperHero** [comment]
To clarify, what I mean is: basically we would need to retain the followers
collection of the original actor object, and then make sure that the
attribution in federated posts correctly points back to it, so that further
interactions with said posts receive updates.

**Comment by sunjam** [comment]
@DeadSuperHero pterotype was causing serious errors on my wordpress so I just had to uninstall it.  Oh well.  Hope you are doing well!

**Comment by sunjam** [comment]
:shrug: Would love to have work on this, so suppose this will keep it open.

**Comment by sunjam** [comment]
:man_shrugging: open

**Comment by pfefferle** [comment]
Is this still a valid request?

**Comment by sunjam** [comment]
@pfefferle absolutely my friend. :)
It would be so wonderful to continue using @blog.* account instead of it being dead forever. Thanks for considering!

**Comment by pfefferle** [comment]
with 1.0.0 it is already possible to use `@blog@...` or whatever you call it. It is more about the rest of the data!?!

**Comment by sunjam** [comment]
> with 1.0.0 it is already possible to use `@blog@...` or whatever you call it. It is more about the rest of the data!?!

Excellent, do you need help with testing this?

**Comment by pfefferle** [comment]
does it make sense to have these settings? why not use the blogs settings? why should someone wants to have different informations on the blog as on the fediverse? this isn't even possible on Mastodon & Co.

**Comment by sunjam** [comment]
Personally, I really enjoy being able to write my own description, user name and set an icon for how my site is perceived on the fediverse.  :shrug: 

Here is how it looks from Mastodon Social.
https://mastodon.social/@blog@james.network

**Comment by pfefferle** [comment]
@DeadSuperHero @sunjam Thanks for your feedback and @DeadSuperHero I would love to have that as an extra issue.

And the question is still: Should/can we close this one?

**Comment by sunjam** [comment]
> And the question is still: Should/can we close this one?
My question is: can I start using the same @blog@* account?

Thank you so much for caring about this.  I love this.

**Comment by pfefferle** [comment]
you can rename the blog user (default is domain.tld@domain.tld) to blog@domain.tld, yes. This is already possible.

**Comment by sunjam** [comment]
> you can rename the blog user (default is [domain.tld@domain.tld](mailto:domain.tld@domain.tld)) to [blog@domain.tld](mailto:blog@domain.tld), yes. This is already possible.

Okay, did this by creating a blog user on my site.  Seems [the post](https://james.network/archives/re-joining-the-federation-what-did-i-miss/) is not showing on the federation side, nor is the [gravator icon or profile description updated](https://mastodon.social/@blog@james.network).

**Comment by pfefferle** [comment]
@sunjam the content-negotiation does not seem to work on your blog.

```
curl "https://james.network/archives/author/blog/" \
     -H 'Accept: application/activity+json'
```

This returns HTML instead of JSON. Do you maybe use a Caching plugin?

**Comment by mediaformat** [comment]
> My question is: can I start using the same @blog@* account?

This will not work for any instance that has previously interacted with the pterotype acct, since those instances have a cached copy of the pterotype public key, which will be different to the newly created one. Mastodon and most other software will ignore the new account.

**Comment by mediaformat** [comment]
Essentially the Pterotype actor would need to send a`Move` activity:
```
{
    "@context": "https://www.w3.org/ns/activitystreams",
    "id": "https://old.instance/users/someusername#moves/1",
    "type": "Move",
    "target": "https://new.instance/users/someothername",
    "actor": "https://old.instance/users/someusername",
    "object": "https://old.instance/users/someusername"
}
```
And our new Actor would need to have an `alsoKnownAs` property pointing to the pterotype actor.

**Comment by sunjam** [comment]
> This returns HTML instead of JSON. Do you maybe use a Caching plugin?

Yes, LiteSpeed cache app from hosting provider.

**Comment by mediaformat** [comment]
> Yes, LiteSpeed cache app from hosting provider.

See here https://github.com/Automattic/wordpress-activitypub/issues/442#issuecomment-1723612596

**Comment by sunjam** [comment]
Tried the litespeed fix without success.  I'll try it again.
