### ISSUE TITLE
Feature Request: Content Warnings

### ISSUE THREAD

**Issue by BlueWinds** [Automattic/wordpress-activitypub#757]
### What

I would like the option to add content warnings to posts when they are published via activitypub.

### Why

Many fediverse instances require NSFW content to be content-warned. In some circles it's also a social norm to tag certain topics (such as "mh-", "American Politics", "transphobia", or others).

I would appreciate if this plugin provided users (like me) the option to both better respect instance rules and also be good citizens of the fediverse.

### How

Some possible implementations:
- Via tags - "Posts tagged with tags X, Y or Z get content warnings", using the tag name as the CW text
- Via categories - "Posts in category X, Y or Z get a content warning", using the category name as the CW text
- A new field on posts?

I'm unsure what would be the best way to handle it, but I'd appreciate the option

**Comment by BlueWinds** [comment]
Not stale, Mr. bot. Feature request that was never looked at.

**Comment by pfefferle** [comment]
Some links:

* https://mts.mediencampus.h-da.de/blog/content-warnings-on-mastodon/
* https://fedi.tips/how-to-use-content-warnings-cws-on-mastodon-and-the-fediverse/
