### ISSUE TITLE
Blog not accepting follow requests on the fediverse (similar to #741 maybe)

### ISSUE THREAD

**Issue by minnixtx** [Automattic/wordpress-activitypub#760]
### Quick summary

My blog isn't accepting follow requests via Mastodon. I just get the "Cancel Follow" button when viewing the blog profile. I'm sorry I don't have much information available because debug doesn't really show anything within Wordpress. tech.minnix.dev is the site and site health is fine. The only plugins I'm using is ActivityPub and wp_debug. I thought it might be a similar issue to #741 but I don't have an @ in my user as my profile url is https://tech.minnix.dev/index.php/author/minnix/

### Steps to reproduce

Follow minnix@tech.minnix.dev on Mastodon

### What you expected to happen

Follow request accepted

### What actually happened

My follow request is never accepted and "Cancel Follow" is shown instead on the blog's profile

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

More info about my install can be found at #748

**Comment by pfefferle** [comment]
@minnixtx see: https://github.com/Automattic/wordpress-activitypub/issues/591#issuecomment-2201329297

**Comment by minnixtx** [comment]
> @minnixtx see: [#591 (comment)](https://github.com/Automattic/wordpress-activitypub/issues/591#issuecomment-2201329297)

Brilliant. It worked. I have no recollection of changing post URLs to include index.php but after changing the format to just include the post title without index.php the problem is solved. Thanks.
