### ISSUE TITLE
Scheduled Post is Federated Immediately on Save

### ISSUE THREAD

**Issue by jmking-iftas** [Automattic/wordpress-activitypub#767]
### Quick summary

Created a post tied to a timed press release for publishing the next day. Blog is federated as an entire blog, authors are not enabled. Blog is hosted on Wordpress.com (Creator package). Scheduled post was federated immediately, with no way to retract/delete.

### Steps to reproduce

1. Create a scheduled post on a blog that has a federation setting
2. Choose a scheduled date for publish
3. Click "Schedule" to save the document
4. Document is set to scheduled, but document is immediately federated

### What you expected to happen

Document should not federate until publication date time

### What actually happened

Document federated immediately

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
@mattwiebe are you aware of .com doing something special here? I can't reproduce it on my local WordPress installation.

**Comment by mattwiebe** [comment]
I tested just now on a Creator Plan site, I had the opposite problem: the postdated post never seems to have contacted its followers at all. Strange. 

Dotcom Simple worked as expected though.

**Comment by drbruced12** [comment]
I seem to have the same problem as @mattwiebe - I always schedule my posts, and with the most recent one, it didn't publish to the Fediverse at all. I am also using the creator plan on wordpress.com

**Comment by drbruced12** [comment]
Update: plugin has worked correctly with my most recent post. I scheduled it last week, but when it published today the post showed up in the Fediverse correctly.

**Comment by pfefferle** [comment]
@jmking-iftas do you use the "Publish to Schedule" plugin?

https://wordpress.org/support/topic/scheduled-and-updated-posts-showing-up-on-the-fediverse/#post-17864117
