### ISSUE TITLE
Feature Request: Be able to add a bio when profile type is set to ‘enable blog’.

### ISSUE THREAD

**Issue by ethicalrevolution** [Automattic/wordpress-activitypub#768]
### What

Brilliant plugin. 

In Settings -> Profiles -> Enable profiles by type …When ‘Enable blog’ is selected so that the blog becomes an ActivityPub profile, the bio shown to followers on Fediverse platforms such as Mastodon is the website description in Wordpress.

It would be great if there was a way I could change the bio without changing the Wordpress website description.

e.g. I want my website description to still read, “An awesome website about [whatever]” for viewers on the website, search engines etc. …but I want the ActivityPub profile to display something different such as “Please be aware that messages sent from this account are automatically posted from [website]. Replies will be received as comments on the website, but any mentions and DMs that are not replies to posts made by this account will not be received.”

### Why

The bio I want to display for people following on Mastodon is not the same as the info I want to show as the website description in Wordpress. 

I don’t want people to interact with the profile on ActivityPub and think they’re being ignored, which is what happens if someone tags the account in a message that is not a direct reply to a message that the profile has sent from Wordpress.

**Comment by pfefferle** [comment]
This is already possible in the latest version!
