### ISSUE TITLE
Close comments?

### ISSUE THREAD

**Issue by janboddez** [Automattic/wordpress-activitypub#789]
### What

Is there an easy way to "close" replies and such? Like, for posts older than 30 days (or whatever).

### Why

WordPress offers this functionality for regular comments. Noticed "ActivityPub comments" don't seem to respect WP's setting.

### How

Add a check before new comments are processed. If comments are closed for a certain posts, drop the request.

Maybe a simple filter hook would suffice. Site owners with some PHP knowledge could then implement a callback function themselves. (Maybe they want to keep AP reactions open for longer, for instance, or apply some other kind of logic.)

If the request parameters are also made available to any hooked functions, could even use this to decide who gets to reply to certain posts and who doesn't (I know about the discussion filters, but this could allow a more fine-grained control).

**Comment by janboddez** [comment]
Alternatively, I guess we _could_ use the `pre_comment_approved` filter, return a `WP_Error` or something, based on whatever is in the comment data.

**Comment by baby-gnu** [comment]
like #640

**Comment by janboddez** [comment]
Oops, missed that one.

I think for now I'll give filtering `pre_comment_approved` a try.  "Close" also ActivityPub comments if the post with ID `$commentdata['comment_post_ID']` is over 60 days old (or whatever is set in WP's general discussion settings).
