### ISSUE TITLE
OpenGraph-Tag doesn't show

### ISSUE THREAD

**Issue by kaffeeringe** [Automattic/wordpress-activitypub#794]
### Quick summary

I tried the new feature #786 but the tag doesn't show up in my source code: https://kaffeeringe.de/

Is it possible, that Yoast SEO is a problem?

### Steps to reproduce

I updated to 2.50, emptied all caches.

### What you expected to happen

A meta tag with "fediverse:creator" in the source code of an article

### What actually happened

It doesn't show up

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment]
For now it "only" extends the OpenGraph Plugin to add it: https://de.wordpress.org/plugins/opengraph/

**Comment by kaffeeringe** [comment]
Ah! I saw the reference in the code, but I thought it avoided the conflict. Sorry, my PHP skills are not too good. :-D

**Comment by kaffeeringe** [comment]
I installed opengraph. Emptied all caches. It doesn't appear. :-(

**Comment by pfefferle** [comment]
Ah, you deactivated the author profiles... have not thought about this case!

...so maybe I have to release an update then ;)

**Comment by pfefferle** [comment]
It will be in the next release!
