### ISSUE TITLE
fediverse:creator

### ISSUE THREAD

**Issue by ThomasKujawa** [Automattic/wordpress-activitypub#796]
### What

It would be useful if the (new) meta tag is output automatically depending on the author.

### Why

https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/

### How

<meta name="fediverse:creator" content=" @ThomasKujawa@www.fachkraeftesicherer.de" />

**Comment by pfefferle** [comment]
Will be part of the next release: https://github.com/Automattic/wordpress-activitypub/blob/master/integration/class-opengraph.php

**Comment by cybeardjm** [comment]
It seems to default to the AP/WP author and to appear on all blog's pages by default. OK.
But as I've implemented it manually, I do point to my Mastodon profile and I might get into conflicts sooner or later... as mine appears higher in the header.
AP: <meta property="fediverse:creator" name="fediverse:creator" content="cybeardjm@www.didiermary.fr" />
vs
Mine: <meta name="fediverse:creator" content="cybeardjm@masto.ai" />

Shouldn't this option be opt-in and/or let people choose who's the "real" creator/author?

**Comment by rghedin** [comment]
An extra field on user profile for fediverse profile would be awesome. I don't use authors in the AP plugin exactly because I've already have a presence in fediverse and don't want to have multiple profiles from different systems.

**Comment by cybeardjm** [comment]
@rghedin 
> An extra field on user profile for fediverse profile would be awesome. 
It seems to exist a "Mastodon Server (URL)" - but formulation is not clear (to me), what should be in this field

**Comment by pfefferle** [comment]
This should be a simple extension to add the blog ids, to have full Open Graph support, you should use an Open Graph plugin. But you are right, there should be a way to disable the feature.

> What's the default chosen for the Home page in case of multiple authors?

The Blog-User if enabled.

**Comment by cybeardjm** [comment]
> The Blog-User if enabled.

???? Don't know what it means in my case. I don't use the Blog-User at all, only authors.
On both my blogs, it's the main (only) editor that's used on the **Home page** (both admins have AP disabled), even though on the 2nd blog there's a blog author too (that only appears as fediverse:creator for the posts where it is indeed the author)

=> if no Blog-User exists, and admin accounts have AP disabled, it falls back to 1st author? alphabetically or...?

**Comment by pfefferle** [comment]
it should use the author that published the post!

**Comment by cybeardjm** [comment]
> you should use an Open Graph plugin

I use one (Open Graph and Twitter Card Tags) very useful in some contexts in the Fediverse and elsewhere - I already asked them to support fediverse:creator

**Comment by cybeardjm** [comment]
> it should use the author that published the post!

It seems so indeed, although I disabled AP for pages...

**Comment by pfefferle** [comment]
> So logically, if I set the admin account as author for the pages, as AP is not enabled for the admin account, the fediverse:creator entry should disappear of the pages and be kept only for posts... RIght?

This is not about ActivityPub, it is about sharing one of your URLs using Mastodon! So that's why the plugin ignores the Post-Type settings.

**Comment by pfefferle** [comment]
> I use one (Open Graph and Twitter Card Tags) very useful in some contexts in the Fediverse and elsewhere - I already asked them to support fediverse:creator

I read that :)

**Comment by cybeardjm** [comment]
> This is not about ActivityPub, it is about sharing one of your URLs using Mastodon!

I know, but sorry, having implemented as part of AP, confused me a lot... So, it was just a "fun" to add/"why not do it" feature

**Comment by pfefferle** [comment]
It was a requested feature and as I said: The next version will have an Opt-In/Opt-Out setting for it.

If you can't wait, you can use `remove_action( 'wp_head', array( '\Activitypub\Integration\Opengraph', 'add_meta_tags' ) )` to remove it.
