### ISSUE TITLE
Allow logging in as the blog user in Enable Mastodon Apps

### ISSUE THREAD

**Issue by akirk** [Automattic/wordpress-activitypub#800]
It would be helpful, especially in light of being able to edit your profile (see https://github.com/akirk/enable-mastodon-apps/pull/157 and #584), to also be able to do this for the blog user.

I know there has been an effort made to use real WordPress users (#709), but if that effort goes nowhere, we should take a look into how we could allow logging in as that user in EMA.

**Comment by akirk** [comment]
I see that in https://github.com/Automattic/wordpress-activitypub/pull/788#issuecomment-2192321163 @mattwiebe stated that logging in might already be possible if there is only a blog user but I am not sure about how it works.

**Comment by mattwiebe** [comment]
> I see that in [#788 (comment)](https://github.com/Automattic/wordpress-activitypub/pull/788#issuecomment-2192321163) @mattwiebe stated that logging in might already be possible if there is only a blog user but I am not sure about how it works.

It works by using the Blog User when the User account is disabled. We'll still need to figure out a way to allow choosing between Blog and User when both are active later but this will be a good start I think.
