### ISSUE TITLE
Update to 2.6.0 added extra fields that can't be deleted or edited

### ISSUE THREAD

**Issue by mikewmerritt** [Automattic/wordpress-activitypub#813]
### Quick summary

Handle: [mikewmerritt@dymersion.com](https://masto.ai/@mikewmerritt@dymersion.com)

When I updated to 2.6.0, two extra fields appear to have been added. Before there were just the three Blog / Profile / Blog. Once updated, I was able to change the three fields listed on my Edit Profile page, but the two additional fields remain on the bottom, which are not listed on Edit Profile so can't be deleted or edited.

The two extra fields I can't edit are listed in the database as post_author '0', while the ones I can are listed under my own user id.

### Steps to reproduce

1. Update to 2.6.0
2. Go to the Mastodon page
3. See the extra fields

### What you expected to happen

Only three fields that can be edited

### What actually happened

There are five fields, the bottom-most two which cannot be edited or deleted.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
Oh, this is weird 😳

I will check how this could even happen!

**Comment by pfefferle** [comment]
I checked the code, but even with these two glitches in the DB, the plugin should never include these two in your profile! I can't reproduce it locally.

Will run some more tests!

**Comment by pfefferle** [comment]
Found the issue, will release a new version asap. This will not delete the two wrong entries (yet), but it will prevent generating new ones and it will not show them any more.

Can you delete them from the DB by hand?

**Comment by pfefferle** [comment]
Thanks for reporting it so quickly!!

**Comment by mikewmerritt** [comment]
> Found the issue, will release a new version asap. This will not delete the two wrong entries (yet), but it will prevent generating new ones and it will not show them any more.
> 
> Can you delete them from the DB by hand?

I can do that, yes. Thanks.
