### ISSUE TITLE
Feature Request: Posts' Alternate "Activity Pub Content" for ~250-char microblogging

### ISSUE THREAD

**Issue by maltfield** [Automattic/wordpress-activitypub#824]
### What

This is a request to implement a new `Post ActivityPub Contents` field for the user to enter a short (~250 char) summary of the Wordpress Post, which replaces the contents of the Post that's syndicated via Activity Pub.

### Why

I write very, very long articles on Wordpress. Those articles sometimes contain thousands of words and dozens of pictures.

Currently I use Mastodon to publish a short ~250-char toot about my WordPress articles. Many of my readers subscribe to my Mastodon account via ActivityPub, but it would be cool if I could cut-out the middle-instance and just host ActivityPub myself with Wordpress.

But most of my ActivityPub subscribers would still only want the contents of the ActivityPub messages to be micro-blogging-sized toots (~250 chars).

Therefore, I want to be able to define a totally distinct field from the Post's very long [content](https://developer.wordpress.org/rest-api/reference/posts/#schema-content). This shorter version is what wordpress would publish  via ActivityPub.

### How

I envision a UX similar to [Yoast's module](https://yoast.com/what-is-a-snippet/#h-search-appearance-preview-in-yoast-seo) that allows you to define `Meta description` snippets for each Post in a [plugin-specific module](https://wordpress.org/documentation/article/administration-screens/#screen-options)

| [![Screenshot of the Yoast module on the Post edit page, prompting the user to type a short "Meta description" that summarizes the article](https://yoast.com/app/uploads/2023/10/yoast-seo-search-appearance-preview-600x566.jpg)](https://yoast.com/what-is-a-snippet/) |
|:--:| 
| The popular Yoast SEO plugin for Wordpress has a [special input field](https://yoast.com/what-is-a-snippet/#h-search-appearance-preview-in-yoast-seo) allowing the user to enter a brief summary for the article |

Like Yoast's `Meta description` input field, I don't think this ActivityPub `Post ActivityPub Contents` input field should enforce a strict character limitation, but it should probably have some "green/yellow/red" indicator that turns yellow when you break ~250 characters and red when you break ~500 characters.

This would be an optional field. When it's empty, this plugin would publish the full article in Activity Pub (as is currently the case?). But when this field is not empty, that field's contents would replace the Post's `content` filed with the ActivityPub `content` field.

**Comment by pfefferle** [comment]
The plugin supports excerpts, is that what you requested?

**Comment by maltfield** [comment]
I'm not sure. Can you link me to the documentation that describes what is this "excerpts" feature you refer-to and how it works?

> This would be an optional field. When it's empty, this plugin would publish the full article in Activity Pub (as is currently the case?). But when this field is not empty, that field's contents would replace the Post's content filed with the ActivityPub content field.

Does it work like this?

**Comment by maltfield** [comment]
See also:

 * https://webapps.stackexchange.com/questions/177045/how-do-different-activitypub-platforms-handle-large-posts-that-exceed-their-char

**Comment by pfefferle** [comment]
So, there is no extra field, the plugin re-uses all existing WordPress features. So if you write an excerpt, using the WordPress excerpt field for that or if you use the read-more block, than this will be used to send to the fediverse.

**Comment by pfefferle** [comment]
Ah, this only works if you configure your post to send the excerpt with the excerpt shortcode or if you use the WordPress-Post-Format setting instead.

**Comment by pfefferle** [comment]
@maltfield does the excerpt solution work for you?

**Comment by maltfield** [comment]
I think so. Feel free to close this ticket for now. I'll request to re-open it if I discover otherwise later. Thank you <3
