### ISSUE TITLE
Bio coming from wrong section

### ISSUE THREAD

**Issue by ethicalrevolution** [Automattic/wordpress-activitypub#837]
### Quick summary

Bio reads from Wordpress bio but not from ActivityPub bio

### Steps to reproduce

1. Go to user profile.
2. Fill in bio that exists in Wordpress without ActivityPub plugin.
3. Fill in bio that only exists using ActivityPub plugin.
4. Click save.
5. View my profile on Mastodon and it’s the wrong bio of the two above that is displayed.

### What you expected to happen

The second bio in the first screenshot should appear.

### What actually happened

The first bio in the first screenshot appears (even if it’s blank).
![IMG_2233](https://github.com/user-attachments/assets/e84dd687-6373-4e60-8985-17203b8f0f62)
![IMG_2234](https://github.com/user-attachments/assets/42d06bf9-ff4e-49e9-b80c-e3eb4d8eb4e4)

### Impact

One

### Available workarounds?

Yes, easy to implement

**Comment by danielhuesken** [comment]
Should be fixed with #830

**Comment by pfefferle** [comment]
Yes, we try to release a new version asap!

**Comment by pfefferle** [comment]
Should be fixed in the latest version!
