### ISSUE TITLE
Commenting on my own blog post creates a new comment

### ISSUE THREAD

**Issue by donnchawp** [Automattic/wordpress-activitypub#840]
### Quick summary

If I comment on a post on my own blog, as my logged in user, a new duplicate comment is made with the same comment text.
The author name is the same too, but the URL is changed to my blog author URL.
The IP is the IP of my server.

### Steps to reproduce

1. Leave a comment on your own blog as your logged in user.
2. Observe a new duplicate comment generated a few seconds later.

### What you expected to happen

The duplicate comment should not have appeared.

### What actually happened

Duplicate comment was made a few seconds later.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

p1722927750475909-slack-C04TJ8P900J

**Comment by mediaformat** [comment]
confirming!

![Screen Shot 2024-08-12 at 4 10 52 PM](https://github.com/user-attachments/assets/25c8c5a4-b3d4-4355-b63b-893028ef5671)

**Comment by mediaformat** [comment]
I haven't looked at the logs, but there are different `comment_id`s, so I'm guessing wp is somehow federating replies to itself, since the new comment is coming from  a `remote` user!

**Comment by solarbirdy** [comment]
Also confirming, and it only seems to be first-level replies. Replies to other people's comments from the Federation do not seem to generate this issue.

**Comment by dzver** [comment]
Happens on https://veselin.blog as well, sandboxed or not

p1727948547147869-slack-C02FMH4G8

**Comment by dzver** [comment]
If anyone is curious, this is not resolved and my blog keepes getting duplicate comments.

It's even worse because some actions like approving/moving back a comment to the queue are also capable of generating a duplicate comment.

**Comment by pfefferle** [comment]
@dzver I made a mistake! I added a "same domain" check, but haven't thought about WordPress.com using a different domain for their endpoints!

https://github.com/Automattic/wordpress-activitypub/blob/1fdca787316d24586d1f6d31593c74005acc264c/includes/class-activity-dispatcher.php#L280C75-L280C89

Sorry about that, I will see how I can check that case!

**Comment by dzver** [comment]
No worries, I'm glad you found the problem!
