### ISSUE TITLE
Mention links overwritten when mentioning a handle where the username existing on the site

### ISSUE THREAD

**Issue by jeherve** [Automattic/wordpress-activitypub#842]
### Quick summary

ActivityPub mentions added in #213 are super handy, but they do not seem to work well when mentioning a handle where the username part of the handle is an existing user on the site.

### Steps to reproduce

1. On a site with the ActivityPub plugin installed, take note of your own username, e.g. `jeremy`.
2. In a new post, mention a Fediverse user also using that username, e.g. `@jeremy@mastodon.social`
3. Preview your post.

### What you expected to happen

I would expect the ActivityPub mention to be changed into `@jeremy` with a link to `https://mastodon.social/@jeremy`.

### What actually happened

The mention text remains, but a link to `https://mysite.com/author/jeremy` is added instead:

<img width="289" alt="image" src="https://github.com/user-attachments/assets/e222fb50-0f19-4ca6-bd14-8848423da5ac">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
Have you clicked the Auto-Suggestion overlay? If I simply type the full WebFinger handle without clicking anywhere else, it works like expected even if there is a local user.

**Comment by jeherve** [comment]
That doesn't seem to work that way on my site running ActivityPub + Friends + EMA:

Auto-suggestion pops, but I do not click it.

<img width="331" alt="Screenshot 2024-08-13 at 13 33 13" src="https://github.com/user-attachments/assets/7c13dfd5-7b42-4d3a-a649-c2fcf260b22e">

***************

In the editor, I see no link:

<img width="320" alt="Screenshot 2024-08-13 at 13 33 22" src="https://github.com/user-attachments/assets/d930713b-3502-4e19-9aed-39ddfb786181">

***************

On the frontend, a link is automatically created:

<img width="817" alt="Screenshot 2024-08-13 at 13 33 41" src="https://github.com/user-attachments/assets/cef2e789-61ee-48f6-a43b-2984b012bb3f">

**Comment by pfefferle** [comment]
Hmmm, will try that in combination with Friends, but never had any issues so far 😳

**Comment by pfefferle** [comment]
The weird thing here is, that the HTML looks like the ActivityPub one 🤔

**Comment by pfefferle** [comment]
I can reproduce it in combination with the friends plugin!

/cc @akirk

**Comment by pfefferle** [comment]
@jeherve @akirk maybe we should move the issue to the friends plugin?

**Comment by akirk** [comment]
Tracking this in https://github.com/akirk/friends/issues/344
