### ISSUE TITLE
Handle tagging not working on excerpts

### ISSUE THREAD

**Issue by ethicalrevolution** [Automattic/wordpress-activitypub#843]
### Quick summary

When using [ap_excerpt] and including a Fediverse handle in order to tag someone they are not tagged, but when doing the same using [ap_content] they are correctly tagged.

### Steps to reproduce

An example can be seen here: https://climatejustice.social/@mixtape@nham.co.uk/112930922676396454 where I have used [ap_content] in the ActivityPub settings and you can see that the handle of ‘dereisenhofer’ has been correctly tagged in the Mastodon post.

I had previously tried doing the same using [ap_excerpt] and including the same text in the excerpt but in doing so the Mastodon post displays the handle as text only and does not link to the account of the user handle.

The issue here is that some posts are very long and so I don’t want to display the entire [ap_content] but I do want to still be able to tag an account. Should this be possible to achieve using the [ap_excerpt] tag?

### What you expected to happen

The user handle to display in the Mastodon post as a link to the user.

### What actually happened

The user handler displays as plain text with no link through to the user.

### Impact

One

### Available workarounds?

No but the platform is still usable

**Comment by obenland** [comment]
Mentions and hashtags should work, even with the `ap_excerpt` template tag, [I learned today](https://github.com/Automattic/wordpress-activitypub/pull/1039#issuecomment-2517813478), and [can confirm](https://mastodon.social/@obenland@obietester.blog/113595362038385582).

@ethicalrevolution It looks like [it displays correctly here](https://mastodon.social/@mixtape@nham.co.uk/112930922984707156)?

**Comment by obenland** [comment]
I'll mark it as `worksforme` for now, it looks like that should work as expected.

@ethicalrevolution Please feel free to re-open if there are reproducible steps that prevent this from working correctly.

**Comment by ethicalrevolution** [comment]
Hi,
Thanks for looking in to this for me. It works on the link you posted because that is a full post, not an excerpt. However, I’ve just retested as I was doing previously and it is now working! 
Test post 1 shows tag working in the body, as has always been the case: https://openspurs.uk/2024/12/09/test-1/
Test post 2 shows tag also working in the excerpt, which it hadn’t been doing before: https://openspurs.uk/2024/12/09/test-2/
Screenshot shows it as rendered in Mastodon.
Thank you,
Sam
![Image](https://github.com/user-attachments/assets/c73ccb93-80ac-4545-9d46-93f0c89e56a9)

**Comment by pfefferle** [comment]
Thanks a lot for verifying that it works @ethicalrevolution !!!
