### ISSUE TITLE
Comment replies via Federation: include @mentions in the JSON representation of the reply

### ISSUE THREAD

**Issue by jeherve** [Automattic/wordpress-activitypub#844]
### What

When clicking reply to reply to a comment added via Federation, it would be nice if the handle of the person you're replying to, and maybe even the handles of the all the people @-mentioned in the comment you're replying to, were added to the JSON representation of the reply.

### Why

When on a WordPress site, one does not expect to see every reply to a comment start with `@person`. Comment threading (when it is enabled) makes it very clear that the reply is in response to another comment.
Outside of the WordPress context, however, folks have gotten used to seeing `@person` in front of the replies to a post. It makes it easy to understand who is involved in a conversation.

Here is an example of a typical conversation on the Fediverse. 

- I posted an update (via a WP site)
- Donncha replied via the Fediverse, thus prepending `@jeremy` to his reply.
- Matthias replied to Donncha on the Fediverse, thus prepending both `@jeremy` and `@donncha` to his reply.
- At that point, I replied to Matthias from my WordPress site since all the replies above had been federated. I think it would be fair to expect my reply to follow the same syntax. Those `@mentions` do not need to appear on the site itself, but I think it would be nice for them to appear on the Fediverse.

<img width="644" alt="Screenshot 2024-08-09 at 10 09 40" src="https://github.com/user-attachments/assets/4a42b9f6-9886-48ef-bcff-07a85893ac9c">

### How

Related conversation: p1723189722720219-slack-C04TJ8P900J

**Comment by ethicalrevolution** [comment]
Agreed. Without them there I had assumed it was a bug and people wouldn’t be receiving my replies unless I typed out their Fediverse handle (which I’ve been doing up to now, having just learned they do get tagged!)
