### ISSUE TITLE
Example handle

### ISSUE THREAD

**Issue by nickbohle** [Automattic/wordpress-activitypub#858]
https://github.com/Automattic/wordpress-activitypub/blob/dd8f363c354ca1a25b8c9a8d95d49f0981abd88a/src/shared/dialog.js#L83

I 've just added the Follow block to my home page and in my opinion, the example handle in the description is confusing. Example is: yourusername@example.com It misses the first AT, for example. Why not @YourUsername@server.com or @YourUsername@instance.com

**Comment by pfefferle** [comment]
It does work with and without a leading `@`. The specification (WebFinger) is without the `@`, this is only a Mastodon thing.

But I agree, it might be consistent to add it. Thanks for the report.

**Comment by pfefferle** [comment]
done
