### ISSUE TITLE
Standard Hashtags in Template

### ISSUE THREAD

**Issue by nesges** [Automattic/wordpress-activitypub#859]
I use `<p>[ap_hashtags]</p>` and like to add some standard hashtags for Mastodon in that template. I tried with `<p>[ap_hashtags]#dnd #pnpde</p>` but the manually added tags rendered as hashtags in Mastodon (not linked, not found via search). Here's a working example using that template: [https://mastodon.pnpde.social/@d3@www.dnddeutsch.de/112964984084322002](https://mastodon.pnpde.social/@d3@www.dnddeutsch.de/112964984084322002)

Not sure if it's a bug or a feature request.

Here's my full template:

```
<p><strong>[ap_title]</strong></p>

[ap_content]

<p><a href="[ap_permalink]">[ap_permalink]</a></p>

<p>[ap_hashtags] #dnd #pnpde</p>
```

**Comment by pfefferle** [comment]
FYI: https://github.com/Automattic/wordpress-activitypub/issues/283
