### ISSUE TITLE
Approve & Always Allow button broken

### ISSUE THREAD

**Issue by mediaformat** [Automattic/wordpress-activitypub#865]
### Quick summary

I want to allow trusted fediverse users to bypass comment moderation, however **approving** these users is currently impossible

https://github.com/user-attachments/assets/2cb304ae-6ee4-4133-a488-fa909a40aa5b

### Steps to reproduce

1. Attempt to **Approve & Always Allow a comment**
2. Weep

### What you expected to happen

User comment should be approved and user should be approved to comment without manual moderation

### What actually happened

Ugly unstyled error screen

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
The "Approve & Always Allow a comment" is a Webmention feature and is not supported by ActivityPub (yet).

But maybe we should only show it on Webmentions, to prevent issues like that.

**Comment by pfefferle** [comment]
Closed in favour of: https://github.com/pfefferle/wordpress-webmention/pull/491
