### ISSUE TITLE
Update() activity ID is not unique

### ISSUE THREAD

**Issue by silverpill** [Automattic/wordpress-activitypub#871]
### Quick summary

WordPress instance sends Update(Actor) activity with ID in the form of `https://wordpress.example/author/dev/#update`

ActivityPub [requires](https://www.w3.org/TR/activitypub/#obj-id) IDs to be globally unique:

>all objects distributed by the ActivityPub protocol MUST have unique global identifiers, unless they are intentionally transient

### Steps to reproduce

Update profile info?

### What you expected to happen

Activity ID to be unique

### What actually happened

Activity ID is always `https://wordpress.example/author/dev/#update`

### Impact

All

### Available workarounds?

There is no user impact

**Comment by silverpill** [comment]
#920 didn't make IDs unique, it removed the `id` property

If this operation doesn't have an internal identifier, you can generate a random ID. Or revert back to `#update`, that would be better than no ID.

**Comment by pfefferle** [comment]
Oh &$%§! You are right @silverpill ! I thought it will be auto-generated by this code: https://github.com/Automattic/wordpress-activitypub/blob/6ec77ccb6913cb365fc49eb6194f3bf725080c14/includes/activity/class-activity.php#L187 but this is only used when the `Object` is the real object and not the URL! Good point!

**Comment by pfefferle** [comment]
I am working on persistent Activities, but we should generate a valid one in the meantime!
