### ISSUE TITLE
Replies to comments don’t tag previous members of discussion

### ISSUE THREAD

**Issue by ethicalrevolution** [Automattic/wordpress-activitypub#877]
### Quick summary

When replying to a comment one has to manually enter the members of the group to keep them included in the discussion. On Mastodon it works the other way whereby replying to a post automatically adds the conversation members and you can remove any you choose to.

### Steps to reproduce

1. View a comment either in the Wordpress dashboard or in the website front end on a post pge.
2. Hit reply.
3. The reply box is empty when it should include the Fedi handles of the existing members of the group.

### What you expected to happen

Handles to be automatically included when a reply box is opened as per this screenshot (for which I’ve had to manually type each handle).
![IMG_2536](https://github.com/user-attachments/assets/6eef925e-ed2d-4f1d-b984-e5e123d0f7d2)

### What actually happened

The reply box has no handles and so without manually adding them none of the previous members of the conversation are aware of their comments being responded to. 
![IMG_2535](https://github.com/user-attachments/assets/d7d5549f-7a04-4975-a9fb-9864b30126e3)

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Logs or notes

(I’ve put ‘difficult’ to implement because at times you can be manually typing a large number of handles and inevitably end up having to fix typos)

**Comment by pfefferle** [comment]
It pings every user in the thread even without mentioning them directly in the post!

**Comment by ethicalrevolution** [comment]
Ooooh, wow! I can stop typing out each user’s handle now then! 😂🤦‍♂️

**Comment by pfefferle** [comment]
In my experience, the @-replies in the comment are only aesthetics, the real mentions are in the ActivityPub meta.

You can see an example here: https://notiz.blog/?c=1973265&activitypub

All other people that are in the thread are tracked in the tags array as type `Mention` and the reply is sent to their inboxes.

But this could be wrong, or might have changed over time... please let me know if I am wrong 🫣

Btw. we also thought about adding the @-replies only to the ActivityPub representation and hide it on the frontend: https://github.com/Automattic/wordpress-activitypub/issues/844

**Comment by mikewmerritt** [comment]
Only disadvantage to this approach, maybe, is on some implementations like Mastodon, which tend to include everybody mentioned upthread when you click reply. I looked on my Mastodon account at that same reply, and when clicking Reply to it, the mentions only include you.

Opinions may vary on if this is desirable, anyway. Sometimes I've only wanted to reply to the single person, so having to remove the other names annoys me, but it might be expected in many cases, just based on past usage of Mastodon.

**Comment by pfefferle** [comment]
@mikewmerritt really good point! have you checked https://github.com/Automattic/wordpress-activitypub/issues/844 ???

**Comment by ethicalrevolution** [comment]
The trouble is it'

> Only disadvantage to this approach, maybe, is on some implementations like Mastodon, which tend to include everybody mentioned from upthread when you click reply. I looked on my Mastodon account at that same reply, and when clicking Reply to it, the mentions only include you.
> 
> Opinions may vary on if this is desirable. Sometimes I've only wanted to reply to the single person, so having to remove the other names annoys me, but it might be expected in many cases, just based on past usage of Mastodon.

It sounds as though you don't have the option to only reply to one person when replying via the ActivityPub plugin because even if the handles are stripped they're all still pinged anyway, as Matthias pointed out.

The issue I had (and I imagine any other lay user) is that I assumed nobody was being replied to because the handles didn't appear in my reply. I ended up manually inserting them, lots of them! It's only because of reporting it here that I've found out I needn't have. If I wasn't minded to come in here (as I suspect most lay users wouldn't) then I'd be continuing to manually add every member of the thread I wanted to include in the reply.

**Comment by mikewmerritt** [comment]
> @mikewmerritt really good point! have you checked #844 ???

Yes. I think it's a good idea!

**Comment by pfefferle** [comment]
Can we close this one then?

**Comment by pfefferle** [comment]
I will close this for now, please re-open if you think it is still an issue!
