### ISSUE TITLE
Blog is at /blog which I believe means the webfinger cannot resolve

### ISSUE THREAD

**Issue by ross-spencer** [Automattic/wordpress-activitypub#878]
### Quick summary

Most of the plugin settings look good, but the site cannot be found on Fediverse instances.

### Steps to reproduce

According to my settings my profile can be found with: `exponentialdecay.co.uk@exponentialdecay.co.uk` but if you try to find via Mastodon for example it won't return.

### What you expected to happen

Ideally it would resolve and folks could follow the blog.

### What actually happened

Site doesn't resolve.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

Webfinger: https://exponentialdecay.co.uk/blog/.well-known/webfinger?resource=acct:exponentialdecay@exponentialdecay.co.uk

Screenshot of settings

![image](https://github.com/user-attachments/assets/f5b99ef0-8ade-4b4a-aa4e-150756652c14)

**Comment by pfefferle** [comment]
As already discussed on Mastodon, you can find a HowTo at the FAQ of the plugin: https://github.com/Automattic/wordpress-activitypub?tab=readme-ov-file#what-if-you-are-running-your-blog-in-a-subdirectory

**Comment by pfefferle** [comment]
I will close this, because it is not really a bug. Maybe it is something we should discuss here: https://github.com/Automattic/wordpress-activitypub/discussions

**Comment by ross-spencer** [comment]
@pfefferle apologies, I misunderstood. I followed the FAQ and can confirm it worked which it pretty great. Thank you :pray:

**Comment by pfefferle** [comment]
No problem ☺️

I am happy that it works!
