### ISSUE TITLE
HTML code in excerpts seeing content from Mastodon

### ISSUE THREAD

**Issue by talksina** [Automattic/wordpress-activitypub#889]
### Quick summary

When publishing a content on WordPress blog, ActivityPub returns HTML code instead of text, in Mastodon networks.

### Steps to reproduce

1. Try to go to: - mastodon . social / @network @plusbrothers . net
-I put spaces in order to avoid undesired effects here in Github
2. you should see last posts
3. in last posts, the excerpt (or first sentence before the "read more") is enclosed between < p > tags instead of seeing pure text. And even the "& numbers;" code instead of apostrophes.

### What you expected to happen

only text should appear.

### What actually happened

pure html code is displayed

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

platform: mastodon. Plugin version: activitypub 3.2.2.

**Comment by pfefferle** [comment]
What is the issue with having HTML code?

**Comment by talksina** [comment]
On Mastodon it's not readable because of the code enclosing the post - not
appealing and not screen reader friendly having to read "< p > this is my
new blog post, read on! < / p >" ...

**Comment by pfefferle** [comment]
why does the screen reader reads the HTML tags 😳

can you maybe send me some example links?

**Comment by pfefferle** [comment]
Oh, I see! But this is not a problem of pure ActivityPub! There seem to be a plugin that interferes with ActivityPub!

**Comment by talksina** [comment]
I'll try to deactivate my new shortcode-based plugins temporarily, but they
shouldn't be the issue. Problem occurred as soon as I installed latest
ActivityPub 3..2.2.

**Comment by talksina** [comment]
Problem still persists and I really don't know how to deal with it, while testing it worked but not when publishing a real article in standard format (status worked instead).

**Comment by talksina** [comment]
@pfefferle - I have tested ActivityPub further (latest stable build) and HTML tags are still there. Even with just activitypub installed. I thought it was excerpt, or the "read more", but I fear something has been broken from your part - if it were a plugin, even the "status" format and custom post types should be broken. So, why only "standard" post is? And only on Mastodon.

**Comment by pfefferle** [comment]
The change is not released yet!

**Comment by talksina** [comment]
Was it fixed in 3..2..4 released a couple days ago? If so, the bug still persists.

**Comment by pfefferle** [comment]
I added a screen reader text in v3.2.5

**Comment by talksina** [comment]
I doubt it's a matter of screen readers, this < p > appearing in Mastodon's rendering of activitypub posts. If you go to your mastodon and try to search for my blog - @network@plusbrothers.net - you should find it (tried also deactivating all plugins). It does it only with Standard format, Status works.

**Comment by pfefferle** [comment]
Yes, it is because mastodon has issues with html in the summary field and that is only used by standard posts. I removed all html, so every new post should look fine now! It is also reported to mastodon and they are working on a fix.
