### ISSUE TITLE
Latest AP update (3.2.2) removes facepiles

### ISSUE THREAD

**Issue by cybeardjm** [Automattic/wordpress-activitypub#890]
### Quick summary

I use @janboddez' Indieblocks facepile to show webmentions on my 2 blogs.
With the latest update to the ActivityPub plugin, the facepile block disappears from the frontend

### Steps to reproduce

- have a post with webmentions (e.g. likes or reshares...)
- disable the AP plugin => facepile shows
-  reenable the AP plugin => facepile disappears

### What you expected to happen

Have both AP and Indieblocks work properly together...

### What actually happened

After not being able to edit any post on my blogs with 3.2.1, it appears the "Extra-Fields check" in 3.2.2 is not thorough enough...

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
I do not think that it is an issue with the Extra-Fields, but maybe the filter that hides `Like` and `Announces`!?! Can you help with debugging @janboddez ??

**Comment by janboddez** [comment]
Ah, I see.

I'd bet this is the same thing we saw when Webmention got better block theme support (and started filtering out likes etc. from comment queries). ActivityPub now does the same (i.e., by default filters out the same comment types from comment queries, including the Facepile block's)!

I will have to update IndieBlocks then, to make it compatible again.

**Comment by janboddez** [comment]
I.e., the culprit is this line of code (sort of): https://github.com/Automattic/wordpress-activitypub/blob/5aaa2e3629416ef25cb50fdeb390fb1ffb2af86c/includes/class-comment.php#L28

But there's no need to remove it; I just have to make IndieBlocks smarter!

**Comment by janboddez** [comment]
IndieBlocks 0.13.1 should fix this. But it may require you flush your page and object cache. Or transients.

And also, I have recently been messing with the Facepile (Content) block, so if things look off ... let me know over in IndieBlocks' repository.

**Comment by pfefferle** [comment]
Thanks a lot @janboddez 

I will close this issue for now, please re-open if we still have to implement something on AP level!
