### ISSUE TITLE
Error Commenting From Friends Feed

### ISSUE THREAD

**Issue by jeckman** [Automattic/wordpress-activitypub#891]
### Quick summary

Trying to comment on a post inside my Friends Feed: 

Fatal error: Uncaught Error: Class 'Enable_Mastodon_Apps\Entity\Account' not found in /[pathto]/wp-content/plugins/activitypub/integration/class-enable-mastodon-apps.php:182 

Stack trace: 
#0 /[pathto]/wp-content/plugins/activitypub/integration/class-enable-mastodon-apps.php(459): Activitypub\Integration\Enable_Mastodon_Apps::get_account_for_actor('https://mastodo...') 
#1 /v[pathto]/wp-includes/class-wp-hook.php(324): Activitypub\Integration\Enable_Mastodon_Apps::api_get_replies(Array, 387418, 'https://mastodo...') 
#2 /[pathto]/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array) 
#3 /[pathto]/wp-content/plugins/friends/feed-parsers/class-feed-parser-activitypub.php(2240): apply_filters('mastodon_api_st...', Array, 387418, 'https://indiewe...') 
#4 /[pathto]/wp-includes/class-wp-hook.php(324): Friends\Feed_Parser_ActivityPub->get_remote_comments(Array, 387418) 
#5 /[pathto]/wp-include in /[pathto]/wp-content/plugins/activitypub/integration/class-enable-mastodon-apps.php on line 182

### Steps to reproduce

Reading a feed of posts from the Friends plugin, click on comments on a single post

### What you expected to happen

Get the ability to see the comments and maybe comment on the post? 

### What actually happened

Got the above stack trace inline 

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

WordPress 6.6.2, Activity Pub 3.2.2, Friends 2.9.5

Post I was trying to comment on: https://indieweb.social/@brentsimmons/113115596379696208  (a Mastodon instance)

**Comment by akirk** [comment]
Hm, to me this seems rather that the `integration/class-enable-mastodon-apps.php` file [is loaded even without EMA being installed](https://github.com/Automattic/wordpress-activitypub/blob/master/integration/load.php#L38-L39). I think we need to check if the plugin is loaded before loading the integration, don't you think, @pfefferle?

**Comment by pfefferle** [comment]
oh, you are right! why that 🫣

**Comment by pfefferle** [comment]
aaaah, I thought it might not be a problem, because it only loads through filters, but the `use ...` might be the issue!

**Comment by akirk** [comment]
The `use` should be ok but the problem is that the Friends plugin uses the filter that maybe EMA might implement (and ActivityPub extends by utilizing EMA functions). If EMA is not installed, then the filter the Friends plugin uses just does nothing. But since ActivityPub also registers for it, it will be called, assuming the call can only come from EMA which is not installed.

**Comment by pfefferle** [comment]
but again: isn't it a friends plugin issue then?

**Comment by akirk** [comment]
I am not sure. I think I should be able to use a filter provided by a plugin and rely that it will work with or without the plugin and not fatal.

**Comment by jeckman** [comment]
EMA = Enable Mastodon Apps? 

Just trying to figure out how to solve for it

**Comment by akirk** [comment]
@jeckman Oh, yes, sorry. If you feel comfortable with you can apply the patch like in https://github.com/Automattic/wordpress-activitypub/commit/51dea3d23b48791a71eb0229fe0e8052b2061869 or straight comment out that `include` and the following line until the new version is released.
