### ISSUE TITLE
Missing leading @ symbol in username on the follow-me block

### ISSUE THREAD

**Issue by cdevroe** [Automattic/wordpress-activitypub#897]
### Quick summary

In the edit view of the follow-me block the @ symbol is missing from the view, making the username/account look like an email address.
<img width="753" alt="image" src="https://github.com/user-attachments/assets/cfa4409e-9ea2-4f98-aca5-1d89470e4095">

### Steps to reproduce

1. Add the follow-me block
2. Select a specific author
3. Compare the editor view with the front-end view of the block

### What you expected to happen

I would expect full usernames in the block preview; e.g. @colin@cdevroe.com 

### What actually happened

Instead I see colin@cdevroe.com (which looks like an email address, because it is my email address!)

### Impact

All

### Available workarounds?

There is no user impact

### Logs or notes

I'm submitting a simple patch that _may_ address it. But I couldn't decide exactly where the best place to add the @ symbol in. So, I figured someone else should address it.

**Comment by cdevroe** [comment]
Possible fix in `src/follow-me/follow-me.js` line 35...

```javascript
function Profile( { profile, popupStyles, userId } ) {
	let { avatar, name, webfinger } = profile;
	webfinger = webfinger.charAt(0) !== '@' ? '@' + webfinger : webfinger;
```

I doubt this is the best solution to this issue. But it is one possible way of addressing it.

**Comment by pfefferle** [comment]
@cdevroe this seems to be a bug in the block-editor... if you publish the post, the frontend shows the leading `@`...

**Comment by cdevroe** [comment]
> @cdevroe this seems to be a bug in the block-editor... if you publish the post, the frontend shows the leading `@`...

Yes, I was aware of that. But shouldn't the preview in the editor also show the @ symbol?
