### ISSUE TITLE
Add promonent link to GitHub on Plugin page (wordpress.org)

### ISSUE THREAD

**Issue by maltfield** [Automattic/wordpress-activitypub#928]
This ticket is a request to update the [plugin page](https://wordpress.org/plugins/activitypub/) with a prominent link back to [this github repo](https://github.com/Automattic/wordpress-activitypub/)

 * https://wordpress.org/plugins/activitypub/ ->
 * https://github.com/Automattic/wordpress-activitypub/

# Problem

I find it very difficult to find this GitHub repo

When I do a ctrl+f for the word "github" or "git" or "vcs" or "bug" or "feature" on the wordpress.org page for this plugin, I get 0 results for all of these.

When I click on the "Development" tab, there is a bunch of prominent links to the svn mirror, and **there is only one link to this GitHub *very bottom* of the page**.

# Solution

I think we should make at least three changes to the plugin page:

1. Add a new question to the FAQ: "How do I submit a bug or feature request?" with an answer that includes a link to this github repo
2. Somewhere on the page, outside of the FAQ, the keyword word "git" should be used, with a link to this repo (eg "Development activity is done on our [GitHub repo](https://github.com/Automattic/wordpress-activitypub/) github.com/Automattic/wordpress-activitypub/")
3. If possible, the primary links under the "Development" tab should point to GitHub, not svn. If not possible, then a very prominent warning notebox should be added as high-as-possible in the page telling the user that svn is a mirror and the main development activity happens on GitHub, with a link to this repo

**Comment by pfefferle** [comment]
There is a prominent "Contribute to the plugin" link at the top right of the page, that links to GitHub!

**Comment by maltfield** [comment]
@pfefferle can you update that link to literally include the keyword "git" or "repo" or "vcs" or "forge"? It doesn't come-up for common keywords that folks will ctrl+f. For example:

```
Contribute to this plugin on our GitHub repo
```

would be better than 

```
Contribute to this plugin
```

Also, of course, an image/font icon of github would make it much easier to visually see too

 * https://fontawesome.com/icons/github

This would solve [2] above, but I do think we should also implement [1] and [3]  as well.

**Comment by pfefferle** [comment]
The problem is, that I can't change the wording on WordPress.org. I can simply setup the link.

I can add a link to the top of the changelog, like I do here: https://wordpress.org/plugins/webmention/#developers

**Comment by maltfield** [comment]
Are you opposed to adding it to multiple places (ie in addition to the link at the top, also adding it to the body where you *can* change the wording)?

IMHO, good documentation has important information stated many times in multiple places in many ways.

**Comment by obenland** [comment]
The "Contribute to this plugin" link at the top of the right sidebar is probably as easy to find as it gets. Beyond that I could recommend adding the repository to your browser's bookmarks.
