### ISSUE TITLE
Text-formatting bulleted lists in Fedi-version

### ISSUE THREAD

**Issue by 1br0wn** [Automattic/wordpress-activitypub#933]
Hi. Love this plugin, thank you! Tiny issue I’ve noticed: it doesn’t reflect bulleted lists in WordPress in the text version in the Fediverse. See for example https://www.ianbrown.tech/2024/10/09/mastodon-and-bluesky-show-interoperability-in-action/ vs the Fedi version from @ian@ianbrown.tech (I’ve looked for this elsewhere here but couldn't see it; apologies if it’s hidden more deeply in eg style template issues.) 🙏🏻

**Comment by pfefferle** [comment]
I am not sure I understand your request properly. It shows pretty nice on my side!?!

![Image](https://github.com/user-attachments/assets/1dea90e2-9057-42af-9957-d39ff0ea5b72)

**Comment by 1br0wn** [comment]
Sorry not to be clearer. My favourite Fedi-app, Ivory, shows the first paras in text format as follows. The bullet list could obviously be rendered in pure text. (But I appreciate if you think that is an issue that should be dealt with better by clients rather than your plugin.)

Even after two years of Musk damaging exTwitter so badly Fidelity has now marked down its own holdings by 78.7% (😱), alternative services have still not reached anything like its scale. I’d hypothesise two reasons are:The interactions which make social networking services (SNSes) so worthwhile are by definition much harder to build up when there are far fewer users — the chicken and egg problem which so entrenches incumbents. While it’s perfectly possible for users to maintain accounts on multiple (free!) services, and flip between apps (known as multi-homing), this does impose some user cognitive load.

**Comment by pfefferle** [comment]
The problem is, that I can't format it in a different way. We send always the full HTML and hope that other platforms and apps will display it properly.

**Comment by 1br0wn** [comment]
No problem. I thought it might be possible to make multiple content-types available. I will ask my app developers instead :)

**Comment by pfefferle** [comment]
We could send it as Markdown, but then the Web-Version would look a bit clumsy!

**Comment by 1br0wn** [comment]
Thanks! I guess (with no evidence ;) more people use web clients than app readers. (I noticed the other app I use, openvibe, has similar problems rendering the HTML as plain text. I’ll tell them too.)
