### ISSUE TITLE
Bug? Posts by Authors without ActivityPub privilege are not shared by Blog Profile

### ISSUE THREAD

**Issue by cdevroe** [Automattic/wordpress-activitypub#948]
### Quick summary

(I'm not sure if this should be considered a bug or if it is working exactly how it is designed.)

My goal is that I have a WordPress Author that I'd prefer not to have an ActivityPub profile, but still want the Blog Profile to share posts by that Author. If I turn Disable ActivityPub for that WordPress Author, but have the Blog Profile turned on in the ActivityPub plugin's settings, the Blog Author does not share/post posts by that WordPress Author. 

### Steps to reproduce

1. In the ActivityPub plugin's settings: Enable Author-Profiles
2. In the ActivityPub plugin's settings: Enable Blog Profile
3. In Users panel in WordPress Admin, disable ActivityPub for a single user
4. Publish a post by that user

### What you expected to happen

The Blog Profile would still share the post via ActivityPub.

### What actually happened

It did not.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Perhaps the user expectation is that this is working properly. If I disable an Author from ActivityPub, perhaps it is reasonable to conclude I don't want posts authored by the user to be shared at all. So perhaps this would need to be a new setting?

**Comment by cdevroe** [comment]
Examples: 

- My blog profile: https://cdevroe.com/@colin
- My author profile (which I do not want) https://cdevroe.com/@cdevroe

Browser pub link: https://browser.pub/https://cdevroe.com/@colin

(I currently have the author profile for "cdevroe" disabled for ActivityPub.)

**Comment by pfefferle** [comment]
@cdevroe one question: Why have you not simply disabled author-profiles completely, if you do not use them?

**Comment by cdevroe** [comment]
Because I was experimenting with having multiple authors based on some of my side projects. 

I think if I could have done _anything_... I would allow me to rename my author's profile name. So, many moons ago I setup my WordPress Author as "cdevroe". But I don't want my ActivityPub profile to be @cdevroe@cdevroe.com -- but there is no way to specify that I'd prefer to use "colin". If I was able to do that, I wouldn't need a blog profile at all.

**Comment by pfefferle** [comment]
But the question is still: why don't you simply disable all author profiles?

**Comment by cdevroe** [comment]
I will do so and just forgo the desire to have multiple profiles powered by my blog. Thank you!

**Comment by pfefferle** [comment]
Oh no, you don't have to, the PR will fix your issue and you can keep your settings as they are!!!

This questions are not meant to force you to change something, I simply want to understand the needs of every user, to improve the plugin and to maybe rework some things!

**Comment by cdevroe** [comment]
OK Matthias! 😄 

So, I could eventually see having as many as 3 profiles powered by my blog. So, that is why I hadn't disabled all author profiles. Does that make sense?

**Comment by pfefferle** [comment]
Totally! ... and I know at least one other blog owner who is interested in that feature!

Sorry if my question was a bit misleading!

**Comment by cdevroe** [comment]
No worries! For now, I'll turn profiles off and just keep the blog profile so that posts are shared through that. Perhaps my specific case cannot be fixed since I have a username I wish I didn't. That is totally fine.

**Comment by pfefferle** [comment]
@cdevroe https://github.com/Automattic/wordpress-activitypub/pull/915 :)

**Comment by cdevroe** [comment]
I see that PR is paused. Which totally makes sense. Thank you for even taking the time to look at it!

**Comment by pfefferle** [comment]
yes, it is a bit complex and we might need the `Move` functionality first!
