### ISSUE TITLE
Comments are no longer mirrored from Fediverse to Wordpress

### ISSUE THREAD

**Issue by Sesivany** [Automattic/wordpress-activitypub#954]
### Quick summary

I run two Wordpress blogs with the ActivityPub enabled. When I publish a blog post that is federated and people comment on it in the Fediverse, the comments no longer show up in Wordpress. It worked for posts last week, didn't work today. I haven't changed any settings. There was an update to 4.0.0 in that period of time, so it might be associated with that.

I'd be more than happy to provide useful logs if you instruct me where to get them.

### Steps to reproduce

1. Create a blog post at https://blog.eischmann.cz/
2. Someone comments on the federated post.
3. The comment doesn't get mirrored to Wordpress.

### What you expected to happen

1. Create a blog post at https://blog.eischmann.cz/
2. Someone comments on the federated post.
3. The comment shows up among comments to approve in Wordpress.

### What actually happened

Posts from Fediverse get mirrored to the blog.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by Sesivany** [comment]
I can confirm that after downgrading the plugin to 3.3.0, it works again.

**Comment by pfefferle** [comment]
It seems to be no general issue, because "it works on my machine" ☺️

**Comment by pfefferle** [comment]
What timezone you are in? That we might cue up a test tomorrow?

**Comment by Sesivany** [comment]
My timezone is CEST (UTC+2).

**Comment by seymour1006** [comment]
I have the same problem, since 4.0.0 there are no comments in 4 wordpress sites I use.

And follow requests are also not accepted

I have uninstalled all plugins for testing. But it still does not work.

When I installed a completely blank Wordpress with only the ActivityPub plugin, however, it worked there.

**Comment by pfefferle** [comment]
Can you also send me some URLs so that I can test? I also improved the unit tests and they are all green for 4.0.0. Maybe an issue with the migration!?!

**Comment by pfefferle** [comment]
@seymour1006 have you downgraded to the 3.X version? I tried it with your mapf blog and following worked fine!

**Comment by Sesivany** [comment]
I downgraded the plugin on one blog, but kept it on the other: https://enblog.eischmann.cz/, Fediverse handle: @brnohat@enblog.eischmann.cz

I have one other plugin related to Mastodon installed: Simple Mastodon Verification. But even when I disabled it, it still didn't work with 4.0.0.

**Comment by pfefferle** [comment]
@Sesivany oh perfect, can you please keep the 4.0.0 on that blog for some more days, so that I can run some tests against it?

**Comment by pfefferle** [comment]
@Sesivany can you test something for me?

Can you edit `includes\rest\class-server.php` scroll to the `request_parameter_order` function and edit the `return` to:

```
return array(
	'JSON',
	'POST',
	'URL',
	'defaults',
);
```

**Comment by seymour1006** [comment]
Yes, I have version 3.3.3 installed again. But I can do the update again if it helps.

**Comment by pfefferle** [comment]
I just released v4.0.1 and that should fix the issue.

**Comment by Sesivany** [comment]
@pfefferle I'm away from any desktop computer for the weekend. I'll test it once I get back.

**Comment by seymour1006** [comment]
> I just released v4.0.1 and that should fix the issue.

It works 👍🏼 🙏🏼

**Comment by pfefferle** [comment]
I will close this issue for now, please re-open if still an issue!
