### ISSUE TITLE
Error after upgrade to 4.1.0

### ISSUE THREAD

**Issue by baby-gnu** [Automattic/wordpress-activitypub#972]
### Quick summary

Our wordpress sent us an alert:

```
Une erreur de type E_ERROR a été causée dans la ligne 286 du fichier /var/www/vhosts/emancipation.fr/httpdocs/wp-content/plugins/activitypub/includes/class-admin.php. Message d’erreur : Uncaught Error: Call to undefined function Activitypub\home_host() in /var/www/vhosts/emancipation.fr/httpdocs/wp-content/plugins/activitypub/includes/class-admin.php:286
Stack trace:
#0 /var/www/vhosts/emancipation.fr/httpdocs/wp-includes/class-wp-hook.php(324): Activitypub\Admin::register_settings()
#1 /var/www/vhosts/emancipation.fr/httpdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /var/www/vhosts/emancipation.fr/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/vhosts/emancipation.fr/httpdocs/wp-admin/admin-ajax.php(45): do_action()
#4 {main}
  thrown
```

### Steps to reproduce

1. Update the plugin

### What you expected to happen

No error message is sent to admins.

### What actually happened

Wordpress sent us an error report.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

Here are the technical information

- WordPress version 6.6.2
- Thème actif : Twenty Twenty-Three (version 1.5)
- Extension actuelle : ActivityPub (version 4.1.0)
- PHP version 8.3.12

**Comment by pfefferle** [comment]
@baby-gnu do you have a PHP object caching in place? If so, can you try to clear caches? Can you also check if `includes/functions.php` exists?

**Comment by baby-gnu** [comment]
I purged the cache and updated to 4.1.1 and did not receive an error mail.

**Comment by pfefferle** [comment]
So it seems to work for you now @baby-gnu ?

**Comment by baby-gnu** [comment]
yes.

**Comment by pfefferle** [comment]
Then I will close this for now! Please re-open if you see the error again!
