### ISSUE TITLE
4.1 has removed my custom tag

### ISSUE THREAD

**Issue by ethicalrevolution** [Automattic/wordpress-activitypub#980]
### Quick summary

I have three sites using ActivityPub and all three have had my custom tag removed on this upgrade which had previously allowed the post to link back to the website with custom text such as ‘read more’. Dashboard screenshot shows where the tag was and is now missing. Mastodon screenshot shows what a post looked like before the tag had been removed (yellow arrow pointing to the rendered tag …I can’t remember exactly how the tags were written in the dashboard side but I had used the documentation to write them originally.)

### Steps to reproduce

As above

### What you expected to happen

Custom tag to have remained in the box.

### What actually happened

It was removed.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

![Image](https://github.com/user-attachments/assets/0944171d-cc56-4be5-b851-45e14419732e)
![Image](https://github.com/user-attachments/assets/36dd7316-ed44-44e1-af60-37d018794d0d)

**Comment by pfefferle** [comment]
Oh no, I think I forgot to handle the "custom" case! I am so sorry and will fix that asap!

For your issue: It would have been something like `<a href="[ap_permalink type="url"]">[Via Ethical Revolution]</a>`

**Comment by ethicalrevolution** [comment]
Super, thanks for the code. Never any need to be sorry. I’m extremely grateful for your work and am happy to be able to contribute by reporting anything I notice. 👍

**Comment by ethicalrevolution** [comment]
I notice you've issued a fix but having updated to 4.1.1 I'm still unable to put the custom link in: I type in '<a href="[ap_permalink type="url"]">[Via Ethical Revolution]</a>' and click save and it then changes itself to just '<a>[Via Ethical Revolution]</a>'.

**Comment by pfefferle** [comment]
oh!

**Comment by pfefferle** [comment]
Oh sorry, this interferes with the `wp_kses`! It works if you simply remove the type  `<a href="[ap_permalink]">[Via Ethical Revolution]</a>` or change the double-quotation-marks to single-quotation-marks `<a href="[ap_permalink type='url']">[Via Ethical Revolution]</a>`.

**Comment by ethicalrevolution** [comment]
That's sorted it!

**Comment by pfefferle** [comment]
I will close this for now, because the migration is fixed for upcoming migrations and you problem seems also solved. Feel free to re-open if still an issue and sorry one again @ethicalrevolution
