### ISSUE TITLE
Does not allow following & posts not appearing in Mastodon

### ISSUE THREAD

**Issue by remouk** [Automattic/wordpress-activitypub#981]
### Quick summary

I installed ActivityPub on my blog which is hosted on Wordpress.com (business) : https://danstonchat.com/
I chose blogwide account (no author pages/ActivityPub accounts).

When searching for the account (`@danstonchat.com@danstonchat.com`), it appears. It's missing the logo but the other informations are there.

When someone tries to follow it , it doesn't work. The requests to follow are sent but not "allowed".

I tried with my own account on the https://piaille.fr/ instance. It doesn't work.

In the "followers" page (in WordPress admin), the list is empty.

When I post, nothing appears on Mastodon. Weird thing: someone did share a link to one of the post, and now it appears on the account page.

### Steps to reproduce

- Go to you Mastodon (any ActivityPub?) instance
- Search for `@danstonchat.com@danstonchat.com`
- Try to follow it

### What you expected to happen

- You should be allowed to follow
- Posts should appear on your timeline

### What actually happened

- Nothing

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by pfefferle** [comment]
Hey @remouk 👋

where do you host your site? Maybe it is an issue with `mod_rewrite`?

https://blog.rac.me.uk/2022/11/10/activitypub-for-wordpress-how-to-fix-modsecurity-to-make-it-work/

**Comment by remouk** [comment]
Hi @pfefferle ! :) I'm hosting on Wordpress.com (Business plan)

**Comment by pfefferle** [comment]
Hmmm! Ok, it should work there!!! Let me have a look!

**Comment by pfefferle** [comment]
@remouk do you use a security/firewall plugin?

**Comment by remouk** [comment]
Nope! 
Pretty standard stuff (jetpack/akismet...) and a few custom plugins to add favorites, reactions on posts and to colour the quotes (html formatting).

**Comment by remouk** [comment]
@pfefferle May I provide you anything useful? I'm stuck 😅 Thank you so much

**Comment by pfefferle** [comment]
May I ask what version of the plugin you use, because we had an issue in version 4.0.0!

**Comment by mattwiebe** [comment]
Really sorry about this @remouk - we are digging into this but it's not failing for any reasons that are immediately obvious.

You could also try deactivating all other plugins. None you have seem to conflict at first glance but this is a standard debugging move.

We'll keep digging in.

**Comment by remouk** [comment]
Thanks @pfefferle and @mattwiebe - the plugin is up-to-date (currently 4.1.1).

It's complicated to deactivate a plugin or something live, because there's a lot of users on my website. I will find the best moment to do so.

Is there a "fast" way to check if it works? Because when using a Mastodon instance, those actions seems to take quite some time.

**Comment by mattwiebe** [comment]
@remouk I'm still digging into this after eliminating some more possibilities.

Although it doesn't appear to be responsible for the Follow troubles, I'll also note that the Favorites plugin is throwing a lot of errors. If you don't absolutely need it, I would suggest deactivating that for sure.

Hope we have some good news for you soon!

**Comment by mattwiebe** [comment]
@remouk I got to the bottom of this in #996. While that fix has not yet been released in a plugin update, the benefits of being on WordPress.com is that I just went and applied the fix for you. 

I just sent you a follow from my `mattwiebe@mastodon.online` account and it worked! 🎉

The next plugin release should have this fix in it, but again, you're already good to go.

**Comment by remouk** [comment]
> [@remouk](https://github.com/remouk) I got to the bottom of this in [#996](https://github.com/Automattic/wordpress-activitypub/pull/996). While that fix has not yet been released in a plugin update, the benefits of being on WordPress.com is that I just went and applied the fix for you.
> 
> I just sent you a follow from my `mattwiebe@mastodon.online` account and it worked! 🎉
> 
> The next plugin release should have this fix in it, but again, you're already good to go.

Thank you so much!! It seems to be working now! The only thing that seems to be missing is the profile picture. Do you have any idea about what should I do?

I will look into the Favorites plugin and replace it (it is an important feature to have). Thanks for pointing it out.

Really, a huge thank you, you made my day!! 🙏

**Comment by remouk** [comment]
Also I'm not sure the replies are gathered in WordPress as comments.

**Comment by mattwiebe** [comment]
![Image](https://github.com/user-attachments/assets/ac2e0552-75e6-49ff-aa95-5af14a6396f3)

**Comment by mattwiebe** [comment]
> Thank you so much!! It seems to be working now!

Awesome! Glad to get to the bottom of it for you.

> The only thing that seems to be missing is the profile picture. Do you have any idea about what should I do?

We use your site icon, it looks to be working when I browse your profile on Mastodon?

![Image](https://github.com/user-attachments/assets/29d31b34-41b3-474b-879e-3c5a2624e251)

> Also I'm not sure the replies are gathered in WordPress as comments.

They may be caught in your comment moderation queue?

**Comment by remouk** [comment]
> > Thank you so much!! It seems to be working now!
> 
> Awesome! Glad to get to the bottom of it for you.

🙏

> > The only thing that seems to be missing is the profile picture. Do you have any idea about what should I do?
> 
> We use your site icon, it looks to be working when I browse your profile on Mastodon?

Ok cool! I guess there is an image cache on each Mastodon's instance, it doesn't appear on mine but I guess it will eventually!

> > Also I'm not sure the replies are gathered in WordPress as comments.
> 
> They may be caught in your comment moderation queue?

I double checked, posted a new comment to be sure, but no they do not appear anywhere. Any idea? :(

**Comment by pfefferle** [comment]
@remouk you seem to use a very special comment-system and you also have re-captchas on your site. Can you check if either the comment system and/or re-captcha is blocking comments from the fediverse?

**Comment by remouk** [comment]
@pfefferle Thank you for your rapid answer!! Now it works. 🎉

The re-captcha is only for user sign up / sign in, it's not a problem.

The comment system is wpDiscuz, it is still the WordPress comment system under the hood. It's only a coat of paint that changes the look & feel, and adds a few features (voting on comments and stuff like that...). I deactivated it and now it works!

I thought the ActivityPub reactions were pushed through the API or something like that. So I guess the comments are added through the native comment form? So changing the comment UI is not possible? Good to know when customizing the website.

Thanks again! You've been a huge help. 🙏

**Comment by pfefferle** [comment]
@remouk the comment is sent through the API! The ActivityPub plugin does not use any Comment-Forms! But ActivityPub uses WordPress core functions to save comments, likes and boosts. It might be possible, that the re-captcha plugin also hooks into `wp_new_comment` or `wp_update_comment` to verify it's captchas.

So long story short: It might be possible that plugins that are meant to handle front-end validations, might not differentiate if the comment really comes from the form or from another source like an API.

**Comment by remouk** [comment]
Thank you for taking the time to explain. :) And thanks again for your help! Have a good day!
