### ISSUE TITLE
4.1.1 fix removed og meta?

### ISSUE THREAD

**Issue by ethicalrevolution** [Automattic/wordpress-activitypub#983]
### Quick summary

I’ve just published a post with 4.1.1 and I no longer have a preview link on Mastodon with the ‘more from Ethical Revolution’ link.

### Steps to reproduce

Screenshot 1 shows the Mastodon preview and og data before updating AP plugin.
Screenshot 2 show new post with preview missing.

### What you expected to happen

Have the preview there with the ‘more from Ethical Revolution’ link.

### What actually happened

No preview.

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

![Image](https://github.com/user-attachments/assets/5206c1ef-4a01-4c8c-bc8b-a15bee576fc2)
![Image](https://github.com/user-attachments/assets/1ebd3ed6-9a52-40a6-8c46-6226e39d3695)

**Comment by ethicalrevolution** [comment]
Should have said: og settings in WP AP dashboard remain unchanged. 
![Image](https://github.com/user-attachments/assets/f6ce78fe-2372-4d35-bbb4-1825b6f1f27f)

**Comment by pfefferle** [comment]
Oh no @ethicalrevolution we seem to have broken a lot on your site 🫣

I am not aware of any changes in this regard, but I will have a look! Do you always have two links in your posts? One at the top and one at the bottom?

**Comment by pfefferle** [comment]
OK, it seems to be no general issue: https://mastodon.art/@pfefferle/113465360744057849

**Comment by ethicalrevolution** [comment]
Hmm, that’s odd that it hasn’t worked on today’s post in that case.

If there is no external link in the text I keep it to the one generic link at the end of the post (‘[Via Ethical Revolution]’). However, if there’s an external link in the article I put a link to the WP post at the top because Mastodon chooses the first link in a post to create the preview from.

**Comment by pfefferle** [comment]
@ethicalrevolution maybe it was a glitch because of all the changes, you had to do! let's wait for the next post and see if it works there. (not very analytical, I know 🤫)

**Comment by ethicalrevolution** [comment]
Same problem on today's post (screenshot). The issue only arises when posts are made from my WP site via the AP plugin. You've already showed the preview and 'more' link to work when you post from your account and I have also managed this from my personal account. It's the WP site itself not getting the desired result.![Image](https://github.com/user-attachments/assets/61bdfa1b-bc9a-4911-9e3b-b8ad9b265f15)

**Comment by ethicalrevolution** [comment]
(Here's a screenshot showing it working when I post from my own personal account) ![Image](https://github.com/user-attachments/assets/f99d6283-b188-4d7d-bf6c-4c2d0aaa5eb7)

**Comment by ethicalrevolution** [comment]
Ufff, ignore this! I think I've found the issue! The actual link  on the offedning posts is going to the preview page (e.g. https://ethicalrevolution.co.uk/?p=15294) rather than the live page. (https://ethicalrevolution.co.uk/decarbonisation-of-uk-grid-by-2030/). Let me fix that on the site and see if it makes the difference.

**Comment by ethicalrevolution** [comment]
Yup, that's fixed it. My turn to apologise, for wasting your time. Sorry! 🙏

**Comment by pfefferle** [comment]
Oh, no problem!

And I am glad it works :)
