### ISSUE TITLE
Comments in Fediverse don't mirror back to Wordpress (since: mid October 2024)

### ISSUE THREAD

**Issue by Koelle4Future** [Automattic/wordpress-activitypub#993]
### Quick summary

We love the Activitypub plugin! It worked out very well, but as of October 16, 2024 we don't get comments mirrored back to our wordpress envirioment. 

### Steps to reproduce

Blog: https://koelle4future.de/
Fedi: @blog@koelle4future.de

Comments below any posting don't appear in Wordpress any more

### What you expected to happen

It worked out pretty nice, e.g.: 

https://koelle4future.de/blog/2024/10/15/wasserbuendnis-rheinisches-revier/

### What actually happened

Blogpost is published successfully in Fedi, but no comments are transfered back

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

Activity Version 4.1.1

Wordpress  6.7 DE

**Comment by pfefferle** [comment]
Have you checked the Spam or Trash folder for comments?

**Comment by pfefferle** [comment]
I checked your site and I noticed two things:

1. you do not show comments for events
2. your site is unavailable (503 Service Unavailable) for some minutes if I set up a comment from Mastodon. This might be because the server can't handle the requests from all of the Mastodon servers and could be the reason why the comment doesn't make it to the blog.

**Comment by Koelle4Future** [comment]
Thanks Matthias for the fast feedback. And for looking into our page. Fantastic service, very welcome. Need to look into other wordpress plugins from you and your team. 

What did we do so far: 

- database backup
- switch off all plugins, we suspected w3 total cashe or yoast as most proberbly suspects
- empty all cache we know of

This probably led to the error  Error 50X 

Giving 30 minutes of rest time

Commenting in Fedi on regular blogposts,, not events --> still no mirroring back

- no smoking gun found so far
- turning on all the plugins again
- killing SPAM because the bee was resting, too


Indeed, comments in event calender don't work, we did not know that. 

Next steps on the weekend: 

- Checking if the service provider is on an old php /  mySQL version
- downsize to the status mid of October (if possible), e.g. Wordpress 6.6 or an earlier version of ActivityPub 

Let's see.

**Comment by pfefferle** [comment]
> Commenting in Fedi on regular blogposts,, not events --> still no mirroring back

When I understand your comment on mastodon correctly, it seems to work on blog-posts!?! https://social.cologne/@P4FKoeln/113481855062775199

Regarding caching: https://github.com/Automattic/wordpress-activitypub/wiki/Caching

Regarding W3 Total Cache: https://github.com/Automattic/wordpress-activitypub/issues?q=sort%3Aupdated-desc%20is%3Aissue%20%22w3%20total%20cache%22

**Comment by Koelle4Future** [comment]
Found it! 

Our provider did not update the database, we have been running on mySQL 5.7 for years.

Now, updated to mySQL 8.0 and magic tune: comments come through! 


Thanks for listening in and your great and fast contribution.
