### ISSUE TITLE
Confusing wording `Every author on this blog` on settings page

### ISSUE THREAD

**Issue by Menrath** [Automattic/wordpress-activitypub#998]
The wording `Every author on this blog` on the general settings page has already led to confusion three times while I was observing people from organizations during the plugin-setup.

I would suggest to either replace it with `Every user account on this WordPress site that can publish posts` or add a tool-tip info button to clarify this even better.

(Accidentally reported here: https://github.com/pfefferle/wordpress-webmention/issues/497)

**Comment by pfefferle** [comment]
What version of the plugin do you currently use? Because the latest version already says:

> Every author on this blog (with the activitypub capability) gets their own ActivityPub profile. You can add/remove the capability in the [user settings.](https://pfefferle.org/wp-admin/users.php) Select all the users you want to update, choose the method from the drop-down list and click on the "Apply" button.

**Comment by pfefferle** [comment]
I will close this for now, please re-open if I am referring to the wrong example!

**Comment by Menrath** [comment]
@pfefferle The passage you cite starts with "Every author on this blog" which is the wording which has been causing confusion.

> *---* Every author on this blog (with the activitypub capability) gets their own ActivityPub profile.

> *+++* > Every user account on this WordPress site (that can publish posts and has the activitypub capability) gets their own ActivityPub profile.

I might seem impossible for our minds, but there are people who manage a WordPress site (image them taking it over in a small association) that have very little digital-education and to me the seemed worried that authors refers to persons not to user accounts (often user accounts get shared...). I admit the longer text might keep others from actually reading the setting...

**Comment by pfefferle** [comment]
Ah, sorry my attention was on the `that can publish posts` instead of the beginning of the sentence, so I have not seen the different wording there. I have no strong feelings about whether to use "user account" or "authors", so I am fine with changing it.

`that can publish posts` on the other hand is no longer true, because it is handled by the capability now and that can be added to every user regardless if the can publish posts or not.
